aitools::invertedindex::Exception Class Reference
aitools::invertedindex::Exception Class Reference
#include <Exception.hpp>
Static Public Member Functions
static void throw_invalid_argument (const std::string &msg, const bfs::path &path) throw (std::invalid_argument)
static void throw_invalid_argument (const std::string &msg) throw (std::invalid_argument)
template<typename Entry >
static void throw_out_of_range (const std::string &msg, const Record< Entry > &record) throw (std::out_of_range)
static void throw_out_of_range (const std::string &msg, unsigned value) throw (std::out_of_range)
static void throw_out_of_range (const std::string &msg, unsigned index, unsigned size) throw (std::out_of_range)
static void throw_out_of_range (const std::string &msg, unsigned off, unsigned num, unsigned size) throw (std::out_of_range)
static void throw_length_error (const std::string &msg, unsigned value) throw (std::length_error)
static void throw_logic_error (const std::string &msg) throw (std::logic_error)
static void throw_domain_error (const std::string &msg) throw (std::domain_error)
static void throw_runtime_error (const std::string &msg) throw (std::runtime_error)
static void throw_overflow_error (const std::string &msg) throw (std::overflow_error)
static void throw_underflow_error (const std::string &msg) throw (std::underflow_error)
Private Member Functions
Exception ()
~Exception ()
Detailed Description
A class that provides an interface to throw C++ standard exceptions attached with exception-dependent messages and optional user information.
Author:
martin.trenkmann@uni-weimar.de
Created on Jun 22, 2008
Id
Exception.hpp,v 1.2 2010/05/11 23:41:08 trenkman Exp
Definition at line 28 of file Exception.hpp.
Constructor & Destructor Documentation
aitools::invertedindex::Exception::Exception () [private]
The default constructor.
aitools::invertedindex::Exception::~Exception () [private]
The destructor.
Member Function Documentation
void aitools::invertedindex::Exception::throw_domain_error (const std::string & msg) throw (std::domain_error) [static]
Definition at line 65 of file Exception.cpp.
void aitools::invertedindex::Exception::throw_invalid_argument (const std::string & msg) throw (std::invalid_argument) [static]
Definition at line 14 of file Exception.cpp.
void aitools::invertedindex::Exception::throw_invalid_argument (const std::string & msg, const bfs::path & path) throw (std::invalid_argument) [static]
Definition at line 5 of file Exception.cpp.
Referenced by aitools::invertedindex::JNIGateway::create_builder(), aitools::invertedindex::JNIGateway::create_searcher(), aitools::invertedindex::System::directory_size(), aitools::invertedindex::System::fopen(), aitools::invertedindex::JNIGateway::get_builder(), aitools::invertedindex::JNIGateway::get_iterator(), aitools::invertedindex::JNIGateway::get_searcher(), aitools::invertedindex::InvertedFileWriter< Value >::open(), and aitools::invertedindex::StorageBuilder::open().
void aitools::invertedindex::Exception::throw_length_error (const std::string & msg, unsigned value) throw (std::length_error) [static]
Definition at line 49 of file Exception.cpp.
void aitools::invertedindex::Exception::throw_logic_error (const std::string & msg) throw (std::logic_error) [static]
Definition at line 58 of file Exception.cpp.
void aitools::invertedindex::Exception::throw_out_of_range (const std::string & msg, unsigned off, unsigned num, unsigned size) throw (std::out_of_range) [static]
Definition at line 39 of file Exception.cpp.
void aitools::invertedindex::Exception::throw_out_of_range (const std::string & msg, unsigned index, unsigned size) throw (std::out_of_range) [static]
Definition at line 30 of file Exception.cpp.
void aitools::invertedindex::Exception::throw_out_of_range (const std::string & msg, unsigned value) throw (std::out_of_range) [static]
Definition at line 21 of file Exception.cpp.
template<typename Entry > static void aitools::invertedindex::Exception::throw_out_of_range (const std::string & msg, const Record< Entry > & record) throw (std::out_of_range) [inline, static]
Definition at line 54 of file Exception.hpp.
void aitools::invertedindex::Exception::throw_overflow_error (const std::string & msg) throw (std::overflow_error) [static]
Definition at line 79 of file Exception.cpp.
void aitools::invertedindex::Exception::throw_runtime_error (const std::string & msg) throw (std::runtime_error) [static]
Definition at line 72 of file Exception.cpp.
Referenced by aitools::invertedindex::MPHashFunction::create_(), aitools::invertedindex::System::fread(), aitools::invertedindex::System::fseek(), aitools::invertedindex::System::ftell(), aitools::invertedindex::System::fwrite(), and aitools::invertedindex::StorageBuilder::put().
void aitools::invertedindex::Exception::throw_underflow_error (const std::string & msg) throw (std::underflow_error) [static]
Definition at line 86 of file Exception.cpp.
The documentation for this class was generated from the following files:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/util/Exception.hpp
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/util/Exception.cpp