aitools::invertedindex::Value Class Reference
aitools::invertedindex::Value Class Reference
#include <Value.hpp>
Public Member Functions
Value ()
virtual ~Value ()
virtual void clear ()=0
virtual double score () const =0
virtual void parse (std::istream &is)=0
virtual void print (std::ostream &os) const =0
virtual void to_bytes (ByteBuffer &buffer) const =0
virtual void wrap (const char *data, size_t size)=0
void wrap (const ByteBuffer &buffer)
Static Protected Attributes
static const size_t sizeof_int8_t = sizeof(int8_t)
static const size_t sizeof_size_t = sizeof(size_t)
static int tmp_int
Detailed Description
An abstract class to represent an indexable value.
Derived classes can wrap and interpret a raw ByteBuffer in a user defined manner, providing getter and setter methods, as well as I/O support.
Author:
martin.trenkmann@uni-weimar.de
Version:
Id
Value.hpp,v 1.5 2010/10/15 17:44:47 trenkman Exp
Definition at line 23 of file Value.hpp.
Constructor & Destructor Documentation
aitools::invertedindex::Value::Value () [inline]
The constructor.
Definition at line 47 of file Value.hpp.
virtual aitools::invertedindex::Value::~Value () [inline, virtual]
The destructor.
Definition at line 52 of file Value.hpp.
Member Function Documentation
virtual void aitools::invertedindex::Value::clear () [pure virtual]
Resets all internals to default values.
Implemented in aitools::invertedindex::Pair< T1, T2 >, aitools::invertedindex::PairString< T >, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >, aitools::invertedindex::Single< T >, aitools::invertedindex::SingleString, aitools::invertedindex::StringString, aitools::invertedindex::Triple< T1, T2, T3 >, and aitools::invertedindex::Triple< int64_t, int32_t, int8_t >.
virtual void aitools::invertedindex::Value::parse (std::istream & is) [pure virtual]
Parses all elements from an input stream.
Implemented in aitools::invertedindex::Pair< T1, T2 >, aitools::invertedindex::PairString< T >, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >, aitools::invertedindex::Single< T >, aitools::invertedindex::SingleString, aitools::invertedindex::StringString, aitools::invertedindex::Triple< T1, T2, T3 >, and aitools::invertedindex::Triple< int64_t, int32_t, int8_t >.
virtual void aitools::invertedindex::Value::print (std::ostream & os) const [pure virtual]
Prints all elements to an output stream.
Implemented in aitools::invertedindex::Pair< T1, T2 >, aitools::invertedindex::PairString< T >, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >, aitools::invertedindex::Single< T >, aitools::invertedindex::SingleString, aitools::invertedindex::StringString, aitools::invertedindex::Triple< T1, T2, T3 >, and aitools::invertedindex::Triple< int64_t, int32_t, int8_t >.
virtual double aitools::invertedindex::Value::score () const [inline, pure virtual]
Gets the weight of this object.
Implemented in aitools::invertedindex::Pair< T1, T2 >, aitools::invertedindex::PairString< T >, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >, aitools::invertedindex::Single< T >, aitools::invertedindex::SingleString, aitools::invertedindex::StringString, aitools::invertedindex::Triple< T1, T2, T3 >, and aitools::invertedindex::Triple< int64_t, int32_t, int8_t >.
virtual void aitools::invertedindex::Value::to_bytes (ByteBuffer & buffer) const [pure virtual]
Serializes all elements into a byte buffer.
Implemented in aitools::invertedindex::Pair< T1, T2 >, aitools::invertedindex::PairString< T >, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >, aitools::invertedindex::Single< T >, aitools::invertedindex::SingleString, aitools::invertedindex::StringString, aitools::invertedindex::Triple< T1, T2, T3 >, and aitools::invertedindex::Triple< int64_t, int32_t, int8_t >.
Referenced by aitools::invertedindex::Record< Value >::to_generic().
void aitools::invertedindex::Value::wrap (const ByteBuffer & buffer)
Interprets a byte buffer.
Reimplemented in aitools::invertedindex::Pair< T1, T2 >, aitools::invertedindex::PairString< T >, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >, aitools::invertedindex::Single< T >, aitools::invertedindex::SingleString, aitools::invertedindex::StringString, aitools::invertedindex::Triple< T1, T2, T3 >, and aitools::invertedindex::Triple< int64_t, int32_t, int8_t >.
Definition at line 10 of file Value.cpp.
References aitools::invertedindex::ByteBuffer::data(), aitools::invertedindex::ByteBuffer::size(), and wrap().
virtual void aitools::invertedindex::Value::wrap (const char * data, size_t size) [pure virtual]
Interprets a byte buffer.
Implemented in aitools::invertedindex::Pair< T1, T2 >, aitools::invertedindex::PairString< T >, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >, aitools::invertedindex::Single< T >, aitools::invertedindex::SingleString, aitools::invertedindex::StringString, aitools::invertedindex::Triple< T1, T2, T3 >, and aitools::invertedindex::Triple< int64_t, int32_t, int8_t >.
Referenced by aitools::invertedindex::Postlist< Value >::next(), and wrap().
Member Data Documentation
const size_t aitools::invertedindex::Value::sizeof_int8_t = sizeof(int8_t) [static, protected]
Size in byte of the int8_t type
Definition at line 30 of file Value.hpp.
Referenced by aitools::invertedindex::Triple< T1, T2, T3 >::parse(), aitools::invertedindex::Single< T >::parse(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::parse(), aitools::invertedindex::PairString< T >::parse(), aitools::invertedindex::Triple< T1, T2, T3 >::print(), aitools::invertedindex::Single< T >::print(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::print(), and aitools::invertedindex::PairString< T >::print().
const size_t aitools::invertedindex::Value::sizeof_size_t = sizeof(size_t) [static, protected]
Size in byte of the size_t type
Definition at line 35 of file Value.hpp.
int aitools::invertedindex::Value::tmp_int [static, protected]
Temporal integer variable used for [u]int8_t IO support
Definition at line 40 of file Value.hpp.
Referenced by aitools::invertedindex::Triple< T1, T2, T3 >::parse(), aitools::invertedindex::Single< T >::parse(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::parse(), and aitools::invertedindex::PairString< T >::parse().
The documentation for this class was generated from the following files:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/value/Value.hpp
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/value/Value.cpp