aitools::invertedindex::InternalIntroSort Class Reference
aitools::invertedindex::InternalIntroSort Class Reference
#include <InternalIntroSort.hpp>
Static Public Member Functions
template<typename Value >
static void sort (Postlist< Value > &postlist, Quantile &quantile, Sorting mode)
template<typename Value >
static void sort (std::vector< Value > &values, Quantile &quantile, Sorting mode)
Private Types
typedef Configuration::Sorting Sorting
Private Member Functions
InternalIntroSort ()
Static Private Member Functions
template<typename Value >
static void comp_quantile (const std::vector< Value > &values, Quantile &quantile)
Detailed Description
A class that provides a static method to sort a postlist in memory. The algorithm used is std::sort of the STL, which is currently an SGI implementation of introsort.
See also:
http://www.sgi.com/tech/stl/sort.html
Author:
martin.trenkmann@uni-weimar.de
Version:
Id
InternalIntroSort.hpp,v 1.12 2010/10/15 17:44:48 trenkman Exp
Definition at line 27 of file InternalIntroSort.hpp.
Member Typedef Documentation
typedef Configuration::Sorting aitools::invertedindex::InternalIntroSort::Sorting [private]
Definition at line 31 of file InternalIntroSort.hpp.
Constructor & Destructor Documentation
aitools::invertedindex::InternalIntroSort::InternalIntroSort () [private]
Member Function Documentation
template<typename Value > void aitools::invertedindex::InternalIntroSort::comp_quantile (const std::vector< Value > & values, Quantile & quantile) [inline, static, private]
Definition at line 108 of file InternalIntroSort.hpp.
References aitools::invertedindex::Quantile::at(), aitools::invertedindex::Quantile::clear(), aitools::invertedindex::Quantile::COUNT, aitools::invertedindex::Quantile::P10, aitools::invertedindex::Quantile::P100, and aitools::invertedindex::Quantile::P91.
template<typename Value > void aitools::invertedindex::InternalIntroSort::sort (std::vector< Value > & values, Quantile & quantile, Sorting mode) [inline, static]
Definition at line 89 of file InternalIntroSort.hpp.
References aitools::invertedindex::Configuration::ASCENDING, and aitools::invertedindex::Configuration::DESCENDING.
template<typename Value > void aitools::invertedindex::InternalIntroSort::sort (Postlist< Value > & postlist, Quantile & quantile, Sorting mode) [inline, static]
Definition at line 59 of file InternalIntroSort.hpp.
References aitools::invertedindex::PostlistBuilder::append(), aitools::invertedindex::PostlistBuilder::build(), aitools::invertedindex::Configuration::DISABLED, aitools::invertedindex::Postlist< Value >::iterator(), aitools::invertedindex::Postlist< Value >::length(), aitools::invertedindex::Postlist< Value >::next(), and aitools::invertedindex::PostlistBuilder::set_checksum().
Referenced by aitools::invertedindex::PostlistSorter::sort().
The documentation for this class was generated from the following file:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/core/InternalIntroSort.hpp