aitools::invertedindex::Quadruple< T1, T2, T3, T4 > Class Template Reference
aitools::invertedindex::Quadruple< T1, T2, T3, T4 > Class Template Reference
#include <Quadruple.hpp>
Public Types
typedef T1 e1_type
typedef T2 e2_type
typedef T3 e3_type
typedef T4 e4_type
Public Member Functions
Quadruple ()
Quadruple (T1 e1, T2 e2, T3 e3, T4 e4)
Quadruple (const Quadruple< T1, T2, T3, T4 > &rhs)
virtual ~Quadruple ()
void clear ()
double score () const
bool operator== (const Quadruple< T1, T2, T3, T4 > &rhs) const
bool operator!= (const Quadruple< T1, T2, T3, T4 > &rhs) const
bool operator> (const Quadruple< T1, T2, T3, T4 > &rhs) const
bool operator< (const Quadruple< T1, T2, T3, T4 > &rhs) const
void parse (std::istream &is)
T1 & e1 ()
T2 & e2 ()
T3 & e3 ()
T4 & e4 ()
const T1 & e1 () const
const T2 & e2 () const
const T3 & e3 () const
const T4 & e4 () const
void print (std::ostream &os) const
void to_bytes (ByteBuffer &buffer) const
void wrap (const char *data, size_t size)
void wrap (const ByteBuffer &buffer)
Static Public Attributes
static const std::string classname
static const size_t sizeof_T1 = sizeof(T1)
static const size_t sizeof_T2 = sizeof(T2)
static const size_t sizeof_T3 = sizeof(T3)
static const size_t sizeof_T4 = sizeof(T4)
static const size_t offset_T2 = sizeof_T1
static const size_t offset_T3 = offset_T2 + sizeof_T2
static const size_t offset_T4 = offset_T3 + sizeof_T3
static const size_t sizeof_value
Private Attributes
T1 e1_
T2 e2_
T3 e3_
T4 e4_
Detailed Description
template<typename T1, typename T2, typename T3, typename T4>
class aitools::invertedindex::Quadruple< T1, T2, T3, T4 >
A class template of a concrete Value. This class interprets its ByteBuffer as four primitive values. Valid primitive types defined by the template parameters T1, T2 ,T3, T4 are [u]int[ 8 | 16 | 32 | 64 ]_t | float | double
Author:
martin.trenkmann@uni-weimar.de
Version:
Id
Quadruple.hpp,v 1.1 2011/01/26 22:20:09 trenkman Exp
Definition at line 25 of file Quadruple.hpp.
Member Typedef Documentation
template<typename T1, typename T2, typename T3, typename T4> typedef T1 aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e1_type
Definition at line 30 of file Quadruple.hpp.
template<typename T1, typename T2, typename T3, typename T4> typedef T2 aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e2_type
Definition at line 31 of file Quadruple.hpp.
template<typename T1, typename T2, typename T3, typename T4> typedef T3 aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e3_type
Definition at line 32 of file Quadruple.hpp.
template<typename T1, typename T2, typename T3, typename T4> typedef T4 aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e4_type
Definition at line 33 of file Quadruple.hpp.
Constructor & Destructor Documentation
template<typename T1 , typename T2 , typename T3 , typename T4 > aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::Quadruple () [inline]
The default constructor.
Definition at line 157 of file Quadruple.hpp.
template<typename T1 , typename T2 , typename T3 , typename T4 > aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::Quadruple (T1 e1, T2 e2, T3 e3, T4 e4) [inline]
The explicit constructor.
Definition at line 165 of file Quadruple.hpp.
template<typename T1 , typename T2 , typename T3 , typename T4 > aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::Quadruple (const Quadruple< T1, T2, T3, T4 > & rhs) [inline]
The copy constructor.
Definition at line 173 of file Quadruple.hpp.
template<typename T1 , typename T2 , typename T3 , typename T4 > aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::~Quadruple () [inline, virtual]
The destructor.
Definition at line 181 of file Quadruple.hpp.
Member Function Documentation
template<typename T1 , typename T2 , typename T3 , typename T4 > void aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::clear () [inline, virtual]
Resets all internals to default values.
Implements aitools::invertedindex::Value.
Definition at line 186 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e1_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e2_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e3_, and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e4_.
template<typename T1 , typename T2 , typename T3 , typename T4 > const T1 & aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e1 () const [inline]
Access the 1st element for reading.
Definition at line 280 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e1_.
template<typename T1 , typename T2 , typename T3 , typename T4 > T1 & aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e1 () [inline]
Access the 1st element for writing.
Definition at line 252 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e1_.
template<typename T1 , typename T2 , typename T3 , typename T4 > const T2 & aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e2 () const [inline]
Access the 2nd element for reading.
Definition at line 287 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e2_.
template<typename T1 , typename T2 , typename T3 , typename T4 > T2 & aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e2 () [inline]
Access the 2nd element for writing.
Definition at line 259 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e2_.
template<typename T1 , typename T2 , typename T3 , typename T4 > const T3 & aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e3 () const [inline]
Access the 3th element for reading.
Definition at line 294 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e3_.
template<typename T1 , typename T2 , typename T3 , typename T4 > T3 & aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e3 () [inline]
Access the 3th element for writing.
Definition at line 266 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e3_.
template<typename T1 , typename T2 , typename T3 , typename T4 > const T4 & aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e4 () const [inline]
Access the 4th element for reading.
Definition at line 301 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e4_.
template<typename T1 , typename T2 , typename T3 , typename T4 > T4 & aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e4 () [inline]
Access the 4th element for writing.
Definition at line 273 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e4_.
template<typename T1 , typename T2 , typename T3 , typename T4 > bool aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::operator!= (const Quadruple< T1, T2, T3, T4 > & rhs) const [inline]
Definition at line 211 of file Quadruple.hpp.
template<typename T1 , typename T2 , typename T3 , typename T4 > bool aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::operator< (const Quadruple< T1, T2, T3, T4 > & rhs) const [inline]
Definition at line 225 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::score().
template<typename T1 , typename T2 , typename T3 , typename T4 > bool aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::operator== (const Quadruple< T1, T2, T3, T4 > & rhs) const [inline]
Definition at line 203 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e1_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e2_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e3_, and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e4_.
template<typename T1 , typename T2 , typename T3 , typename T4 > bool aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::operator> (const Quadruple< T1, T2, T3, T4 > & rhs) const [inline]
Definition at line 218 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::score().
template<typename T1 , typename T2 , typename T3 , typename T4 > void aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::parse (std::istream & is) [inline, virtual]
Parses all elements from an input stream.
Implements aitools::invertedindex::Value.
Definition at line 232 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e1_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e2_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e3_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e4_, aitools::invertedindex::Value::sizeof_int8_t, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T1, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T2, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T3, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T4, and aitools::invertedindex::Value::tmp_int.
template<typename T1 , typename T2 , typename T3 , typename T4 > void aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::print (std::ostream & os) const [inline, virtual]
Prints all elements to an output stream.
Implements aitools::invertedindex::Value.
Definition at line 308 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e1_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e2_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e3_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e4_, aitools::invertedindex::Value::sizeof_int8_t, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T1, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T2, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T3, and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T4.
template<typename T1 , typename T2 , typename T3 , typename T4 > double aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::score () const [inline, virtual]
Gets the weight of this object.
Implements aitools::invertedindex::Value.
Definition at line 196 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e1_.
Referenced by aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::operator<(), and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::operator>().
template<typename T1 , typename T2 , typename T3 , typename T4 > void aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::to_bytes (ByteBuffer & buffer) const [inline, virtual]
Serializes all elements into a byte buffer.
Implements aitools::invertedindex::Value.
Definition at line 331 of file Quadruple.hpp.
References aitools::invertedindex::ByteBuffer::data(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e1_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e2_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e3_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e4_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::offset_T2, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::offset_T3, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::offset_T4, aitools::invertedindex::ByteBuffer::resize(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T1, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T2, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T3, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T4, and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_value.
template<typename T1 , typename T2 , typename T3 , typename T4 > void aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::wrap (const ByteBuffer & buffer) [inline]
Interprets a byte buffer.
Reimplemented from aitools::invertedindex::Value.
Definition at line 354 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::wrap().
template<typename T1 , typename T2 , typename T3 , typename T4 > void aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::wrap (const char * data, size_t size) [inline, virtual]
Interprets a byte buffer.
Implements aitools::invertedindex::Value.
Definition at line 342 of file Quadruple.hpp.
References aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e1_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e2_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e3_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e4_, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::offset_T2, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::offset_T3, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::offset_T4, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T1, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T2, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T3, aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T4, and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_value.
Referenced by aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::wrap().
Member Data Documentation
template<typename T1, typename T2, typename T3, typename T4> const std::string aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::classname [inline, static]
Definition at line 37 of file Quadruple.hpp.
template<typename T1, typename T2, typename T3, typename T4> T1 aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e1_ [private]
Definition at line 139 of file Quadruple.hpp.
Referenced by aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::clear(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e1(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::operator==(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::parse(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::print(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::score(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::to_bytes(), and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::wrap().
template<typename T1, typename T2, typename T3, typename T4> T2 aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e2_ [private]
Definition at line 140 of file Quadruple.hpp.
Referenced by aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::clear(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e2(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::operator==(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::parse(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::print(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::to_bytes(), and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::wrap().
template<typename T1, typename T2, typename T3, typename T4> T3 aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e3_ [private]
Definition at line 141 of file Quadruple.hpp.
Referenced by aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::clear(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e3(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::operator==(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::parse(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::print(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::to_bytes(), and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::wrap().
template<typename T1, typename T2, typename T3, typename T4> T4 aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e4_ [private]
Definition at line 142 of file Quadruple.hpp.
Referenced by aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::clear(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::e4(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::operator==(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::parse(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::print(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::to_bytes(), and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::wrap().
template<typename T1, typename T2, typename T3, typename T4> const size_t aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::offset_T2 = sizeof_T1 [static]
Definition at line 44 of file Quadruple.hpp.
Referenced by aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::to_bytes(), and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::wrap().
template<typename T1, typename T2, typename T3, typename T4> const size_t aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::offset_T3 = offset_T2 + sizeof_T2 [static]
Definition at line 45 of file Quadruple.hpp.
Referenced by aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::to_bytes(), and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::wrap().
template<typename T1, typename T2, typename T3, typename T4> const size_t aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::offset_T4 = offset_T3 + sizeof_T3 [static]
Definition at line 46 of file Quadruple.hpp.
Referenced by aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::to_bytes(), and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::wrap().
template<typename T1, typename T2, typename T3, typename T4> const size_t aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T1 = sizeof(T1) [static]
Definition at line 39 of file Quadruple.hpp.
Referenced by aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::parse(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::print(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::to_bytes(), and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::wrap().
template<typename T1, typename T2, typename T3, typename T4> const size_t aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T2 = sizeof(T2) [static]
Definition at line 40 of file Quadruple.hpp.
Referenced by aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::parse(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::print(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::to_bytes(), and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::wrap().
template<typename T1, typename T2, typename T3, typename T4> const size_t aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T3 = sizeof(T3) [static]
Definition at line 41 of file Quadruple.hpp.
Referenced by aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::parse(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::print(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::to_bytes(), and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::wrap().
template<typename T1, typename T2, typename T3, typename T4> const size_t aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_T4 = sizeof(T4) [static]
Definition at line 42 of file Quadruple.hpp.
Referenced by aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::parse(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::print(), aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::to_bytes(), and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::wrap().
template<typename T1, typename T2, typename T3, typename T4> const size_t aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::sizeof_value [static]
Initial value:
                        sizeof_T1 + sizeof_T2 + sizeof_T3 + sizeof_T4
Definition at line 48 of file Quadruple.hpp.
Referenced by aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::to_bytes(), and aitools::invertedindex::Quadruple< T1, T2, T3, T4 >::wrap().
The documentation for this class was generated from the following file:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/value/Quadruple.hpp