aitools::invertedindex::SingleString Class Reference
aitools::invertedindex::SingleString Class Reference
#include <SingleString.hpp>
Public Member Functions
SingleString ()
SingleString (const std::string &element)
SingleString (const SingleString &single)
virtual ~SingleString ()
void clear ()
bool operator== (const SingleString &single) const
bool operator!= (const SingleString &single) const
bool operator> (const SingleString &single) const
bool operator< (const SingleString &single) const
void parse (std::istream &is)
void print (std::ostream &os) const
double score () const
std::string & element ()
const std::string & element () const
void to_bytes (ByteBuffer &buffer) const
void wrap (const char *data, size_t size)
void wrap (const ByteBuffer &buffer)
Static Public Attributes
static const std::string classname
Private Attributes
std::string element_
Detailed Description
A concrete class of Value. This class interprets its ByteBuffer as a single string.
Author:
martin.trenkmann@uni-weimar.de
Version:
Id
SingleString.hpp,v 1.2 2010/10/15 17:44:47 trenkman Exp
Definition at line 20 of file SingleString.hpp.
Constructor & Destructor Documentation
aitools::invertedindex::SingleString::SingleString ()
The default constructor.
Definition at line 7 of file SingleString.cpp.
aitools::invertedindex::SingleString::SingleString (const std::string & element)
The explicit constructor.
Definition at line 10 of file SingleString.cpp.
aitools::invertedindex::SingleString::SingleString (const SingleString & single)
The copy constructor.
Definition at line 14 of file SingleString.cpp.
aitools::invertedindex::SingleString::~SingleString () [virtual]
The destructor.
Definition at line 18 of file SingleString.cpp.
Member Function Documentation
void aitools::invertedindex::SingleString::clear () [virtual]
Resets all internals to default values.
Implements aitools::invertedindex::Value.
Definition at line 22 of file SingleString.cpp.
const std::string & aitools::invertedindex::SingleString::element () const
Definition at line 76 of file SingleString.cpp.
References element_.
std::string & aitools::invertedindex::SingleString::element ()
Definition at line 70 of file SingleString.cpp.
References element_.
bool aitools::invertedindex::SingleString::operator!= (const SingleString & single) const
Definition at line 34 of file SingleString.cpp.
References element_.
bool aitools::invertedindex::SingleString::operator< (const SingleString & single) const
Definition at line 46 of file SingleString.cpp.
References score().
bool aitools::invertedindex::SingleString::operator== (const SingleString & single) const
Definition at line 28 of file SingleString.cpp.
References element_.
bool aitools::invertedindex::SingleString::operator> (const SingleString & single) const
Definition at line 40 of file SingleString.cpp.
void aitools::invertedindex::SingleString::parse (std::istream & is) [virtual]
Parses all elements from an input stream.
Implements aitools::invertedindex::Value.
Definition at line 52 of file SingleString.cpp.
References score().
void aitools::invertedindex::SingleString::print (std::ostream & os) const [virtual]
Prints all elements to an output stream.
Implements aitools::invertedindex::Value.
Definition at line 58 of file SingleString.cpp.
References element_.
double aitools::invertedindex::SingleString::score () const [virtual]
Gets the weight of this object.
Implements aitools::invertedindex::Value.
Definition at line 64 of file SingleString.cpp.
References element_.
Referenced by operator<(), and parse().
void aitools::invertedindex::SingleString::to_bytes (ByteBuffer & buffer) const [virtual]
Serializes all elements into a byte buffer.
Implements aitools::invertedindex::Value.
Definition at line 82 of file SingleString.cpp.
References element_.
void aitools::invertedindex::SingleString::wrap (const ByteBuffer & buffer)
Interprets a byte buffer.
Reimplemented from aitools::invertedindex::Value.
Definition at line 97 of file SingleString.cpp.
void aitools::invertedindex::SingleString::wrap (const char * data, size_t size) [virtual]
Interprets a byte buffer.
Implements aitools::invertedindex::Value.
Definition at line 89 of file SingleString.cpp.
Member Data Documentation
const std::string aitools::invertedindex::SingleString::classname [static]
Definition at line 24 of file SingleString.hpp.
std::string aitools::invertedindex::SingleString::element_ [private]
Definition at line 78 of file SingleString.hpp.
Referenced by element(), operator!=(), operator==(), print(), score(), and to_bytes().
The documentation for this class was generated from the following files:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/value/SingleString.hpp
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/value/SingleString.cpp