de::aitools::aq::invertedindex::usage::UsingIndexer Class Reference
de::aitools::aq::invertedindex::usage::UsingIndexer Class Reference
Static Public Member Functions
static void main (String[] args)
Detailed Description
A helper class to demonstrate the usage of Indexer.
Author:
martin.trenkmann@uni-weimar.de
Version:
Id
UsingIndexer.java,v 1.4 2011/04/06 16:12:09 trenkman Exp
See also:
Indexer
Definition at line 23 of file UsingIndexer.java.
Member Function Documentation
static void de::aitools::aq::invertedindex::usage::UsingIndexer::main (String[] args) [inline, static]
Definition at line 25 of file UsingIndexer.java.
References de::aitools::aq::invertedindex::core::Properties::printTo(), de::aitools::aq::invertedindex::core::Configuration::setExpectedNumberOfRecords(), de::aitools::aq::invertedindex::core::Configuration::setIndexDirectory(), de::aitools::aq::invertedindex::core::Configuration::setKeySorting(), de::aitools::aq::invertedindex::core::Configuration::setMaxMemoryUsage(), and de::aitools::aq::invertedindex::core::Configuration::setValueSorting().
The documentation for this class was generated from the following file:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex2-java/src/de/aitools/aq/invertedindex/usage/UsingIndexer.java