aitools::invertedindex::NGramFileReader Class Reference
aitools::invertedindex::NGramFileReader Class Reference
#include <NGramFileReader.hpp>
Public Member Functions
NGramFileReader ()
~NGramFileReader ()
void close ()
bool next (Record< value_type > &record)
void open (const bfs::path &path)
Private Attributes
bfs::ifstream ifs_
std::istringstream iss_
std::string::size_type tabpos_
std::string line_
value_type value_
Detailed Description
Definition at line 18 of file NGramFileReader.hpp.
Constructor & Destructor Documentation
aitools::invertedindex::NGramFileReader::NGramFileReader () [inline]
The default constructor.
Definition at line 25 of file NGramFileReader.hpp.
aitools::invertedindex::NGramFileReader::~NGramFileReader () [inline]
The destructor.
Definition at line 30 of file NGramFileReader.hpp.
Member Function Documentation
void aitools::invertedindex::NGramFileReader::close () [inline, virtual]
Closes the file currently associated with the object.
Implements aitools::invertedindex::RecordReader< value_type >.
Definition at line 37 of file NGramFileReader.hpp.
References ifs_, and iss_.
bool aitools::invertedindex::NGramFileReader::next (Record< value_type > & record) [inline, virtual]
Extracts the next record by resetting the content of the given record.
Parameters:
record A record to fill with new content.
Returns:
true if a new record could be extracted successfully, and false otherwise, which signals the end of the stream.
Implements aitools::invertedindex::RecordReader< value_type >.
Definition at line 50 of file NGramFileReader.hpp.
References aitools::invertedindex::Triple< T1, T2, T3 >::e1(), aitools::invertedindex::Triple< T1, T2, T3 >::e2(), aitools::invertedindex::Triple< T1, T2, T3 >::e3(), ifs_, iss_, aitools::invertedindex::Record< Value >::key(), line_, tabpos_, aitools::invertedindex::Record< Value >::value(), and value_.
void aitools::invertedindex::NGramFileReader::open (const bfs::path & path) [inline, virtual]
Opens a file and initializes the reader to extract records. Invoking this method on an already opened file is illegal.
Parameters:
path The path of the file to be opened.
Implements aitools::invertedindex::RecordReader< value_type >.
Definition at line 85 of file NGramFileReader.hpp.
References ifs_.
Member Data Documentation
bfs::ifstream aitools::invertedindex::NGramFileReader::ifs_ [private]
Definition at line 92 of file NGramFileReader.hpp.
Referenced by close(), next(), and open().
std::istringstream aitools::invertedindex::NGramFileReader::iss_ [private]
Definition at line 93 of file NGramFileReader.hpp.
Referenced by close(), and next().
std::string aitools::invertedindex::NGramFileReader::line_ [private]
Definition at line 95 of file NGramFileReader.hpp.
Referenced by next().
std::string::size_type aitools::invertedindex::NGramFileReader::tabpos_ [private]
Definition at line 94 of file NGramFileReader.hpp.
Referenced by next().
value_type aitools::invertedindex::NGramFileReader::value_ [private]
Definition at line 96 of file NGramFileReader.hpp.
Referenced by next().
The documentation for this class was generated from the following file:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/reader/NGramFileReader.hpp