aitools::invertedindex::Configuration Class Reference
aitools::invertedindex::Configuration Class Reference
#include <IndexMessages.pb.h>
Public Types
typedef Configuration_InputFormat InputFormat
typedef Configuration_Sorting Sorting
Public Member Functions
Configuration ()
virtual ~Configuration ()
Configuration (const Configuration &from)
Configuration & operator= (const Configuration &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Configuration *other)
Configuration * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const Configuration &from)
void MergeFrom (const Configuration &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_input_directory () const
void clear_input_directory ()
const ::std::string & input_directory () const
void set_input_directory (const ::std::string &value)
void set_input_directory (const char *value)
void set_input_directory (const char *value, size_t size)
inline::std::string * mutable_input_directory ()
bool has_index_directory () const
void clear_index_directory ()
const ::std::string & index_directory () const
void set_index_directory (const ::std::string &value)
void set_index_directory (const char *value)
void set_index_directory (const char *value, size_t size)
inline::std::string * mutable_index_directory ()
bool has_available_memory () const
void clear_available_memory ()
inline::google::protobuf::uint32 available_memory () const
void set_available_memory (::google::protobuf::uint32 value)
bool has_postlist_sorting () const
void clear_postlist_sorting ()
inline::aitools::invertedindex::Configuration_Sorting postlist_sorting () const
void set_postlist_sorting (::aitools::invertedindex::Configuration_Sorting value)
bool has_input_format () const
void clear_input_format ()
inline::aitools::invertedindex::Configuration_InputFormat input_format () const
void set_input_format (::aitools::invertedindex::Configuration_InputFormat value)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const Configuration & default_instance ()
static bool InputFormat_IsValid (int value)
static const
::google::protobuf::EnumDescriptor * InputFormat_descriptor ()
static const ::std::string & InputFormat_Name (InputFormat value)
static bool InputFormat_Parse (const ::std::string &name, InputFormat *value)
static bool Sorting_IsValid (int value)
static const
::google::protobuf::EnumDescriptor * Sorting_descriptor ()
static const ::std::string & Sorting_Name (Sorting value)
static bool Sorting_Parse (const ::std::string &name, Sorting *value)
Static Public Attributes
static const InputFormat REAL_INVERTED = Configuration_InputFormat_REAL_INVERTED
static const InputFormat PSEUDO_INVERTED = Configuration_InputFormat_PSEUDO_INVERTED
static const InputFormat InputFormat_MIN
static const InputFormat InputFormat_MAX
static const Sorting DISABLED = Configuration_Sorting_DISABLED
static const Sorting ASCENDING = Configuration_Sorting_ASCENDING
static const Sorting DESCENDING = Configuration_Sorting_DESCENDING
static const Sorting Sorting_MIN
static const Sorting Sorting_MAX
static const int kInputDirectoryFieldNumber = 1
static const int kIndexDirectoryFieldNumber = 2
static const int kAvailableMemoryFieldNumber = 3
static const int kPostlistSortingFieldNumber = 4
static const int kInputFormatFieldNumber = 5
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
bool _has_bit (int index) const
void _set_bit (int index)
void _clear_bit (int index)
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
int _cached_size_
::std::string * input_directory_
::std::string * index_directory_
::google::protobuf::uint32 available_memory_
int postlist_sorting_
int input_format_
::google::protobuf::uint32 _has_bits_ [(5+31)/32]
Static Private Attributes
static const ::std::string _default_input_directory_
static const ::std::string _default_index_directory_
static Configuration * default_instance_ = NULL
Friends
void protobuf_AddDesc_IndexMessages_2eproto ()
void protobuf_AssignDesc_IndexMessages_2eproto ()
void protobuf_ShutdownFile_IndexMessages_2eproto ()
Detailed Description
Definition at line 76 of file IndexMessages.pb.h.
Member Typedef Documentation
typedef Configuration_InputFormat aitools::invertedindex::Configuration::InputFormat
Definition at line 127 of file IndexMessages.pb.h.
typedef Configuration_Sorting aitools::invertedindex::Configuration::Sorting
Definition at line 149 of file IndexMessages.pb.h.
Constructor & Destructor Documentation
aitools::invertedindex::Configuration::Configuration ()
Definition at line 193 of file IndexMessages.pb.cc.
aitools::invertedindex::Configuration::~Configuration () [virtual]
Definition at line 215 of file IndexMessages.pb.cc.
aitools::invertedindex::Configuration::Configuration (const Configuration & from)
Definition at line 200 of file IndexMessages.pb.cc.
References SharedCtor().
Member Function Documentation
void aitools::invertedindex::Configuration::_clear_bit (int index) [inline, private]
Definition at line 239 of file IndexMessages.pb.h.
References _has_bits_.
Referenced by clear_available_memory(), clear_index_directory(), clear_input_directory(), clear_input_format(), and clear_postlist_sorting().
bool aitools::invertedindex::Configuration::_has_bit (int index) const [inline, private]
Definition at line 233 of file IndexMessages.pb.h.
References _has_bits_.
Referenced by has_available_memory(), has_index_directory(), has_input_directory(), has_input_format(), and has_postlist_sorting().
void aitools::invertedindex::Configuration::_set_bit (int index) [inline, private]
Definition at line 236 of file IndexMessages.pb.h.
References _has_bits_.
Referenced by mutable_index_directory(), mutable_input_directory(), set_available_memory(), set_index_directory(), set_input_directory(), set_input_format(), and set_postlist_sorting().
google::protobuf::uint32 aitools::invertedindex::Configuration::available_memory () const [inline]
Definition at line 495 of file IndexMessages.pb.h.
References available_memory_.
int aitools::invertedindex::Configuration::ByteSize () const
Definition at line 463 of file IndexMessages.pb.cc.
References unknown_fields().
void aitools::invertedindex::Configuration::Clear ()
Definition at line 245 of file IndexMessages.pb.cc.
void aitools::invertedindex::Configuration::clear_available_memory () [inline]
Definition at line 491 of file IndexMessages.pb.h.
References _clear_bit(), and available_memory_.
void aitools::invertedindex::Configuration::clear_index_directory () [inline]
Definition at line 449 of file IndexMessages.pb.h.
References _clear_bit(), _default_index_directory_, and index_directory_.
void aitools::invertedindex::Configuration::clear_input_directory () [inline]
Definition at line 407 of file IndexMessages.pb.h.
References _clear_bit(), _default_input_directory_, and input_directory_.
void aitools::invertedindex::Configuration::clear_input_format () [inline]
Definition at line 524 of file IndexMessages.pb.h.
References _clear_bit(), and input_format_.
void aitools::invertedindex::Configuration::clear_postlist_sorting () [inline]
Definition at line 507 of file IndexMessages.pb.h.
References _clear_bit(), and postlist_sorting_.
void aitools::invertedindex::Configuration::CopyFrom (const Configuration & from)
Definition at line 550 of file IndexMessages.pb.cc.
void aitools::invertedindex::Configuration::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 544 of file IndexMessages.pb.cc.
Referenced by operator=().
const Configuration & aitools::invertedindex::Configuration::default_instance () [static]
Definition at line 235 of file IndexMessages.pb.cc.
const ::google::protobuf::Descriptor * aitools::invertedindex::Configuration::descriptor () [static]
Definition at line 230 of file IndexMessages.pb.cc.
int aitools::invertedindex::Configuration::GetCachedSize () const [inline]
Definition at line 116 of file IndexMessages.pb.h.
References _cached_size_.
google::protobuf::Metadata aitools::invertedindex::Configuration::GetMetadata () const
Definition at line 574 of file IndexMessages.pb.cc.
bool aitools::invertedindex::Configuration::has_available_memory () const [inline]
Definition at line 488 of file IndexMessages.pb.h.
References _has_bit().
bool aitools::invertedindex::Configuration::has_index_directory () const [inline]
Definition at line 446 of file IndexMessages.pb.h.
References _has_bit().
bool aitools::invertedindex::Configuration::has_input_directory () const [inline]
Definition at line 404 of file IndexMessages.pb.h.
References _has_bit().
bool aitools::invertedindex::Configuration::has_input_format () const [inline]
Definition at line 521 of file IndexMessages.pb.h.
References _has_bit().
bool aitools::invertedindex::Configuration::has_postlist_sorting () const [inline]
Definition at line 504 of file IndexMessages.pb.h.
References _has_bit().
const ::std::string & aitools::invertedindex::Configuration::index_directory () const [inline]
Definition at line 455 of file IndexMessages.pb.h.
References index_directory_.
void aitools::invertedindex::Configuration::InitAsDefaultInstance () [private]
Definition at line 197 of file IndexMessages.pb.cc.
const ::std::string & aitools::invertedindex::Configuration::input_directory () const [inline]
Definition at line 413 of file IndexMessages.pb.h.
References input_directory_.
aitools::invertedindex::Configuration_InputFormat aitools::invertedindex::Configuration::input_format () const [inline]
Definition at line 528 of file IndexMessages.pb.h.
References input_format_.
static const ::google::protobuf::EnumDescriptor* aitools::invertedindex::Configuration::InputFormat_descriptor () [inline, static]
Definition at line 138 of file IndexMessages.pb.h.
References aitools::invertedindex::Configuration_InputFormat_descriptor().
static bool aitools::invertedindex::Configuration::InputFormat_IsValid (int value) [inline, static]
Definition at line 130 of file IndexMessages.pb.h.
References aitools::invertedindex::Configuration_InputFormat_IsValid().
static const ::std::string& aitools::invertedindex::Configuration::InputFormat_Name (InputFormat value) [inline, static]
Definition at line 141 of file IndexMessages.pb.h.
References aitools::invertedindex::Configuration_InputFormat_Name().
static bool aitools::invertedindex::Configuration::InputFormat_Parse (const ::std::string & name, InputFormat * value) [inline, static]
Definition at line 144 of file IndexMessages.pb.h.
References aitools::invertedindex::Configuration_InputFormat_Parse().
bool aitools::invertedindex::Configuration::IsInitialized () const
Definition at line 556 of file IndexMessages.pb.cc.
void aitools::invertedindex::Configuration::MergeFrom (const Configuration & from)
Definition at line 522 of file IndexMessages.pb.cc.
void aitools::invertedindex::Configuration::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 510 of file IndexMessages.pb.cc.
bool aitools::invertedindex::Configuration::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 265 of file IndexMessages.pb.cc.
std::string * aitools::invertedindex::Configuration::mutable_index_directory () [inline]
Definition at line 479 of file IndexMessages.pb.h.
References _default_index_directory_, _set_bit(), and index_directory_.
std::string * aitools::invertedindex::Configuration::mutable_input_directory () [inline]
Definition at line 437 of file IndexMessages.pb.h.
References _default_input_directory_, _set_bit(), and input_directory_.
inline ::google::protobuf::UnknownFieldSet* aitools::invertedindex::Configuration::mutable_unknown_fields () [inline]
Definition at line 92 of file IndexMessages.pb.h.
References _unknown_fields_.
Configuration * aitools::invertedindex::Configuration::New () const
Definition at line 241 of file IndexMessages.pb.cc.
Configuration& aitools::invertedindex::Configuration::operator= (const Configuration & from) [inline]
Definition at line 83 of file IndexMessages.pb.h.
References CopyFrom().
aitools::invertedindex::Configuration_Sorting aitools::invertedindex::Configuration::postlist_sorting () const [inline]
Definition at line 511 of file IndexMessages.pb.h.
References postlist_sorting_.
void aitools::invertedindex::Configuration::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 368 of file IndexMessages.pb.cc.
google::protobuf::uint8 * aitools::invertedindex::Configuration::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 417 of file IndexMessages.pb.cc.
void aitools::invertedindex::Configuration::set_available_memory (::google::protobuf::uint32 value) [inline]
Definition at line 498 of file IndexMessages.pb.h.
References _set_bit(), and available_memory_.
Referenced by aitools::invertedindex::build_ngram_index().
void aitools::invertedindex::Configuration::set_index_directory (const char * value, size_t size) [inline]
Definition at line 472 of file IndexMessages.pb.h.
References _default_index_directory_, _set_bit(), and index_directory_.
void aitools::invertedindex::Configuration::set_index_directory (const char * value) [inline]
Definition at line 465 of file IndexMessages.pb.h.
References _default_index_directory_, _set_bit(), and index_directory_.
void aitools::invertedindex::Configuration::set_index_directory (const ::std::string & value) [inline]
Definition at line 458 of file IndexMessages.pb.h.
References _default_index_directory_, _set_bit(), and index_directory_.
Referenced by aitools::invertedindex::build_ngram_index().
void aitools::invertedindex::Configuration::set_input_directory (const char * value, size_t size) [inline]
Definition at line 430 of file IndexMessages.pb.h.
References _default_input_directory_, _set_bit(), and input_directory_.
void aitools::invertedindex::Configuration::set_input_directory (const char * value) [inline]
Definition at line 423 of file IndexMessages.pb.h.
References _default_input_directory_, _set_bit(), and input_directory_.
void aitools::invertedindex::Configuration::set_input_directory (const ::std::string & value) [inline]
Definition at line 416 of file IndexMessages.pb.h.
References _default_input_directory_, _set_bit(), and input_directory_.
Referenced by aitools::invertedindex::build_ngram_index().
void aitools::invertedindex::Configuration::set_input_format (::aitools::invertedindex::Configuration_InputFormat value) [inline]
Definition at line 531 of file IndexMessages.pb.h.
References _set_bit(), aitools::invertedindex::Configuration_InputFormat_IsValid(), and input_format_.
Referenced by aitools::invertedindex::build_ngram_index().
void aitools::invertedindex::Configuration::set_postlist_sorting (::aitools::invertedindex::Configuration_Sorting value) [inline]
Definition at line 514 of file IndexMessages.pb.h.
References _set_bit(), aitools::invertedindex::Configuration_Sorting_IsValid(), and postlist_sorting_.
Referenced by aitools::invertedindex::build_ngram_index().
void aitools::invertedindex::Configuration::SetCachedSize (int size) const [inline, private]
Definition at line 120 of file IndexMessages.pb.h.
References _cached_size_.
void aitools::invertedindex::Configuration::SharedCtor () [private]
Definition at line 205 of file IndexMessages.pb.cc.
Referenced by Configuration().
void aitools::invertedindex::Configuration::SharedDtor () [private]
Definition at line 219 of file IndexMessages.pb.cc.
static const ::google::protobuf::EnumDescriptor* aitools::invertedindex::Configuration::Sorting_descriptor () [inline, static]
Definition at line 161 of file IndexMessages.pb.h.
References aitools::invertedindex::Configuration_Sorting_descriptor().
static bool aitools::invertedindex::Configuration::Sorting_IsValid (int value) [inline, static]
Definition at line 153 of file IndexMessages.pb.h.
References aitools::invertedindex::Configuration_Sorting_IsValid().
static const ::std::string& aitools::invertedindex::Configuration::Sorting_Name (Sorting value) [inline, static]
Definition at line 164 of file IndexMessages.pb.h.
References aitools::invertedindex::Configuration_Sorting_Name().
static bool aitools::invertedindex::Configuration::Sorting_Parse (const ::std::string & name, Sorting * value) [inline, static]
Definition at line 167 of file IndexMessages.pb.h.
References aitools::invertedindex::Configuration_Sorting_Parse().
void aitools::invertedindex::Configuration::Swap (Configuration * other)
Definition at line 561 of file IndexMessages.pb.cc.
const ::google::protobuf::UnknownFieldSet& aitools::invertedindex::Configuration::unknown_fields () const [inline]
Definition at line 88 of file IndexMessages.pb.h.
References _unknown_fields_.
Referenced by ByteSize().
Friends And Related Function Documentation
void protobuf_AddDesc_IndexMessages_2eproto () [friend]
void protobuf_AssignDesc_IndexMessages_2eproto () [friend]
void protobuf_ShutdownFile_IndexMessages_2eproto () [friend]
Member Data Documentation
int aitools::invertedindex::Configuration::_cached_size_ [mutable, private]
Definition at line 217 of file IndexMessages.pb.h.
Referenced by GetCachedSize(), and SetCachedSize().
const ::std::string aitools::invertedindex::Configuration::_default_index_directory_ [static, private]
Definition at line 222 of file IndexMessages.pb.h.
Referenced by clear_index_directory(), mutable_index_directory(), and set_index_directory().
const ::std::string aitools::invertedindex::Configuration::_default_input_directory_ [static, private]
Definition at line 220 of file IndexMessages.pb.h.
Referenced by clear_input_directory(), mutable_input_directory(), and set_input_directory().
::google::protobuf::uint32 aitools::invertedindex::Configuration::_has_bits_[(5+31)/32] [private]
Definition at line 230 of file IndexMessages.pb.h.
Referenced by _clear_bit(), _has_bit(), and _set_bit().
::google::protobuf::UnknownFieldSet aitools::invertedindex::Configuration::_unknown_fields_ [private]
Definition at line 216 of file IndexMessages.pb.h.
Referenced by mutable_unknown_fields(), and unknown_fields().
const Configuration_Sorting aitools::invertedindex::Configuration::ASCENDING = Configuration_Sorting_ASCENDING [static]
Definition at line 151 of file IndexMessages.pb.h.
Referenced by aitools::invertedindex::ExternalMergeSort::merge(), and aitools::invertedindex::InternalIntroSort::sort().
::google::protobuf::uint32 aitools::invertedindex::Configuration::available_memory_ [private]
Definition at line 223 of file IndexMessages.pb.h.
Referenced by available_memory(), clear_available_memory(), and set_available_memory().
Configuration * aitools::invertedindex::Configuration::default_instance_ = NULL [static, private]
Definition at line 244 of file IndexMessages.pb.h.
const Configuration_Sorting aitools::invertedindex::Configuration::DESCENDING = Configuration_Sorting_DESCENDING [static]
Definition at line 152 of file IndexMessages.pb.h.
Referenced by aitools::invertedindex::build_ngram_index(), and aitools::invertedindex::InternalIntroSort::sort().
const Configuration_Sorting aitools::invertedindex::Configuration::DISABLED = Configuration_Sorting_DISABLED [static]
Definition at line 150 of file IndexMessages.pb.h.
Referenced by aitools::invertedindex::build_ngram_index(), aitools::invertedindex::InternalIntroSort::sort(), and aitools::invertedindex::ExternalMergeSort::sort().
::std::string* aitools::invertedindex::Configuration::index_directory_ [private]
Definition at line 221 of file IndexMessages.pb.h.
Referenced by clear_index_directory(), index_directory(), mutable_index_directory(), and set_index_directory().
::std::string* aitools::invertedindex::Configuration::input_directory_ [private]
Definition at line 219 of file IndexMessages.pb.h.
Referenced by clear_input_directory(), input_directory(), mutable_input_directory(), and set_input_directory().
int aitools::invertedindex::Configuration::input_format_ [private]
Definition at line 225 of file IndexMessages.pb.h.
Referenced by clear_input_format(), input_format(), and set_input_format().
const Configuration_InputFormat aitools::invertedindex::Configuration::InputFormat_MAX [static]
Initial value:
    Configuration_InputFormat_InputFormat_MAX
Definition at line 135 of file IndexMessages.pb.h.
const Configuration_InputFormat aitools::invertedindex::Configuration::InputFormat_MIN [static]
Initial value:
    Configuration_InputFormat_InputFormat_MIN
Definition at line 133 of file IndexMessages.pb.h.
const int aitools::invertedindex::Configuration::kAvailableMemoryFieldNumber = 3 [static]
Definition at line 197 of file IndexMessages.pb.h.
const int aitools::invertedindex::Configuration::kIndexDirectoryFieldNumber = 2 [static]
Definition at line 187 of file IndexMessages.pb.h.
const int aitools::invertedindex::Configuration::kInputDirectoryFieldNumber = 1 [static]
Definition at line 177 of file IndexMessages.pb.h.
const int aitools::invertedindex::Configuration::kInputFormatFieldNumber = 5 [static]
Definition at line 211 of file IndexMessages.pb.h.
const int aitools::invertedindex::Configuration::kPostlistSortingFieldNumber = 4 [static]
Definition at line 204 of file IndexMessages.pb.h.
int aitools::invertedindex::Configuration::postlist_sorting_ [private]
Definition at line 224 of file IndexMessages.pb.h.
Referenced by clear_postlist_sorting(), postlist_sorting(), and set_postlist_sorting().
const Configuration_InputFormat aitools::invertedindex::Configuration::PSEUDO_INVERTED = Configuration_InputFormat_PSEUDO_INVERTED [static]
Definition at line 129 of file IndexMessages.pb.h.
Referenced by aitools::invertedindex::build_ngram_index().
const Configuration_InputFormat aitools::invertedindex::Configuration::REAL_INVERTED = Configuration_InputFormat_REAL_INVERTED [static]
Definition at line 128 of file IndexMessages.pb.h.
Referenced by aitools::invertedindex::build_ngram_index().
const Configuration_Sorting aitools::invertedindex::Configuration::Sorting_MAX [static]
Initial value:
    Configuration_Sorting_Sorting_MAX
Definition at line 158 of file IndexMessages.pb.h.
const Configuration_Sorting aitools::invertedindex::Configuration::Sorting_MIN [static]
Initial value:
    Configuration_Sorting_Sorting_MIN
Definition at line 156 of file IndexMessages.pb.h.
The documentation for this class was generated from the following files:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/generated/IndexMessages.pb.h
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/generated/IndexMessages.pb.cc