aitools::bighashmap::core::big_hash_map< T > Class Template Reference
aitools::bighashmap::core::big_hash_map< T > Class Template Reference
#include <big_hash_map.hpp>
Public Types
typedef cmph_map< T > map_type
typedef map_type::key_type key_type
typedef map_type::value_type value_type
typedef map_type::checksum_type checksum_type
Public Member Functions
~big_hash_map ()
bool find (const key_type &key, value_type &value)
bool find (const std::string &key, char *value_buffer)
uint64_t size () const
Static Public Member Functions
static const bfs::path build (const bfs::path &input_dir, const bfs::path &output_dir, algorithm algo=algorithm::bdz)
static big_hash_map * open (const bfs::path &idx_file, util::memory_type mem)
Static Public Attributes
static const std::string index_file_name
Private Member Functions
big_hash_map ()
big_hash_map (const std::vector< map_type * > &sub_maps)
Static Private Member Functions
static uint64_t table_size (const bfs::path &dir)
Private Attributes
std::vector< map_type * > maps_
uint64_t size_
Detailed Description
template<typename T>
class aitools::bighashmap::core::big_hash_map< T >
See external_map for any comments.
Author:
martin.trenkmann@uni-weimar.de
Version:
Id
big_hash_map.hpp,v 1.2 2011/09/21 01:00:50 trenkman Exp
Definition at line 25 of file big_hash_map.hpp.
Member Typedef Documentation
template<typename T> typedef map_type::checksum_type aitools::bighashmap::core::big_hash_map< T >::checksum_type
Definition at line 32 of file big_hash_map.hpp.
template<typename T> typedef map_type::key_type aitools::bighashmap::core::big_hash_map< T >::key_type
Definition at line 30 of file big_hash_map.hpp.
template<typename T> typedef cmph_map<T> aitools::bighashmap::core::big_hash_map< T >::map_type
Definition at line 29 of file big_hash_map.hpp.
template<typename T> typedef map_type::value_type aitools::bighashmap::core::big_hash_map< T >::value_type
Definition at line 31 of file big_hash_map.hpp.
Constructor & Destructor Documentation
template<typename T> aitools::bighashmap::core::big_hash_map< T >::big_hash_map () [inline, private]
Definition at line 40 of file big_hash_map.hpp.
Referenced by aitools::bighashmap::core::big_hash_map< T >::open().
template<typename T> aitools::bighashmap::core::big_hash_map< T >::big_hash_map (const std::vector< map_type * > & sub_maps) [inline, private]
Definition at line 43 of file big_hash_map.hpp.
References aitools::bighashmap::core::big_hash_map< T >::maps_, and aitools::bighashmap::core::big_hash_map< T >::size_.
template<typename T> aitools::bighashmap::core::big_hash_map< T >::~big_hash_map () [inline]
Definition at line 76 of file big_hash_map.hpp.
References aitools::bighashmap::core::big_hash_map< T >::maps_.
Member Function Documentation
template<typename T> static const bfs::path aitools::bighashmap::core::big_hash_map< T >::build (const bfs::path & input_dir, const bfs::path & output_dir, algorithm algo = algorithm::bdz) [inline, static]
Definition at line 87 of file big_hash_map.hpp.
template<typename T> bool aitools::bighashmap::core::big_hash_map< T >::find (const std::string & key, char * value_buffer) [inline, virtual]
Implements aitools::bighashmap::core::raw_big_hash_map.
Definition at line 134 of file big_hash_map.hpp.
References aitools::util::hash32(), and aitools::bighashmap::core::big_hash_map< T >::maps_.
template<typename T> bool aitools::bighashmap::core::big_hash_map< T >::find (const key_type & key, value_type & value) [inline]
Definition at line 127 of file big_hash_map.hpp.
References aitools::util::hash32(), and aitools::bighashmap::core::big_hash_map< T >::maps_.
template<typename T> static big_hash_map* aitools::bighashmap::core::big_hash_map< T >::open (const bfs::path & idx_file, util::memory_type mem) [inline, static]
Definition at line 94 of file big_hash_map.hpp.
References aitools::bighashmap::core::big_hash_map< T >::big_hash_map(), aitools::bighashmap::core::big_hash_map< T >::table_size(), aitools::util::throw_runtime_error(), and aitools::util::to_bytes().
template<typename T> uint64_t aitools::bighashmap::core::big_hash_map< T >::size () const [inline, virtual]
Implements aitools::bighashmap::core::raw_big_hash_map.
Definition at line 146 of file big_hash_map.hpp.
References aitools::bighashmap::core::big_hash_map< T >::size_.
Referenced by aitools::bighashmap::core::big_hash_map< T >::table_size().
template<typename T> static uint64_t aitools::bighashmap::core::big_hash_map< T >::table_size (const bfs::path & dir) [inline, static, private]
Definition at line 55 of file big_hash_map.hpp.
References aitools::bighashmap::core::big_hash_map< T >::size().
Referenced by aitools::bighashmap::core::big_hash_map< T >::open().
Member Data Documentation
template<typename T> const std::string aitools::bighashmap::core::big_hash_map< T >::index_file_name [inline, static]
Definition at line 36 of file big_hash_map.hpp.
template<typename T> std::vector<map_type*> aitools::bighashmap::core::big_hash_map< T >::maps_ [private]
Definition at line 153 of file big_hash_map.hpp.
Referenced by aitools::bighashmap::core::big_hash_map< T >::big_hash_map(), aitools::bighashmap::core::big_hash_map< T >::find(), and aitools::bighashmap::core::big_hash_map< T >::~big_hash_map().
template<typename T> uint64_t aitools::bighashmap::core::big_hash_map< T >::size_ [private]
Definition at line 154 of file big_hash_map.hpp.
Referenced by aitools::bighashmap::core::big_hash_map< T >::big_hash_map(), and aitools::bighashmap::core::big_hash_map< T >::size().
The documentation for this class was generated from the following file:
include/core/big_hash_map.hpp