aitools::bighashmap::core::internal_map< T > Class Template Reference
aitools::bighashmap::core::internal_map< T > Class Template Reference
#include <internal_map.hpp>
Public Types
typedef cmph_map< T > base_type
typedef base_type::key_type key_type
typedef base_type::value_type value_type
typedef base_type::checksum_type checksum_type
Public Member Functions
~internal_map ()
bool find (const key_type &key, value_type &value)
Static Public Member Functions
static internal_map * open (const bfs::path &idx_file)
Private Types
typedef value::pair
< checksum_type, value_type > entry_type
typedef value::value_traits
< entry_type > entry_traits
Private Member Functions
internal_map ()
internal_map (const bfs::path &mph_file, const bfs::path &dat_file)
Private Attributes
char * data_
Detailed Description
template<typename T>
class aitools::bighashmap::core::internal_map< T >
Author:
martin.trenkmann@uni-weimar.de
Version:
Id
internal_map.hpp,v 1.2 2011/09/21 01:00:50 trenkman Exp
Definition at line 26 of file internal_map.hpp.
Member Typedef Documentation
template<typename T > typedef cmph_map<T> aitools::bighashmap::core::internal_map< T >::base_type
Definition at line 30 of file internal_map.hpp.
template<typename T > typedef base_type::checksum_type aitools::bighashmap::core::internal_map< T >::checksum_type
Reimplemented from aitools::bighashmap::core::cmph_map< T >.
Definition at line 33 of file internal_map.hpp.
template<typename T > typedef value::value_traits<entry_type> aitools::bighashmap::core::internal_map< T >::entry_traits [private]
Definition at line 38 of file internal_map.hpp.
template<typename T > typedef value::pair<checksum_type, value_type> aitools::bighashmap::core::internal_map< T >::entry_type [private]
Definition at line 37 of file internal_map.hpp.
template<typename T > typedef base_type::key_type aitools::bighashmap::core::internal_map< T >::key_type
Reimplemented from aitools::bighashmap::core::cmph_map< T >.
Definition at line 31 of file internal_map.hpp.
template<typename T > typedef base_type::value_type aitools::bighashmap::core::internal_map< T >::value_type
Reimplemented from aitools::bighashmap::core::cmph_map< T >.
Definition at line 32 of file internal_map.hpp.
Constructor & Destructor Documentation
template<typename T > aitools::bighashmap::core::internal_map< T >::internal_map () [inline, private]
Definition at line 42 of file internal_map.hpp.
Referenced by aitools::bighashmap::core::internal_map< T >::open().
template<typename T > aitools::bighashmap::core::internal_map< T >::internal_map (const bfs::path & mph_file, const bfs::path & dat_file) [inline, private]
Definition at line 45 of file internal_map.hpp.
References aitools::bighashmap::core::internal_map< T >::data_, aitools::util::fclose(), aitools::util::fopen(), aitools::util::fread(), aitools::bighashmap::core::cmph_map< T >::size(), aitools::value::value_traits< T >::size_of(), and aitools::util::throw_runtime_error().
template<typename T > aitools::bighashmap::core::internal_map< T >::~internal_map () [inline]
Definition at line 63 of file internal_map.hpp.
References aitools::bighashmap::core::internal_map< T >::data_.
Member Function Documentation
template<typename T > bool aitools::bighashmap::core::internal_map< T >::find (const key_type & key, value_type & value) [inline, virtual]
Implements aitools::bighashmap::core::cmph_map< T >.
Definition at line 89 of file internal_map.hpp.
References aitools::value::value_traits< T >::copy_from(), aitools::bighashmap::core::internal_map< T >::data_, aitools::value::pair< T1, T2 >::e1(), aitools::value::pair< T1, T2 >::e2(), aitools::bighashmap::core::cmph_map< T >::hash(), aitools::util::log_debug(), and aitools::value::value_traits< T >::size_of().
template<typename T > static internal_map* aitools::bighashmap::core::internal_map< T >::open (const bfs::path & idx_file) [inline, static]
Definition at line 71 of file internal_map.hpp.
References aitools::bighashmap::core::internal_map< T >::internal_map(), and aitools::util::throw_runtime_error().
Member Data Documentation
template<typename T > char* aitools::bighashmap::core::internal_map< T >::data_ [private]
Definition at line 112 of file internal_map.hpp.
Referenced by aitools::bighashmap::core::internal_map< T >::find(), aitools::bighashmap::core::internal_map< T >::internal_map(), and aitools::bighashmap::core::internal_map< T >::~internal_map().
The documentation for this class was generated from the following file:
include/core/internal_map.hpp