aitools::invertedindex::GenericRecord Class Reference
aitools::invertedindex::GenericRecord Class Reference
#include <GenericRecord.hpp>
Public Member Functions
GenericRecord ()
GenericRecord (const GenericRecord &record)
GenericRecord (const std::string &key, const ByteBuffer &value)
~GenericRecord ()
std::string & key ()
const std::string & key () const
GenericRecord & operator= (const GenericRecord &record)
bool operator== (const GenericRecord &record) const
bool operator!= (const GenericRecord &record) const
ByteBuffer & value ()
const ByteBuffer & value () const
bool write (FILE *file)
bool read (FILE *file)
size_t size () const
Static Public Attributes
static const size_t max_key_size
static const size_t max_val_size
Private Types
typedef uint16_t key_size_t
typedef uint16_t val_size_t
Private Attributes
std::string key_
ByteBuffer val_
key_size_t key_size_
val_size_t val_size_
Static Private Attributes
static const size_t sizeof_key_size_t = sizeof(key_size_t)
static const size_t sizeof_val_size_t = sizeof(val_size_t)
Detailed Description
A class to represent a key value pair. The key is a string and the value is a generic byte buffer.
Author:
martin.trenkmann@uni-weimar.de
Created on Jun 22, 2008
Id
GenericRecord.hpp,v 1.28 2011/03/05 03:49:04 trenkman Exp
Definition at line 24 of file GenericRecord.hpp.
Member Typedef Documentation
typedef uint16_t aitools::invertedindex::GenericRecord::key_size_t [private]
Definition at line 28 of file GenericRecord.hpp.
typedef uint16_t aitools::invertedindex::GenericRecord::val_size_t [private]
Definition at line 29 of file GenericRecord.hpp.
Constructor & Destructor Documentation
aitools::invertedindex::GenericRecord::GenericRecord ()
Definition at line 10 of file GenericRecord.cpp.
aitools::invertedindex::GenericRecord::GenericRecord (const GenericRecord & record)
Definition at line 15 of file GenericRecord.cpp.
aitools::invertedindex::GenericRecord::GenericRecord (const std::string & key, const ByteBuffer & value)
Definition at line 22 of file GenericRecord.cpp.
aitools::invertedindex::GenericRecord::~GenericRecord ()
Definition at line 29 of file GenericRecord.cpp.
Member Function Documentation
const std::string & aitools::invertedindex::GenericRecord::key () const
Definition at line 39 of file GenericRecord.cpp.
std::string & aitools::invertedindex::GenericRecord::key ()
Definition at line 33 of file GenericRecord.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and aitools::invertedindex::Record< Value >::to_generic().
bool aitools::invertedindex::GenericRecord::operator!= (const GenericRecord & record) const
Definition at line 59 of file GenericRecord.cpp.
GenericRecord & aitools::invertedindex::GenericRecord::operator= (const GenericRecord & record)
Definition at line 45 of file GenericRecord.cpp.
bool aitools::invertedindex::GenericRecord::operator== (const GenericRecord & record) const
Definition at line 53 of file GenericRecord.cpp.
bool aitools::invertedindex::GenericRecord::read (FILE * file)
Definition at line 89 of file GenericRecord.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
size_t aitools::invertedindex::GenericRecord::size () const
Definition at line 104 of file GenericRecord.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
const ByteBuffer & aitools::invertedindex::GenericRecord::value () const
Definition at line 71 of file GenericRecord.cpp.
ByteBuffer & aitools::invertedindex::GenericRecord::value ()
Definition at line 65 of file GenericRecord.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and aitools::invertedindex::Record< Value >::to_generic().
bool aitools::invertedindex::GenericRecord::write (FILE * file)
Definition at line 77 of file GenericRecord.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
Member Data Documentation
std::string aitools::invertedindex::GenericRecord::key_ [private]
Definition at line 75 of file GenericRecord.hpp.
key_size_t aitools::invertedindex::GenericRecord::key_size_ [private]
Definition at line 77 of file GenericRecord.hpp.
const size_t aitools::invertedindex::GenericRecord::max_key_size [static]
Definition at line 33 of file GenericRecord.hpp.
const size_t aitools::invertedindex::GenericRecord::max_val_size [static]
Definition at line 34 of file GenericRecord.hpp.
const size_t aitools::invertedindex::GenericRecord::sizeof_key_size_t = sizeof(key_size_t) [static, private]
Definition at line 38 of file GenericRecord.hpp.
const size_t aitools::invertedindex::GenericRecord::sizeof_val_size_t = sizeof(val_size_t) [static, private]
Definition at line 39 of file GenericRecord.hpp.
ByteBuffer aitools::invertedindex::GenericRecord::val_ [private]
Definition at line 76 of file GenericRecord.hpp.
val_size_t aitools::invertedindex::GenericRecord::val_size_ [private]
Definition at line 78 of file GenericRecord.hpp.
The documentation for this class was generated from the following files:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/core/GenericRecord.hpp
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/core/GenericRecord.cpp