de::aitools::aq::invertedindex::core::TestIndexer Class Reference
de::aitools::aq::invertedindex::core::TestIndexer Class Reference
Public Member Functions
final void testSingleDouble ()
final void testSingleInt ()
final void testSingleLong ()
final void testSingleBuffer ()
final void testSingleString ()
final void testDoubleDouble ()
final void testDoubleInt ()
final void testDoubleLong ()
final void testIntDouble ()
final void testIntInt ()
final void testIntLong ()
final void testLongDouble ()
final void testLongInt ()
final void testLongLong ()
final void testDoubleString ()
final void testIntString ()
final void testLongString ()
final void testDoubleDoubleDouble ()
final void testDoubleIntDouble ()
final void testDoubleIntInt ()
final void testIntDoubleDouble ()
final void testIntIntDouble ()
final void testIntIntInt ()
final void testLongDoubleDouble ()
final void testLongIntDouble ()
final void testLongIntInt ()
final void testDoubleDoubleIntInt ()
final void testDoubleDoubleLongLong ()
final void testIntIntDoubleDouble ()
final void testIntIntLongLong ()
final void testLongDoubleLongInt ()
final void testLongLongDoubleDouble ()
final void testLongLongIntInt ()
final void testDoubleLongLongInt ()
Static Public Member Functions
static< VextendsValue > List< V > createRandomValues (Class< V > clazz, int count) throws InstantiationException, IllegalAccessException
Static Private Member Functions
static void deleteAll (File directory)
static< VextendsValue > void test (Class< V > clazz, int count)
Static Private Attributes
static final int RECORD_COUNT = 100000
static final File tmpIndexDir = new File("testIndexer")
Detailed Description
Definition at line 48 of file TestIndexer.java.
Member Function Documentation
static <VextendsValue> List<V> de::aitools::aq::invertedindex::core::TestIndexer::createRandomValues (Class< V > clazz, int count) throws InstantiationException, IllegalAccessException [inline, static]
Definition at line 56 of file TestIndexer.java.
References de::aitools::aq::value::single::SingleBuffer::getBuffer().
Referenced by test().
static void de::aitools::aq::invertedindex::core::TestIndexer::deleteAll (File directory) [inline, static, private]
Definition at line 100 of file TestIndexer.java.
Referenced by test().
static <VextendsValue> void de::aitools::aq::invertedindex::core::TestIndexer::test (Class< V > clazz, int count) [inline, static, private]
Definition at line 110 of file TestIndexer.java.
References createRandomValues(), deleteAll(), RECORD_COUNT, de::aitools::aq::invertedindex::core::Configuration::setExpectedNumberOfRecords(), de::aitools::aq::invertedindex::core::Configuration::setIndexDirectory(), and tmpIndexDir.
Referenced by testDoubleDouble(), testDoubleDoubleDouble(), testDoubleDoubleIntInt(), testDoubleDoubleLongLong(), testDoubleInt(), testDoubleIntDouble(), testDoubleIntInt(), testDoubleLong(), testDoubleLongLongInt(), testDoubleString(), testIntDouble(), testIntDoubleDouble(), testIntInt(), testIntIntDouble(), testIntIntDoubleDouble(), testIntIntInt(), testIntIntLongLong(), testIntLong(), testIntString(), testLongDouble(), testLongDoubleDouble(), testLongDoubleLongInt(), testLongInt(), testLongIntDouble(), testLongIntInt(), testLongLong(), testLongLongDoubleDouble(), testLongLongIntInt(), testLongString(), testSingleBuffer(), testSingleDouble(), testSingleInt(), testSingleLong(), and testSingleString().
final void de::aitools::aq::invertedindex::core::TestIndexer::testDoubleDouble () [inline]
Definition at line 203 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testDoubleDoubleDouble () [inline]
Definition at line 271 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testDoubleDoubleIntInt () [inline]
Definition at line 320 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testDoubleDoubleLongLong () [inline]
Definition at line 325 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testDoubleInt () [inline]
Definition at line 208 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testDoubleIntDouble () [inline]
Definition at line 276 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testDoubleIntInt () [inline]
Definition at line 281 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testDoubleLong () [inline]
Definition at line 213 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testDoubleLongLongInt () [inline]
Definition at line 355 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testDoubleString () [inline]
Definition at line 252 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testIntDouble () [inline]
Definition at line 218 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testIntDoubleDouble () [inline]
Definition at line 286 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testIntInt () [inline]
Definition at line 223 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testIntIntDouble () [inline]
Definition at line 291 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testIntIntDoubleDouble () [inline]
Definition at line 330 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testIntIntInt () [inline]
Definition at line 296 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testIntIntLongLong () [inline]
Definition at line 335 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testIntLong () [inline]
Definition at line 228 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testIntString () [inline]
Definition at line 257 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testLongDouble () [inline]
Definition at line 233 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testLongDoubleDouble () [inline]
Definition at line 301 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testLongDoubleLongInt () [inline]
Definition at line 340 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testLongInt () [inline]
Definition at line 238 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testLongIntDouble () [inline]
Definition at line 306 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testLongIntInt () [inline]
Definition at line 311 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testLongLong () [inline]
Definition at line 243 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testLongLongDoubleDouble () [inline]
Definition at line 345 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testLongLongIntInt () [inline]
Definition at line 350 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testLongString () [inline]
Definition at line 262 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testSingleBuffer () [inline]
Definition at line 189 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testSingleDouble () [inline]
Definition at line 174 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testSingleInt () [inline]
Definition at line 179 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testSingleLong () [inline]
Definition at line 184 of file TestIndexer.java.
References RECORD_COUNT, and test().
final void de::aitools::aq::invertedindex::core::TestIndexer::testSingleString () [inline]
Definition at line 194 of file TestIndexer.java.
References RECORD_COUNT, and test().
Member Data Documentation
final int de::aitools::aq::invertedindex::core::TestIndexer::RECORD_COUNT = 100000 [static, private]
Definition at line 50 of file TestIndexer.java.
Referenced by test(), testDoubleDouble(), testDoubleDoubleDouble(), testDoubleDoubleIntInt(), testDoubleDoubleLongLong(), testDoubleInt(), testDoubleIntDouble(), testDoubleIntInt(), testDoubleLong(), testDoubleLongLongInt(), testDoubleString(), testIntDouble(), testIntDoubleDouble(), testIntInt(), testIntIntDouble(), testIntIntDoubleDouble(), testIntIntInt(), testIntIntLongLong(), testIntLong(), testIntString(), testLongDouble(), testLongDoubleDouble(), testLongDoubleLongInt(), testLongInt(), testLongIntDouble(), testLongIntInt(), testLongLong(), testLongLongDoubleDouble(), testLongLongIntInt(), testLongString(), testSingleBuffer(), testSingleDouble(), testSingleInt(), testSingleLong(), and testSingleString().
final File de::aitools::aq::invertedindex::core::TestIndexer::tmpIndexDir = new File("testIndexer") [static, private]
Definition at line 52 of file TestIndexer.java.
Referenced by test().
The documentation for this class was generated from the following file:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex2-java/test/de/aitools/aq/invertedindex/core/TestIndexer.java