aitools::invertedindex::Quantile Class Reference
aitools::invertedindex::Quantile Class Reference
#include <Quantile.hpp>
Public Types
enum Order {
P10, P20, P30, P40,
P50, P60, P70, P80,
P90, P91, P92, P93,
P94, P95, P96, P97,
P98, P99, P100, COUNT
}
Public Member Functions
Quantile ()
Quantile (const Quantile &quantile)
~Quantile ()
void clear ()
uint32_t & at (Order order)
Quantile & operator= (const Quantile &quantile)
Quantile & operator+= (const Quantile &quantile)
void parse (std::istream &is)
void print (std::ostream &os) const
uint32_t * values ()
const uint32_t * values () const
uint32_t get (Order order) const
Static Public Attributes
static const size_t size = COUNT * sizeof(uint32_t)
Private Attributes
uint32_t values_ [COUNT]
Detailed Description
A class to represent an array of quantile values.
Author:
martin.trenkmann@uni-weimar.de
Version:
aitools 2.0
Created on Jun 22, 2008
Id
Quantile.hpp,v 1.24 2010/03/18 22:28:49 trenkman Exp
Definition at line 24 of file Quantile.hpp.
Member Enumeration Documentation
enum aitools::invertedindex::Quantile::Order
Enumerator:
P10
P20
P30
P40
P50
P60
P70
P80
P90
P91
P92
P93
P94
P95
P96
P97
P98
P99
P100
COUNT
Definition at line 28 of file Quantile.hpp.
Constructor & Destructor Documentation
aitools::invertedindex::Quantile::Quantile ()
Definition at line 7 of file Quantile.cpp.
References size, and values_.
aitools::invertedindex::Quantile::Quantile (const Quantile & quantile)
Definition at line 12 of file Quantile.cpp.
References size, and values_.
aitools::invertedindex::Quantile::~Quantile ()
Definition at line 17 of file Quantile.cpp.
Member Function Documentation
uint32_t & aitools::invertedindex::Quantile::at (Order order)
Definition at line 27 of file Quantile.cpp.
References values_.
Referenced by aitools::invertedindex::InternalIntroSort::comp_quantile().
void aitools::invertedindex::Quantile::clear ()
Definition at line 21 of file Quantile.cpp.
References size, and values_.
Referenced by BOOST_AUTO_TEST_CASE(), aitools::invertedindex::InternalIntroSort::comp_quantile(), and aitools::invertedindex::ExternalMergeSort::partition().
uint32_t aitools::invertedindex::Quantile::get (Order order) const
Definition at line 83 of file Quantile.cpp.
References values_.
Quantile & aitools::invertedindex::Quantile::operator+= (const Quantile & quantile)
Definition at line 43 of file Quantile.cpp.
References COUNT, and values_.
Quantile & aitools::invertedindex::Quantile::operator= (const Quantile & quantile)
Definition at line 33 of file Quantile.cpp.
References size, and values_.
void aitools::invertedindex::Quantile::parse (std::istream & is)
Definition at line 53 of file Quantile.cpp.
References COUNT, and values_.
Referenced by BOOST_AUTO_TEST_CASE().
void aitools::invertedindex::Quantile::print (std::ostream & os) const
Definition at line 62 of file Quantile.cpp.
References COUNT, and values_.
Referenced by BOOST_AUTO_TEST_CASE().
const uint32_t * aitools::invertedindex::Quantile::values () const
Definition at line 77 of file Quantile.cpp.
References values_.
uint32_t * aitools::invertedindex::Quantile::values ()
Definition at line 71 of file Quantile.cpp.
References values_.
Referenced by BOOST_AUTO_TEST_CASE().
Member Data Documentation
const size_t aitools::invertedindex::Quantile::size = COUNT * sizeof(uint32_t) [static]
Definition at line 36 of file Quantile.hpp.
Referenced by clear(), aitools::invertedindex::StorageBuilder::close(), aitools::invertedindex::StorageSearcher::open(), operator=(), and Quantile().
uint32_t aitools::invertedindex::Quantile::values_[COUNT] [private]
Definition at line 68 of file Quantile.hpp.
Referenced by at(), clear(), get(), operator+=(), operator=(), parse(), print(), Quantile(), and values().
The documentation for this class was generated from the following files:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/core/Quantile.hpp
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/core/Quantile.cpp