aitools::invertedindex::StorageSearcher Class Reference
aitools::invertedindex::StorageSearcher Class Reference
#include <StorageSearcher.hpp>
Public Member Functions
StorageSearcher ()
~StorageSearcher ()
void close ()
bool is_open () const
void open (const bfs::path &directory) throw (std::invalid_argument)
Iterator::SharedPointer get (const std::string &key) throw (std::runtime_error)
Iterator::SharedPointer get (const std::string &key, size_t length) throw (std::runtime_error)
Iterator::SharedPointer get (const std::string &key, Quantile::Order order) throw (std::runtime_error)
const Quantile & quantile (const std::string &key) const
const Vocabulary & vocabulary () const
const MPHashFunction & mphf () const
Private Types
typedef
PostlistReader::shared_pointer Reader
typedef StorageBuilder::Location Location
typedef std::vector< Location > LocationVector
typedef std::vector< Quantile > QuantileVector
typedef std::vector< Reader > ReaderVector
Private Attributes
ReaderVector readers_
QuantileVector quantiles_
LocationVector locations_
MPHashFunction hash_func_
Vocabulary vocabulary_
bfs::path directory_
boost::mutex mutex_
Static Private Attributes
static const Quantile empty_quantile
Detailed Description
A class to read postlists from an external storage.
Author:
martin.trenkmann@uni-weimar.de
Created on Jun 22, 2008
Id
StorageSearcher.hpp,v 1.6 2010/05/11 23:41:08 trenkman Exp
Definition at line 30 of file StorageSearcher.hpp.
Member Typedef Documentation
typedef StorageBuilder::Location aitools::invertedindex::StorageSearcher::Location [private]
Definition at line 35 of file StorageSearcher.hpp.
typedef std::vector<Location> aitools::invertedindex::StorageSearcher::LocationVector [private]
Definition at line 36 of file StorageSearcher.hpp.
typedef std::vector<Quantile> aitools::invertedindex::StorageSearcher::QuantileVector [private]
Definition at line 37 of file StorageSearcher.hpp.
typedef PostlistReader::shared_pointer aitools::invertedindex::StorageSearcher::Reader [private]
Definition at line 34 of file StorageSearcher.hpp.
typedef std::vector<Reader> aitools::invertedindex::StorageSearcher::ReaderVector [private]
Definition at line 38 of file StorageSearcher.hpp.
Constructor & Destructor Documentation
aitools::invertedindex::StorageSearcher::StorageSearcher ()
Definition at line 12 of file StorageSearcher.cpp.
aitools::invertedindex::StorageSearcher::~StorageSearcher ()
Definition at line 15 of file StorageSearcher.cpp.
Member Function Documentation
void aitools::invertedindex::StorageSearcher::close ()
Definition at line 19 of file StorageSearcher.cpp.
References readers_.
Iterator::SharedPointer aitools::invertedindex::StorageSearcher::get (const std::string & key, Quantile::Order order) throw (std::runtime_error)
Definition at line 87 of file StorageSearcher.cpp.
Iterator::SharedPointer aitools::invertedindex::StorageSearcher::get (const std::string & key, size_t length) throw (std::runtime_error)
Definition at line 72 of file StorageSearcher.cpp.
Iterator::SharedPointer aitools::invertedindex::StorageSearcher::get (const std::string & key) throw (std::runtime_error)
Definition at line 66 of file StorageSearcher.cpp.
bool aitools::invertedindex::StorageSearcher::is_open () const
Definition at line 25 of file StorageSearcher.cpp.
References readers_.
const MPHashFunction & aitools::invertedindex::StorageSearcher::mphf () const
Definition at line 110 of file StorageSearcher.cpp.
References hash_func_.
void aitools::invertedindex::StorageSearcher::open (const bfs::path & directory) throw (std::invalid_argument)
Definition at line 31 of file StorageSearcher.cpp.
References aitools::invertedindex::StorageBuilder::data_file, aitools::util::fclose(), aitools::invertedindex::System::fopen(), aitools::invertedindex::System::fread(), aitools::invertedindex::StorageBuilder::mphf_file, aitools::invertedindex::StorageBuilder::quantile_file, aitools::invertedindex::Quantile::size, aitools::invertedindex::StorageBuilder::storage_file, aitools::invertedindex::Converter::ui32_to_str(), and aitools::invertedindex::StorageBuilder::vocab_file.
const Quantile & aitools::invertedindex::StorageSearcher::quantile (const std::string & key) const
Definition at line 94 of file StorageSearcher.cpp.
References aitools::invertedindex::Vocabulary::contains(), empty_quantile, aitools::invertedindex::MPHashFunction::hash(), hash_func_, quantiles_, and vocabulary_.
const Vocabulary & aitools::invertedindex::StorageSearcher::vocabulary () const
Definition at line 104 of file StorageSearcher.cpp.
References vocabulary_.
Member Data Documentation
bfs::path aitools::invertedindex::StorageSearcher::directory_ [private]
Definition at line 81 of file StorageSearcher.hpp.
const Quantile aitools::invertedindex::StorageSearcher::empty_quantile [static, private]
Definition at line 42 of file StorageSearcher.hpp.
Referenced by quantile().
MPHashFunction aitools::invertedindex::StorageSearcher::hash_func_ [private]
Definition at line 79 of file StorageSearcher.hpp.
Referenced by mphf(), and quantile().
LocationVector aitools::invertedindex::StorageSearcher::locations_ [private]
Definition at line 78 of file StorageSearcher.hpp.
boost::mutex aitools::invertedindex::StorageSearcher::mutex_ [private]
Definition at line 82 of file StorageSearcher.hpp.
QuantileVector aitools::invertedindex::StorageSearcher::quantiles_ [private]
Definition at line 77 of file StorageSearcher.hpp.
Referenced by quantile().
ReaderVector aitools::invertedindex::StorageSearcher::readers_ [private]
Definition at line 76 of file StorageSearcher.hpp.
Referenced by close(), and is_open().
Vocabulary aitools::invertedindex::StorageSearcher::vocabulary_ [private]
Definition at line 80 of file StorageSearcher.hpp.
Referenced by quantile(), and vocabulary().
The documentation for this class was generated from the following files:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/core/StorageSearcher.hpp
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/core/StorageSearcher.cpp