aitools::invertedindex::PostlistSorter Class Reference
aitools::invertedindex::PostlistSorter Class Reference
#include <PostlistSorter.hpp>
Static Public Member Functions
template<typename Value >
static void sort (Postlist< Value > &postlist, Quantile &quantile, Sorting mode)
Private Types
typedef Configuration::Sorting Sorting
Private Member Functions
PostlistSorter ()
Detailed Description
A class to sort postlists.
Author:
martin.trenkmann@uni-weimar.de
Created on Jun 22, 2008
Id
PostlistSorter.hpp,v 1.29 2010/05/11 23:41:08 trenkman Exp
Definition at line 21 of file PostlistSorter.hpp.
Member Typedef Documentation
typedef Configuration::Sorting aitools::invertedindex::PostlistSorter::Sorting [private]
Definition at line 25 of file PostlistSorter.hpp.
Constructor & Destructor Documentation
aitools::invertedindex::PostlistSorter::PostlistSorter () [private]
Member Function Documentation
template<typename Value > void aitools::invertedindex::PostlistSorter::sort (Postlist< Value > & postlist, Quantile & quantile, Sorting mode) [inline, static]
Definition at line 44 of file PostlistSorter.hpp.
References aitools::invertedindex::ExternalMergeSort::max_memory, aitools::invertedindex::Postlist< Value >::payload(), aitools::invertedindex::ExternalMergeSort::sort(), and aitools::invertedindex::InternalIntroSort::sort().
The documentation for this class was generated from the following file:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/core/PostlistSorter.hpp