aitools::invertedindex::MPHashFunction Class Reference
aitools::invertedindex::MPHashFunction Class Reference
#include <MPHashFunction.hpp>
Public Types
enum Algorithm {
BMZ, CHM, BRZ, FCH,
BDZ, CHD
}
Public Member Functions
MPHashFunction ()
~MPHashFunction ()
void create (const bfs::path &vocabulary, Algorithm algorithm=BDZ) throw (std::invalid_argument, std::runtime_error)
void create (const Vocabulary &vocabulary, Algorithm algorithm=BDZ) throw (std::runtime_error)
uint32_t hash (const std::string &key) const
void load (const bfs::path &path) throw (std::invalid_argument)
void save (const bfs::path &path) throw (std::invalid_argument)
uint32_t size () const
Private Member Functions
void clear_ ()
void create_ (Algorithm algorithm, cmph_io_adapter_t *source) throw (std::runtime_error)
Private Attributes
cmph_t * mphf_
Detailed Description
A class to generate a minimal perfect hash function.
A mphf maps a static set of n keys into a set of m integer numbers.
Minimal means that m is equal to n, thus all hash values are within [0, m).
Perfect means that the hash function produces no collisions.
This class is a wrapper of the CMPH library.
Author:
martin.trenkmann@uni-weimar.de
See also:
http://cmph.sourceforge.net
Created on Jun 22, 2008
Id
MPHashFunction.hpp,v 1.18 2010/05/11 23:41:08 trenkman Exp
Definition at line 31 of file MPHashFunction.hpp.
Member Enumeration Documentation
enum aitools::invertedindex::MPHashFunction::Algorithm
Defines the algorithms supported by the CMPH library.
Enumerator:
BMZ
CHM
BRZ
FCH
BDZ
CHD
Definition at line 38 of file MPHashFunction.hpp.
Constructor & Destructor Documentation
aitools::invertedindex::MPHashFunction::MPHashFunction ()
The default constructor.
Definition at line 9 of file MPHashFunction.cpp.
aitools::invertedindex::MPHashFunction::~MPHashFunction ()
The destructor.
Definition at line 13 of file MPHashFunction.cpp.
References clear_().
Member Function Documentation
void aitools::invertedindex::MPHashFunction::clear_ () [private]
Definition at line 93 of file MPHashFunction.cpp.
References mphf_.
Referenced by ~MPHashFunction().
void aitools::invertedindex::MPHashFunction::create (const Vocabulary & vocabulary, Algorithm algorithm = BDZ) throw (std::runtime_error)
Definition at line 46 of file MPHashFunction.cpp.
void aitools::invertedindex::MPHashFunction::create (const bfs::path & vocabulary, Algorithm algorithm = BDZ) throw (std::invalid_argument, std::runtime_error)
Definition at line 28 of file MPHashFunction.cpp.
References aitools::invertedindex::System::fclose(), and aitools::invertedindex::System::fopen().
Referenced by BOOST_AUTO_TEST_CASE(), and aitools::invertedindex::StorageBuilder::close().
void aitools::invertedindex::MPHashFunction::create_ (Algorithm algorithm, cmph_io_adapter_t * source) throw (std::runtime_error) [private]
Definition at line 101 of file MPHashFunction.cpp.
References aitools::invertedindex::Exception::throw_runtime_error().
uint32_t aitools::invertedindex::MPHashFunction::hash (const std::string & key) const
Definition at line 72 of file MPHashFunction.cpp.
References mphf_.
Referenced by BOOST_AUTO_TEST_CASE(), aitools::invertedindex::StorageBuilder::close(), and aitools::invertedindex::StorageSearcher::quantile().
void aitools::invertedindex::MPHashFunction::load (const bfs::path & path) throw (std::invalid_argument) [virtual]
Load the object from a file.
Parameters:
file the path to the file
Implements aitools::invertedindex::Externalizable.
Definition at line 19 of file MPHashFunction.cpp.
References aitools::invertedindex::System::fclose(), and aitools::invertedindex::System::fopen().
Referenced by BOOST_AUTO_TEST_CASE().
void aitools::invertedindex::MPHashFunction::save (const bfs::path & path) throw (std::invalid_argument) [virtual]
Save the object to a file.
Parameters:
file the path to the file
Implements aitools::invertedindex::Externalizable.
Definition at line 78 of file MPHashFunction.cpp.
References aitools::invertedindex::System::fclose(), and aitools::invertedindex::System::fopen().
Referenced by BOOST_AUTO_TEST_CASE(), and aitools::invertedindex::StorageBuilder::close().
uint32_t aitools::invertedindex::MPHashFunction::size () const
Definition at line 87 of file MPHashFunction.cpp.
References mphf_.
Referenced by BOOST_AUTO_TEST_CASE(), and aitools::invertedindex::StorageBuilder::close().
Member Data Documentation
cmph_t* aitools::invertedindex::MPHashFunction::mphf_ [private]
Definition at line 79 of file MPHashFunction.hpp.
Referenced by clear_(), hash(), and size().
The documentation for this class was generated from the following files:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/core/MPHashFunction.hpp
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/core/MPHashFunction.cpp