de::aitools::aq::value::single::SingleBuffer Class Reference
de::aitools::aq::value::single::SingleBuffer Class Reference
Public Member Functions
SingleBuffer ()
SingleBuffer (byte[] bytes)
SingleBuffer (SingleBuffer array)
SingleBuffer (ByteBuffer buffer)
SingleBuffer (int capacity)
ByteBuffer getBuffer ()
void setBuffer (ByteBuffer buffer)
void copyFrom (Pointer buffer)
void copyTo (Pointer buffer)
boolean parseFrom (Scanner sc)
PrintStream printTo (PrintStream stream)
Memory getSharedMemory ()
int getSerializedSize ()
int hashCode ()
boolean equals (Object obj)
void reallocate (int capacity)
Static Public Attributes
static final int NATIVE_TYPE_ID = 104
Private Attributes
ByteBuffer e
Static Private Attributes
static final int SIZEOF_BUFFER_SIZE = Value.SIZEOF_SHORT
Detailed Description
Author:
martin.trenkmann@uni-weimar.de
Version:
Id
SingleBuffer.java,v 1.2 2011/04/08 22:37:47 trenkman Exp
Definition at line 18 of file SingleBuffer.java.
Constructor & Destructor Documentation
de::aitools::aq::value::single::SingleBuffer::SingleBuffer () [inline]
Definition at line 24 of file SingleBuffer.java.
References reallocate().
de::aitools::aq::value::single::SingleBuffer::SingleBuffer (byte[] bytes) [inline]
Definition at line 28 of file SingleBuffer.java.
References e.
de::aitools::aq::value::single::SingleBuffer::SingleBuffer (SingleBuffer array) [inline]
Definition at line 33 of file SingleBuffer.java.
References e.
de::aitools::aq::value::single::SingleBuffer::SingleBuffer (ByteBuffer buffer) [inline]
Definition at line 37 of file SingleBuffer.java.
References e.
de::aitools::aq::value::single::SingleBuffer::SingleBuffer (int capacity) [inline]
Definition at line 42 of file SingleBuffer.java.
References reallocate().
Member Function Documentation
void de::aitools::aq::value::single::SingleBuffer::copyFrom (Pointer buffer) [inline]
Definition at line 56 of file SingleBuffer.java.
References e, and SIZEOF_BUFFER_SIZE.
void de::aitools::aq::value::single::SingleBuffer::copyTo (Pointer buffer) [inline]
Definition at line 63 of file SingleBuffer.java.
References e, and SIZEOF_BUFFER_SIZE.
boolean de::aitools::aq::value::single::SingleBuffer::equals (Object obj) [inline]
Definition at line 98 of file SingleBuffer.java.
References e.
ByteBuffer de::aitools::aq::value::single::SingleBuffer::getBuffer () [inline]
Definition at line 46 of file SingleBuffer.java.
References e.
Referenced by de::aitools::aq::invertedindex::core::TestIndexer::createRandomValues().
int de::aitools::aq::value::single::SingleBuffer::getSerializedSize () [inline]
Definition at line 85 of file SingleBuffer.java.
References e, and SIZEOF_BUFFER_SIZE.
Referenced by getSharedMemory().
Memory de::aitools::aq::value::single::SingleBuffer::getSharedMemory () [inline]
Definition at line 80 of file SingleBuffer.java.
References getSerializedSize().
int de::aitools::aq::value::single::SingleBuffer::hashCode () [inline]
Definition at line 90 of file SingleBuffer.java.
References e.
boolean de::aitools::aq::value::single::SingleBuffer::parseFrom (Scanner sc) [inline]
Definition at line 70 of file SingleBuffer.java.
PrintStream de::aitools::aq::value::single::SingleBuffer::printTo (PrintStream stream) [inline]
Definition at line 75 of file SingleBuffer.java.
void de::aitools::aq::value::single::SingleBuffer::reallocate (int capacity) [inline]
Definition at line 114 of file SingleBuffer.java.
References e.
Referenced by SingleBuffer().
void de::aitools::aq::value::single::SingleBuffer::setBuffer (ByteBuffer buffer) [inline]
Definition at line 50 of file SingleBuffer.java.
References e.
Member Data Documentation
ByteBuffer de::aitools::aq::value::single::SingleBuffer::e [private]
Definition at line 119 of file SingleBuffer.java.
Referenced by copyFrom(), copyTo(), equals(), getBuffer(), getSerializedSize(), hashCode(), reallocate(), setBuffer(), and SingleBuffer().
final int de::aitools::aq::value::single::SingleBuffer::NATIVE_TYPE_ID = 104 [static]
Definition at line 20 of file SingleBuffer.java.
final int de::aitools::aq::value::single::SingleBuffer::SIZEOF_BUFFER_SIZE = Value.SIZEOF_SHORT [static, private]
Definition at line 22 of file SingleBuffer.java.
Referenced by copyFrom(), copyTo(), and getSerializedSize().
The documentation for this class was generated from the following file:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex2-java/src/de/aitools/aq/value/single/SingleBuffer.java