aitools::invertedindex::Header Class Reference
aitools::invertedindex::Header Class Reference
#include <IndexMessages.pb.h>
Public Member Functions
Header ()
virtual ~Header ()
Header (const Header &from)
Header & operator= (const Header &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Header *other)
Header * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const Header &from)
void MergeFrom (const Header &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_payload () const
void clear_payload ()
inline::google::protobuf::int64 payload () const
void set_payload (::google::protobuf::int64 value)
bool has_key_count () const
void clear_key_count ()
inline::google::protobuf::int64 key_count () const
void set_key_count (::google::protobuf::int64 value)
bool has_value_count () const
void clear_value_count ()
inline::google::protobuf::int64 value_count () const
void set_value_count (::google::protobuf::int64 value)
bool has_minor_version () const
void clear_minor_version ()
inline::google::protobuf::int32 minor_version () const
void set_minor_version (::google::protobuf::int32 value)
bool has_major_version () const
void clear_major_version ()
inline::google::protobuf::int32 major_version () const
void set_major_version (::google::protobuf::int32 value)
bool has_indexing_duration () const
void clear_indexing_duration ()
inline::google::protobuf::int32 indexing_duration () const
void set_indexing_duration (::google::protobuf::int32 value)
bool has_value_class_name () const
void clear_value_class_name ()
const ::std::string & value_class_name () const
void set_value_class_name (const ::std::string &value)
void set_value_class_name (const char *value)
void set_value_class_name (const char *value, size_t size)
inline::std::string * mutable_value_class_name ()
bool has_postlist_sorting () const
void clear_postlist_sorting ()
inline::aitools::invertedindex::Configuration_Sorting postlist_sorting () const
void set_postlist_sorting (::aitools::invertedindex::Configuration_Sorting value)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const Header & default_instance ()
Static Public Attributes
static const int kPayloadFieldNumber = 1
static const int kKeyCountFieldNumber = 2
static const int kValueCountFieldNumber = 3
static const int kMinorVersionFieldNumber = 4
static const int kMajorVersionFieldNumber = 5
static const int kIndexingDurationFieldNumber = 6
static const int kValueClassNameFieldNumber = 7
static const int kPostlistSortingFieldNumber = 8
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
bool _has_bit (int index) const
void _set_bit (int index)
void _clear_bit (int index)
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
int _cached_size_
::google::protobuf::int64 payload_
::google::protobuf::int64 key_count_
::google::protobuf::int64 value_count_
::google::protobuf::int32 minor_version_
::google::protobuf::int32 major_version_
::google::protobuf::int32 indexing_duration_
::std::string * value_class_name_
int postlist_sorting_
::google::protobuf::uint32 _has_bits_ [(8+31)/32]
Static Private Attributes
static const ::std::string _default_value_class_name_
static Header * default_instance_ = NULL
Friends
void protobuf_AddDesc_IndexMessages_2eproto ()
void protobuf_AssignDesc_IndexMessages_2eproto ()
void protobuf_ShutdownFile_IndexMessages_2eproto ()
Detailed Description
Definition at line 248 of file IndexMessages.pb.h.
Constructor & Destructor Documentation
aitools::invertedindex::Header::Header ()
Definition at line 597 of file IndexMessages.pb.cc.
aitools::invertedindex::Header::~Header () [virtual]
Definition at line 622 of file IndexMessages.pb.cc.
aitools::invertedindex::Header::Header (const Header & from)
Definition at line 604 of file IndexMessages.pb.cc.
References SharedCtor().
Member Function Documentation
void aitools::invertedindex::Header::_clear_bit (int index) [inline, private]
Definition at line 386 of file IndexMessages.pb.h.
References _has_bits_.
Referenced by clear_indexing_duration(), clear_key_count(), clear_major_version(), clear_minor_version(), clear_payload(), clear_postlist_sorting(), clear_value_class_name(), and clear_value_count().
bool aitools::invertedindex::Header::_has_bit (int index) const [inline, private]
Definition at line 380 of file IndexMessages.pb.h.
References _has_bits_.
Referenced by has_indexing_duration(), has_key_count(), has_major_version(), has_minor_version(), has_payload(), has_postlist_sorting(), has_value_class_name(), and has_value_count().
void aitools::invertedindex::Header::_set_bit (int index) [inline, private]
Definition at line 383 of file IndexMessages.pb.h.
References _has_bits_.
Referenced by mutable_value_class_name(), set_indexing_duration(), set_key_count(), set_major_version(), set_minor_version(), set_payload(), set_postlist_sorting(), set_value_class_name(), and set_value_count().
int aitools::invertedindex::Header::ByteSize () const
Definition at line 921 of file IndexMessages.pb.cc.
References unknown_fields().
void aitools::invertedindex::Header::Clear ()
Definition at line 649 of file IndexMessages.pb.cc.
void aitools::invertedindex::Header::clear_indexing_duration () [inline]
Definition at line 625 of file IndexMessages.pb.h.
References _clear_bit(), and indexing_duration_.
void aitools::invertedindex::Header::clear_key_count () [inline]
Definition at line 561 of file IndexMessages.pb.h.
References _clear_bit(), and key_count_.
void aitools::invertedindex::Header::clear_major_version () [inline]
Definition at line 609 of file IndexMessages.pb.h.
References _clear_bit(), and major_version_.
void aitools::invertedindex::Header::clear_minor_version () [inline]
Definition at line 593 of file IndexMessages.pb.h.
References _clear_bit(), and minor_version_.
void aitools::invertedindex::Header::clear_payload () [inline]
Definition at line 545 of file IndexMessages.pb.h.
References _clear_bit(), and payload_.
void aitools::invertedindex::Header::clear_postlist_sorting () [inline]
Definition at line 683 of file IndexMessages.pb.h.
References _clear_bit(), and postlist_sorting_.
void aitools::invertedindex::Header::clear_value_class_name () [inline]
Definition at line 641 of file IndexMessages.pb.h.
References _clear_bit(), _default_value_class_name_, and value_class_name_.
void aitools::invertedindex::Header::clear_value_count () [inline]
Definition at line 577 of file IndexMessages.pb.h.
References _clear_bit(), and value_count_.
void aitools::invertedindex::Header::CopyFrom (const Header & from)
Definition at line 1039 of file IndexMessages.pb.cc.
void aitools::invertedindex::Header::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 1033 of file IndexMessages.pb.cc.
Referenced by operator=().
const Header & aitools::invertedindex::Header::default_instance () [static]
Definition at line 639 of file IndexMessages.pb.cc.
const ::google::protobuf::Descriptor * aitools::invertedindex::Header::descriptor () [static]
Definition at line 634 of file IndexMessages.pb.cc.
References _default_value_class_name_, default_instance_, and value_class_name_.
int aitools::invertedindex::Header::GetCachedSize () const [inline]
Definition at line 288 of file IndexMessages.pb.h.
References _cached_size_.
google::protobuf::Metadata aitools::invertedindex::Header::GetMetadata () const
Definition at line 1066 of file IndexMessages.pb.cc.
bool aitools::invertedindex::Header::has_indexing_duration () const [inline]
Definition at line 622 of file IndexMessages.pb.h.
References _has_bit().
bool aitools::invertedindex::Header::has_key_count () const [inline]
Definition at line 558 of file IndexMessages.pb.h.
References _has_bit().
bool aitools::invertedindex::Header::has_major_version () const [inline]
Definition at line 606 of file IndexMessages.pb.h.
References _has_bit().
bool aitools::invertedindex::Header::has_minor_version () const [inline]
Definition at line 590 of file IndexMessages.pb.h.
References _has_bit().
bool aitools::invertedindex::Header::has_payload () const [inline]
Definition at line 542 of file IndexMessages.pb.h.
References _has_bit().
bool aitools::invertedindex::Header::has_postlist_sorting () const [inline]
Definition at line 680 of file IndexMessages.pb.h.
References _has_bit().
bool aitools::invertedindex::Header::has_value_class_name () const [inline]
Definition at line 638 of file IndexMessages.pb.h.
References _has_bit().
bool aitools::invertedindex::Header::has_value_count () const [inline]
Definition at line 574 of file IndexMessages.pb.h.
References _has_bit().
google::protobuf::int32 aitools::invertedindex::Header::indexing_duration () const [inline]
Definition at line 629 of file IndexMessages.pb.h.
References indexing_duration_.
void aitools::invertedindex::Header::InitAsDefaultInstance () [private]
Definition at line 601 of file IndexMessages.pb.cc.
bool aitools::invertedindex::Header::IsInitialized () const
Definition at line 1045 of file IndexMessages.pb.cc.
google::protobuf::int64 aitools::invertedindex::Header::key_count () const [inline]
Definition at line 565 of file IndexMessages.pb.h.
References key_count_.
google::protobuf::int32 aitools::invertedindex::Header::major_version () const [inline]
Definition at line 613 of file IndexMessages.pb.h.
References major_version_.
void aitools::invertedindex::Header::MergeFrom (const Header & from)
Definition at line 1002 of file IndexMessages.pb.cc.
void aitools::invertedindex::Header::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 990 of file IndexMessages.pb.cc.
bool aitools::invertedindex::Header::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 668 of file IndexMessages.pb.cc.
google::protobuf::int32 aitools::invertedindex::Header::minor_version () const [inline]
Definition at line 597 of file IndexMessages.pb.h.
References minor_version_.
inline ::google::protobuf::UnknownFieldSet* aitools::invertedindex::Header::mutable_unknown_fields () [inline]
Definition at line 264 of file IndexMessages.pb.h.
References _unknown_fields_.
std::string * aitools::invertedindex::Header::mutable_value_class_name () [inline]
Definition at line 671 of file IndexMessages.pb.h.
References _default_value_class_name_, _set_bit(), and value_class_name_.
Header * aitools::invertedindex::Header::New () const
Definition at line 645 of file IndexMessages.pb.cc.
Header& aitools::invertedindex::Header::operator= (const Header & from) [inline]
Definition at line 255 of file IndexMessages.pb.h.
References CopyFrom().
google::protobuf::int64 aitools::invertedindex::Header::payload () const [inline]
Definition at line 549 of file IndexMessages.pb.h.
References payload_.
aitools::invertedindex::Configuration_Sorting aitools::invertedindex::Header::postlist_sorting () const [inline]
Definition at line 687 of file IndexMessages.pb.h.
References postlist_sorting_.
void aitools::invertedindex::Header::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 807 of file IndexMessages.pb.cc.
google::protobuf::uint8 * aitools::invertedindex::Header::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 866 of file IndexMessages.pb.cc.
void aitools::invertedindex::Header::set_indexing_duration (::google::protobuf::int32 value) [inline]
Definition at line 632 of file IndexMessages.pb.h.
References _set_bit(), and indexing_duration_.
void aitools::invertedindex::Header::set_key_count (::google::protobuf::int64 value) [inline]
Definition at line 568 of file IndexMessages.pb.h.
References _set_bit(), and key_count_.
void aitools::invertedindex::Header::set_major_version (::google::protobuf::int32 value) [inline]
Definition at line 616 of file IndexMessages.pb.h.
References _set_bit(), and major_version_.
void aitools::invertedindex::Header::set_minor_version (::google::protobuf::int32 value) [inline]
Definition at line 600 of file IndexMessages.pb.h.
References _set_bit(), and minor_version_.
void aitools::invertedindex::Header::set_payload (::google::protobuf::int64 value) [inline]
Definition at line 552 of file IndexMessages.pb.h.
References _set_bit(), and payload_.
void aitools::invertedindex::Header::set_postlist_sorting (::aitools::invertedindex::Configuration_Sorting value) [inline]
Definition at line 690 of file IndexMessages.pb.h.
References _set_bit(), aitools::invertedindex::Configuration_Sorting_IsValid(), and postlist_sorting_.
void aitools::invertedindex::Header::set_value_class_name (const char * value, size_t size) [inline]
Definition at line 664 of file IndexMessages.pb.h.
References _default_value_class_name_, _set_bit(), and value_class_name_.
void aitools::invertedindex::Header::set_value_class_name (const char * value) [inline]
Definition at line 657 of file IndexMessages.pb.h.
References _default_value_class_name_, _set_bit(), and value_class_name_.
void aitools::invertedindex::Header::set_value_class_name (const ::std::string & value) [inline]
Definition at line 650 of file IndexMessages.pb.h.
References _default_value_class_name_, _set_bit(), and value_class_name_.
void aitools::invertedindex::Header::set_value_count (::google::protobuf::int64 value) [inline]
Definition at line 584 of file IndexMessages.pb.h.
References _set_bit(), and value_count_.
void aitools::invertedindex::Header::SetCachedSize (int size) const [inline, private]
Definition at line 292 of file IndexMessages.pb.h.
References _cached_size_.
void aitools::invertedindex::Header::SharedCtor () [private]
Definition at line 609 of file IndexMessages.pb.cc.
Referenced by Header().
void aitools::invertedindex::Header::SharedDtor () [private]
Definition at line 626 of file IndexMessages.pb.cc.
void aitools::invertedindex::Header::Swap (Header * other)
Definition at line 1050 of file IndexMessages.pb.cc.
const ::google::protobuf::UnknownFieldSet& aitools::invertedindex::Header::unknown_fields () const [inline]
Definition at line 260 of file IndexMessages.pb.h.
References _unknown_fields_.
Referenced by ByteSize().
const ::std::string & aitools::invertedindex::Header::value_class_name () const [inline]
Definition at line 647 of file IndexMessages.pb.h.
References value_class_name_.
google::protobuf::int64 aitools::invertedindex::Header::value_count () const [inline]
Definition at line 581 of file IndexMessages.pb.h.
References value_count_.
Friends And Related Function Documentation
void protobuf_AddDesc_IndexMessages_2eproto () [friend]
void protobuf_AssignDesc_IndexMessages_2eproto () [friend]
void protobuf_ShutdownFile_IndexMessages_2eproto () [friend]
Member Data Documentation
int aitools::invertedindex::Header::_cached_size_ [mutable, private]
Definition at line 362 of file IndexMessages.pb.h.
Referenced by GetCachedSize(), and SetCachedSize().
const ::std::string aitools::invertedindex::Header::_default_value_class_name_ [static, private]
Definition at line 371 of file IndexMessages.pb.h.
Referenced by clear_value_class_name(), descriptor(), mutable_value_class_name(), and set_value_class_name().
::google::protobuf::uint32 aitools::invertedindex::Header::_has_bits_[(8+31)/32] [private]
Definition at line 377 of file IndexMessages.pb.h.
Referenced by _clear_bit(), _has_bit(), and _set_bit().
::google::protobuf::UnknownFieldSet aitools::invertedindex::Header::_unknown_fields_ [private]
Definition at line 361 of file IndexMessages.pb.h.
Referenced by mutable_unknown_fields(), and unknown_fields().
Header * aitools::invertedindex::Header::default_instance_ = NULL [static, private]
Definition at line 391 of file IndexMessages.pb.h.
Referenced by descriptor().
::google::protobuf::int32 aitools::invertedindex::Header::indexing_duration_ [private]
Definition at line 369 of file IndexMessages.pb.h.
Referenced by clear_indexing_duration(), indexing_duration(), and set_indexing_duration().
::google::protobuf::int64 aitools::invertedindex::Header::key_count_ [private]
Definition at line 365 of file IndexMessages.pb.h.
Referenced by clear_key_count(), key_count(), and set_key_count().
const int aitools::invertedindex::Header::kIndexingDurationFieldNumber = 6 [static]
Definition at line 339 of file IndexMessages.pb.h.
const int aitools::invertedindex::Header::kKeyCountFieldNumber = 2 [static]
Definition at line 311 of file IndexMessages.pb.h.
const int aitools::invertedindex::Header::kMajorVersionFieldNumber = 5 [static]
Definition at line 332 of file IndexMessages.pb.h.
const int aitools::invertedindex::Header::kMinorVersionFieldNumber = 4 [static]
Definition at line 325 of file IndexMessages.pb.h.
const int aitools::invertedindex::Header::kPayloadFieldNumber = 1 [static]
Definition at line 304 of file IndexMessages.pb.h.
const int aitools::invertedindex::Header::kPostlistSortingFieldNumber = 8 [static]
Definition at line 356 of file IndexMessages.pb.h.
const int aitools::invertedindex::Header::kValueClassNameFieldNumber = 7 [static]
Definition at line 346 of file IndexMessages.pb.h.
const int aitools::invertedindex::Header::kValueCountFieldNumber = 3 [static]
Definition at line 318 of file IndexMessages.pb.h.
::google::protobuf::int32 aitools::invertedindex::Header::major_version_ [private]
Definition at line 368 of file IndexMessages.pb.h.
Referenced by clear_major_version(), major_version(), and set_major_version().
::google::protobuf::int32 aitools::invertedindex::Header::minor_version_ [private]
Definition at line 367 of file IndexMessages.pb.h.
Referenced by clear_minor_version(), minor_version(), and set_minor_version().
::google::protobuf::int64 aitools::invertedindex::Header::payload_ [private]
Definition at line 364 of file IndexMessages.pb.h.
Referenced by clear_payload(), payload(), and set_payload().
int aitools::invertedindex::Header::postlist_sorting_ [private]
Definition at line 372 of file IndexMessages.pb.h.
Referenced by clear_postlist_sorting(), postlist_sorting(), and set_postlist_sorting().
::std::string* aitools::invertedindex::Header::value_class_name_ [private]
Definition at line 370 of file IndexMessages.pb.h.
Referenced by clear_value_class_name(), descriptor(), mutable_value_class_name(), set_value_class_name(), and value_class_name().
::google::protobuf::int64 aitools::invertedindex::Header::value_count_ [private]
Definition at line 366 of file IndexMessages.pb.h.
Referenced by clear_value_count(), set_value_count(), and value_count().
The documentation for this class was generated from the following files:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/generated/IndexMessages.pb.h
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/generated/IndexMessages.pb.cc