aitools::invertedindex::PostlistWriter Class Reference
aitools::invertedindex::PostlistWriter Class Reference
#include <PostlistWriter.hpp>
Public Types
typedef boost::shared_ptr
< PostlistWriter > SharedPointer
Public Member Functions
PostlistWriter ()
PostlistWriter (const bfs::path &path) throw (std::invalid_argument)
~PostlistWriter ()
void close ()
bool is_open () const
void open (const bfs::path &path) throw (std::runtime_error, std::invalid_argument)
void write (Iterator::SharedPointer iterator)
const bfs::path & path () const
bool ready () const
uint64_t tell ()
Private Attributes
FILE * file_
bfs::path path_
Detailed Description
A class to write postlists into a file on disk.
Author:
martin.trenkmann@uni-weimar.de
Created on Jun 22, 2008
Id
PostlistWriter.hpp,v 1.7 2010/05/11 23:41:08 trenkman Exp
Definition at line 25 of file PostlistWriter.hpp.
Member Typedef Documentation
typedef boost::shared_ptr<PostlistWriter> aitools::invertedindex::PostlistWriter::SharedPointer
Definition at line 29 of file PostlistWriter.hpp.
Constructor & Destructor Documentation
aitools::invertedindex::PostlistWriter::PostlistWriter ()
The default constructor.
Definition at line 4 of file PostlistWriter.cpp.
aitools::invertedindex::PostlistWriter::PostlistWriter (const bfs::path & path) throw (std::invalid_argument)
The explicit constructor.
Definition at line 8 of file PostlistWriter.cpp.
aitools::invertedindex::PostlistWriter::~PostlistWriter ()
The destructor.
Definition at line 15 of file PostlistWriter.cpp.
Member Function Documentation
void aitools::invertedindex::PostlistWriter::close ()
Definition at line 21 of file PostlistWriter.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
bool aitools::invertedindex::PostlistWriter::is_open () const
Definition at line 32 of file PostlistWriter.cpp.
void aitools::invertedindex::PostlistWriter::open (const bfs::path & path) throw (std::runtime_error, std::invalid_argument)
Definition at line 38 of file PostlistWriter.cpp.
const bfs::path & aitools::invertedindex::PostlistWriter::path () const
Definition at line 50 of file PostlistWriter.cpp.
bool aitools::invertedindex::PostlistWriter::ready () const
Definition at line 77 of file PostlistWriter.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
uint64_t aitools::invertedindex::PostlistWriter::tell ()
Definition at line 83 of file PostlistWriter.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
void aitools::invertedindex::PostlistWriter::write (Iterator::SharedPointer iterator)
Definition at line 56 of file PostlistWriter.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and write_postlist().
Member Data Documentation
FILE* aitools::invertedindex::PostlistWriter::file_ [private]
Definition at line 67 of file PostlistWriter.hpp.
bfs::path aitools::invertedindex::PostlistWriter::path_ [private]
Definition at line 68 of file PostlistWriter.hpp.
The documentation for this class was generated from the following files:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/writer/PostlistWriter.hpp
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/writer/PostlistWriter.cpp