aitools::invertedindex::Postlist< Value > Class Template Reference
aitools::invertedindex::Postlist< Value > Class Template Reference
#include <Postlist.hpp>
Public Member Functions
Postlist ()
Postlist (const Iterator::SharedPointer &iterator)
Postlist (const Postlist &postlist)
~Postlist ()
void info (std::ostream &os) const
bool is_empty () const
bool is_paged () const
Iterator::SharedPointer & iterator ()
size_t length () const
bool next (Value &value)
Postlist & operator= (const Postlist &postlist)
Postlist & operator= (const Iterator::SharedPointer &iterator)
size_t payload () const
void reset ()
Private Attributes
Iterator::SharedPointer iterator_
Detailed Description
template<typename Value>
class aitools::invertedindex::Postlist< Value >
A class template of a typed read-only postlist.
Author:
martin.trenkmann@uni-weimar.de
Created on Jun 22, 2008
Id
Postlist.hpp,v 1.34 2010/05/11 23:41:08 trenkman Exp
Definition at line 24 of file Postlist.hpp.
Constructor & Destructor Documentation
template<typename Value > aitools::invertedindex::Postlist< Value >::Postlist () [inline]
Definition at line 67 of file Postlist.hpp.
template<typename Value > aitools::invertedindex::Postlist< Value >::Postlist (const Iterator::SharedPointer & iterator) [inline]
Definition at line 72 of file Postlist.hpp.
template<typename Value > aitools::invertedindex::Postlist< Value >::Postlist (const Postlist< Value > & postlist) [inline]
Definition at line 79 of file Postlist.hpp.
References aitools::invertedindex::Postlist< Value >::iterator_.
template<typename Value > aitools::invertedindex::Postlist< Value >::~Postlist () [inline]
Definition at line 86 of file Postlist.hpp.
Member Function Documentation
template<typename Value > void aitools::invertedindex::Postlist< Value >::info (std::ostream & os) const [inline]
Definition at line 91 of file Postlist.hpp.
References aitools::invertedindex::Postlist< Value >::iterator_.
template<typename Value > bool aitools::invertedindex::Postlist< Value >::is_empty () const [inline]
Definition at line 101 of file Postlist.hpp.
References aitools::invertedindex::Postlist< Value >::iterator_.
template<typename Value > bool aitools::invertedindex::Postlist< Value >::is_paged () const [inline]
Definition at line 108 of file Postlist.hpp.
References aitools::invertedindex::Postlist< Value >::iterator_.
template<typename Value > Iterator::SharedPointer & aitools::invertedindex::Postlist< Value >::iterator () [inline]
Definition at line 115 of file Postlist.hpp.
References aitools::invertedindex::Postlist< Value >::iterator_.
Referenced by aitools::invertedindex::ExternalMergeSort::merge(), and aitools::invertedindex::InternalIntroSort::sort().
template<typename Value > size_t aitools::invertedindex::Postlist< Value >::length () const [inline]
Definition at line 122 of file Postlist.hpp.
References aitools::invertedindex::Postlist< Value >::iterator_.
Referenced by aitools::invertedindex::ExternalMergeSort::partition(), and aitools::invertedindex::InternalIntroSort::sort().
template<typename Value > bool aitools::invertedindex::Postlist< Value >::next (Value & value) [inline]
Definition at line 129 of file Postlist.hpp.
References aitools::invertedindex::Postlist< Value >::iterator_, and aitools::invertedindex::Value::wrap().
Referenced by aitools::invertedindex::ExternalMergeSort::partition(), and aitools::invertedindex::InternalIntroSort::sort().
template<typename Value > Postlist< Value > & aitools::invertedindex::Postlist< Value >::operator= (const Iterator::SharedPointer & iterator) [inline]
Definition at line 148 of file Postlist.hpp.
References aitools::invertedindex::Postlist< Value >::iterator_.
template<typename Value > Postlist< Value > & aitools::invertedindex::Postlist< Value >::operator= (const Postlist< Value > & postlist) [inline]
Definition at line 139 of file Postlist.hpp.
References aitools::invertedindex::Postlist< Value >::iterator_.
template<typename Value > size_t aitools::invertedindex::Postlist< Value >::payload () const [inline]
Definition at line 157 of file Postlist.hpp.
References aitools::invertedindex::Postlist< Value >::iterator_.
Referenced by aitools::invertedindex::ExternalMergeSort::partition(), aitools::invertedindex::PostlistSorter::sort(), and aitools::invertedindex::ExternalMergeSort::sort().
template<typename Value > void aitools::invertedindex::Postlist< Value >::reset () [inline]
Definition at line 164 of file Postlist.hpp.
References aitools::invertedindex::Postlist< Value >::iterator_.
Member Data Documentation
template<typename Value> Iterator::SharedPointer aitools::invertedindex::Postlist< Value >::iterator_ [private]
Definition at line 60 of file Postlist.hpp.
Referenced by aitools::invertedindex::Postlist< Value >::info(), aitools::invertedindex::Postlist< Value >::is_empty(), aitools::invertedindex::Postlist< Value >::is_paged(), aitools::invertedindex::Postlist< Value >::iterator(), aitools::invertedindex::Postlist< Value >::length(), aitools::invertedindex::Postlist< Value >::next(), aitools::invertedindex::Postlist< Value >::operator=(), aitools::invertedindex::Postlist< Value >::payload(), aitools::invertedindex::Postlist< Value >::Postlist(), and aitools::invertedindex::Postlist< Value >::reset().
The documentation for this class was generated from the following file:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/core/Postlist.hpp