de::aitools::aq::invertedindex::core::Properties Class Reference
de::aitools::aq::invertedindex::core::Properties Class Reference
Classes
class PropertiesImpl
Public Member Functions
long getKeyCount ()
long getTotalSize ()
long getValueCount ()
ValueSorting getValueSorting ()
String getValueType ()
int getVersionNumber ()
PrintStream printTo (PrintStream stream)
Protected Member Functions
Properties ()
Protected Attributes
PropertiesImpl impl
Detailed Description
Author:
martin.trenkmann@uni-weimar.de
Version:
Id
Properties.java,v 1.1 2011/02/16 04:41:23 trenkman Exp
Definition at line 14 of file Properties.java.
Constructor & Destructor Documentation
de::aitools::aq::invertedindex::core::Properties::Properties () [inline, protected]
Definition at line 26 of file Properties.java.
References impl.
Member Function Documentation
long de::aitools::aq::invertedindex::core::Properties::getKeyCount () [inline]
Returns the number of unique keys known by the index instance, that has returned this properties object. This number is equal to the number of postlists stored in this index.
Returns:
the size of the index' vocabulary, which is the number of unique keys
Definition at line 39 of file Properties.java.
References impl.
Referenced by printTo().
long de::aitools::aq::invertedindex::core::Properties::getTotalSize () [inline]
The total size in bytes of all values, indexed by the index instance, that has returned this properties object.
Returns:
the size in bytes of the index' payload
Definition at line 49 of file Properties.java.
References impl.
Referenced by printTo().
long de::aitools::aq::invertedindex::core::Properties::getValueCount () [inline]
Returns the total number of values indexed by the index instance, that has returned this properties object.
Returns:
the number of indexed values
Definition at line 59 of file Properties.java.
References impl.
Referenced by printTo().
ValueSorting de::aitools::aq::invertedindex::core::Properties::getValueSorting () [inline]
Returns the sorting of the postlist's values as specified in Configuration#setValueSorting(ValueSorting).
Returns:
the value sorting mode
Definition at line 69 of file Properties.java.
References impl.
Referenced by printTo().
String de::aitools::aq::invertedindex::core::Properties::getValueType () [inline]
A string that represents the native value type of the index instance, that has returned this properties object.
Returns:
a string with the native value type
Definition at line 79 of file Properties.java.
References impl.
Referenced by printTo().
int de::aitools::aq::invertedindex::core::Properties::getVersionNumber () [inline]
Returns the internal version number of the this library.
Returns:
a number that encodes the version of this library
Definition at line 88 of file Properties.java.
References impl.
Referenced by printTo().
PrintStream de::aitools::aq::invertedindex::core::Properties::printTo (PrintStream stream) [inline]
Prints the content of this object in a human-readable form to the given PrintStream.
Parameters:
stream the stream to print to
Returns:
the stream instance itself
Definition at line 99 of file Properties.java.
References getKeyCount(), getTotalSize(), getValueCount(), getValueSorting(), getValueType(), and getVersionNumber().
Referenced by de::aitools::aq::invertedindex::usage::UsingManagedIndexer::main(), and de::aitools::aq::invertedindex::usage::UsingIndexer::main().
Member Data Documentation
PropertiesImpl de::aitools::aq::invertedindex::core::Properties::impl [protected]
Definition at line 109 of file Properties.java.
Referenced by getKeyCount(), getTotalSize(), getValueCount(), getValueSorting(), getValueType(), getVersionNumber(), de::aitools::aq::invertedindex::core::Indexer< V extends Value >::index(), de::aitools::aq::invertedindex::core::Searcher< V extends Value >::open(), and Properties().
The documentation for this class was generated from the following file:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex2-java/src/de/aitools/aq/invertedindex/core/Properties.java