aitools::invertedindex::JNIGateway Class Reference
aitools::invertedindex::JNIGateway Class Reference
#include <JNIGateway.hpp>
Static Public Member Functions
static void copy_string (JNIEnv *env, jstring jstr, std::string &cstr)
static Builder::shared_pointer create_builder (JNIEnv *env, jstring jclazz) throw (std::invalid_argument)
static Searcher::SharedPointer create_searcher (JNIEnv *env, jstring jclazz) throw (std::invalid_argument)
static void delete_builder (jint oid)
static void delete_searcher (jint oid)
static void delete_iterator (jint oid)
static Builder::shared_pointer & get_builder (jint oid) throw (std::invalid_argument)
static Searcher::SharedPointer & get_searcher (jint oid) throw (std::invalid_argument)
static Iterator::SharedPointer & get_iterator (jint oid) throw (std::invalid_argument)
static jint put_builder (const Builder::shared_pointer &builder)
static jint put_searcher (const Searcher::SharedPointer &searcher)
static jint put_iterator (const Iterator::SharedPointer &iterator)
Static Public Attributes
static const char * java_exception
Private Types
typedef
std::tr1::unordered_map< jint,
Builder::shared_pointer > BuilderMap
typedef
std::tr1::unordered_map< jint,
Searcher::SharedPointer > SearcherMap
typedef
std::tr1::unordered_map< jint,
Iterator::SharedPointer > IteratorMap
Private Member Functions
JNIGateway ()
JNIGateway (const JNIGateway &gateway)
JNIGateway & operator= (const JNIGateway &gateway)
Static Private Attributes
static BuilderMap builders
static SearcherMap searchers
static IteratorMap iterators
static boost::mutex mutex
Detailed Description
Author:
martin.trenkmann@uni-weimar.de
Created on Jun 22, 2008
Id
JNIGateway.hpp,v 1.10 2010/05/11 23:41:08 trenkman Exp
Definition at line 23 of file JNIGateway.hpp.
Member Typedef Documentation
typedef std::tr1::unordered_map<jint, Builder::shared_pointer> aitools::invertedindex::JNIGateway::BuilderMap [private]
Definition at line 27 of file JNIGateway.hpp.
typedef std::tr1::unordered_map<jint, Iterator::SharedPointer> aitools::invertedindex::JNIGateway::IteratorMap [private]
Definition at line 29 of file JNIGateway.hpp.
typedef std::tr1::unordered_map<jint, Searcher::SharedPointer> aitools::invertedindex::JNIGateway::SearcherMap [private]
Definition at line 28 of file JNIGateway.hpp.
Constructor & Destructor Documentation
aitools::invertedindex::JNIGateway::JNIGateway () [private]
aitools::invertedindex::JNIGateway::JNIGateway (const JNIGateway & gateway) [private]
Member Function Documentation
void JNIGateway::copy_string (JNIEnv * env, jstring jstr, std::string & cstr) [static]
Definition at line 25 of file JNIGateway.cpp.
References JNINativeInterface_::GetStringUTFChars().
Builder::shared_pointer JNIGateway::create_builder (JNIEnv * env, jstring jclazz) throw (std::invalid_argument) [static]
Definition at line 34 of file JNIGateway.cpp.
References aitools::invertedindex::Exception::throw_invalid_argument().
Searcher::SharedPointer JNIGateway::create_searcher (JNIEnv * env, jstring jclazz) throw (std::invalid_argument) [static]
Definition at line 134 of file JNIGateway.cpp.
References aitools::invertedindex::Exception::throw_invalid_argument().
void JNIGateway::delete_builder (jint oid) [static]
Definition at line 234 of file JNIGateway.cpp.
References builders, and mutex.
void JNIGateway::delete_iterator (jint oid) [static]
Definition at line 248 of file JNIGateway.cpp.
References iterators, and mutex.
void JNIGateway::delete_searcher (jint oid) [static]
Definition at line 241 of file JNIGateway.cpp.
References mutex, and searchers.
Builder::shared_pointer & JNIGateway::get_builder (jint oid) throw (std::invalid_argument) [static]
Definition at line 255 of file JNIGateway.cpp.
References aitools::invertedindex::Exception::throw_invalid_argument().
Iterator::SharedPointer & JNIGateway::get_iterator (jint oid) throw (std::invalid_argument) [static]
Definition at line 279 of file JNIGateway.cpp.
References aitools::invertedindex::Exception::throw_invalid_argument().
Searcher::SharedPointer & JNIGateway::get_searcher (jint oid) throw (std::invalid_argument) [static]
Definition at line 267 of file JNIGateway.cpp.
References aitools::invertedindex::Exception::throw_invalid_argument().
JNIGateway& aitools::invertedindex::JNIGateway::operator= (const JNIGateway & gateway) [private]
jint JNIGateway::put_builder (const Builder::shared_pointer & builder) [static]
Definition at line 291 of file JNIGateway.cpp.
References builders, and mutex.
jint JNIGateway::put_iterator (const Iterator::SharedPointer & iterator) [static]
Definition at line 325 of file JNIGateway.cpp.
References iterators, and mutex.
jint JNIGateway::put_searcher (const Searcher::SharedPointer & searcher) [static]
Definition at line 308 of file JNIGateway.cpp.
References mutex, and searchers.
Member Data Documentation
JNIGateway::BuilderMap JNIGateway::builders [static, private]
Definition at line 41 of file JNIGateway.hpp.
Referenced by delete_builder(), and put_builder().
JNIGateway::IteratorMap JNIGateway::iterators [static, private]
Definition at line 43 of file JNIGateway.hpp.
Referenced by delete_iterator(), and put_iterator().
const char * JNIGateway::java_exception [static]
Definition at line 48 of file JNIGateway.hpp.
boost::mutex JNIGateway::mutex [static, private]
Definition at line 44 of file JNIGateway.hpp.
Referenced by delete_builder(), delete_iterator(), delete_searcher(), put_builder(), put_iterator(), and put_searcher().
JNIGateway::SearcherMap JNIGateway::searchers [static, private]
Definition at line 42 of file JNIGateway.hpp.
Referenced by delete_searcher(), and put_searcher().
The documentation for this class was generated from the following files:
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/jni/JNIGateway.hpp
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/jni/JNIGateway.cpp