aitools::value::quadruple< T1, T2, T3, T4 > Class Template Reference
aitools::value::quadruple< T1, T2, T3, T4 > Class Template Reference
#include <quadruple.hpp>
Public Types
typedef T1 e1_type
typedef T2 e2_type
typedef T3 e3_type
typedef T4 e4_type
Public Member Functions
quadruple ()
quadruple (const e1_type &e1, const e2_type &e2, const e3_type &e3, const e4_type &e4)
quadruple (const quadruple &rhs)
~quadruple ()
e1_type & e1 ()
e2_type & e2 ()
e3_type & e3 ()
e4_type & e4 ()
const e1_type & e1 () const
const e2_type & e2 () const
const e3_type & e3 () const
const e4_type & e4 () const
void set_e1 (const e1_type &e1)
void set_e2 (const e2_type &e2)
void set_e3 (const e3_type &e3)
void set_e4 (const e4_type &e4)
void set (const e1_type &e1, const e2_type &e2, const e3_type &e3, const e4_type &e4)
Private Attributes
e1_type e1_
e2_type e2_
e3_type e3_
e4_type e4_
Detailed Description
template<typename T1, typename T2, typename T3, typename T4>
class aitools::value::quadruple< T1, T2, T3, T4 >
Definition at line 10 of file quadruple.hpp.
Member Typedef Documentation
template<typename T1, typename T2, typename T3, typename T4> typedef T1 aitools::value::quadruple< T1, T2, T3, T4 >::e1_type
Definition at line 14 of file quadruple.hpp.
template<typename T1, typename T2, typename T3, typename T4> typedef T2 aitools::value::quadruple< T1, T2, T3, T4 >::e2_type
Definition at line 15 of file quadruple.hpp.
template<typename T1, typename T2, typename T3, typename T4> typedef T3 aitools::value::quadruple< T1, T2, T3, T4 >::e3_type
Definition at line 16 of file quadruple.hpp.
template<typename T1, typename T2, typename T3, typename T4> typedef T4 aitools::value::quadruple< T1, T2, T3, T4 >::e4_type
Definition at line 17 of file quadruple.hpp.
Constructor & Destructor Documentation
template<typename T1, typename T2, typename T3, typename T4> aitools::value::quadruple< T1, T2, T3, T4 >::quadruple () [inline]
Definition at line 21 of file quadruple.hpp.
template<typename T1, typename T2, typename T3, typename T4> aitools::value::quadruple< T1, T2, T3, T4 >::quadruple (const e1_type & e1, const e2_type & e2, const e3_type & e3, const e4_type & e4) [inline]
Definition at line 28 of file quadruple.hpp.
template<typename T1, typename T2, typename T3, typename T4> aitools::value::quadruple< T1, T2, T3, T4 >::quadruple (const quadruple< T1, T2, T3, T4 > & rhs) [inline]
Definition at line 36 of file quadruple.hpp.
template<typename T1, typename T2, typename T3, typename T4> aitools::value::quadruple< T1, T2, T3, T4 >::~quadruple () [inline]
Definition at line 43 of file quadruple.hpp.
Member Function Documentation
template<typename T1, typename T2, typename T3, typename T4> const e1_type& aitools::value::quadruple< T1, T2, T3, T4 >::e1 () const [inline]
Definition at line 70 of file quadruple.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e1_.
template<typename T1, typename T2, typename T3, typename T4> e1_type& aitools::value::quadruple< T1, T2, T3, T4 >::e1 () [inline]
Definition at line 46 of file quadruple.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e1_.
Referenced by aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::copy_from(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::copy_to(), aitools::generator< value::quadruple< T1, T2, T3, T4 > >::numbered(), aitools::value::operator==(), aitools::value::operator>(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::parse_from(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::print_to(), aitools::generator< value::quadruple< T1, T2, T3, T4 > >::randomized(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::read_from(), aitools::value::quadruple< T1, T2, T3, T4 >::set(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::size_of(), and aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::write_to().
template<typename T1, typename T2, typename T3, typename T4> const e2_type& aitools::value::quadruple< T1, T2, T3, T4 >::e2 () const [inline]
Definition at line 76 of file quadruple.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e2_.
template<typename T1, typename T2, typename T3, typename T4> e2_type& aitools::value::quadruple< T1, T2, T3, T4 >::e2 () [inline]
Definition at line 52 of file quadruple.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e2_.
Referenced by aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::copy_from(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::copy_to(), aitools::generator< value::quadruple< T1, T2, T3, T4 > >::numbered(), aitools::value::operator==(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::parse_from(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::print_to(), aitools::generator< value::quadruple< T1, T2, T3, T4 > >::randomized(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::read_from(), aitools::value::quadruple< T1, T2, T3, T4 >::set(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::size_of(), and aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::write_to().
template<typename T1, typename T2, typename T3, typename T4> const e3_type& aitools::value::quadruple< T1, T2, T3, T4 >::e3 () const [inline]
Definition at line 82 of file quadruple.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e3_.
template<typename T1, typename T2, typename T3, typename T4> e3_type& aitools::value::quadruple< T1, T2, T3, T4 >::e3 () [inline]
Definition at line 58 of file quadruple.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e3_.
Referenced by aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::copy_from(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::copy_to(), aitools::generator< value::quadruple< T1, T2, T3, T4 > >::numbered(), aitools::value::operator==(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::parse_from(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::print_to(), aitools::generator< value::quadruple< T1, T2, T3, T4 > >::randomized(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::read_from(), aitools::value::quadruple< T1, T2, T3, T4 >::set(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::size_of(), and aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::write_to().
template<typename T1, typename T2, typename T3, typename T4> const e4_type& aitools::value::quadruple< T1, T2, T3, T4 >::e4 () const [inline]
Definition at line 88 of file quadruple.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e4_.
template<typename T1, typename T2, typename T3, typename T4> e4_type& aitools::value::quadruple< T1, T2, T3, T4 >::e4 () [inline]
Definition at line 64 of file quadruple.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e4_.
Referenced by aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::copy_from(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::copy_to(), aitools::generator< value::quadruple< T1, T2, T3, T4 > >::numbered(), aitools::value::operator==(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::parse_from(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::print_to(), aitools::generator< value::quadruple< T1, T2, T3, T4 > >::randomized(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::read_from(), aitools::value::quadruple< T1, T2, T3, T4 >::set(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::size_of(), and aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::write_to().
template<typename T1, typename T2, typename T3, typename T4> void aitools::value::quadruple< T1, T2, T3, T4 >::set (const e1_type & e1, const e2_type & e2, const e3_type & e3, const e4_type & e4) [inline]
Definition at line 118 of file quadruple.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e1(), aitools::value::quadruple< T1, T2, T3, T4 >::e1_, aitools::value::quadruple< T1, T2, T3, T4 >::e2(), aitools::value::quadruple< T1, T2, T3, T4 >::e2_, aitools::value::quadruple< T1, T2, T3, T4 >::e3(), aitools::value::quadruple< T1, T2, T3, T4 >::e3_, aitools::value::quadruple< T1, T2, T3, T4 >::e4(), and aitools::value::quadruple< T1, T2, T3, T4 >::e4_.
template<typename T1, typename T2, typename T3, typename T4> void aitools::value::quadruple< T1, T2, T3, T4 >::set_e1 (const e1_type & e1) [inline]
Definition at line 94 of file quadruple.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e1_.
template<typename T1, typename T2, typename T3, typename T4> void aitools::value::quadruple< T1, T2, T3, T4 >::set_e2 (const e2_type & e2) [inline]
Definition at line 100 of file quadruple.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e2_.
template<typename T1, typename T2, typename T3, typename T4> void aitools::value::quadruple< T1, T2, T3, T4 >::set_e3 (const e3_type & e3) [inline]
Definition at line 106 of file quadruple.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e3_.
template<typename T1, typename T2, typename T3, typename T4> void aitools::value::quadruple< T1, T2, T3, T4 >::set_e4 (const e4_type & e4) [inline]
Definition at line 112 of file quadruple.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e4_.
Member Data Documentation
template<typename T1, typename T2, typename T3, typename T4> e1_type aitools::value::quadruple< T1, T2, T3, T4 >::e1_ [private]
Definition at line 129 of file quadruple.hpp.
Referenced by aitools::value::quadruple< T1, T2, T3, T4 >::e1(), aitools::value::quadruple< T1, T2, T3, T4 >::set(), and aitools::value::quadruple< T1, T2, T3, T4 >::set_e1().
template<typename T1, typename T2, typename T3, typename T4> e2_type aitools::value::quadruple< T1, T2, T3, T4 >::e2_ [private]
Definition at line 130 of file quadruple.hpp.
Referenced by aitools::value::quadruple< T1, T2, T3, T4 >::e2(), aitools::value::quadruple< T1, T2, T3, T4 >::set(), and aitools::value::quadruple< T1, T2, T3, T4 >::set_e2().
template<typename T1, typename T2, typename T3, typename T4> e3_type aitools::value::quadruple< T1, T2, T3, T4 >::e3_ [private]
Definition at line 131 of file quadruple.hpp.
Referenced by aitools::value::quadruple< T1, T2, T3, T4 >::e3(), aitools::value::quadruple< T1, T2, T3, T4 >::set(), and aitools::value::quadruple< T1, T2, T3, T4 >::set_e3().
template<typename T1, typename T2, typename T3, typename T4> e4_type aitools::value::quadruple< T1, T2, T3, T4 >::e4_ [private]
Definition at line 132 of file quadruple.hpp.
Referenced by aitools::value::quadruple< T1, T2, T3, T4 >::e4(), aitools::value::quadruple< T1, T2, T3, T4 >::set(), and aitools::value::quadruple< T1, T2, T3, T4 >::set_e4().
The documentation for this class was generated from the following file:
include/value/quadruple.hpp