aitools::value::triple< T1, T2, T3 > Class Template Reference
aitools::value::triple< T1, T2, T3 > Class Template Reference
#include <triple.hpp>
Public Types
typedef T1 e1_type
typedef T2 e2_type
typedef T3 e3_type
Public Member Functions
triple ()
triple (const e1_type &e1, const e2_type &e2, const e3_type &e3)
triple (const triple &rhs)
~triple ()
e1_type & e1 ()
e2_type & e2 ()
e3_type & e3 ()
const e1_type & e1 () const
const e2_type & e2 () const
const e3_type & e3 () const
void set_e1 (const e1_type &e1)
void set_e2 (const e2_type &e2)
void set_e3 (const e3_type &e3)
void set (const e1_type &e1, const e2_type &e2, const e3_type &e3)
Private Attributes
e1_type e1_
e2_type e2_
e3_type e3_
Detailed Description
template<typename T1, typename T2, typename T3>
class aitools::value::triple< T1, T2, T3 >
Definition at line 10 of file triple.hpp.
Member Typedef Documentation
template<typename T1, typename T2, typename T3> typedef T1 aitools::value::triple< T1, T2, T3 >::e1_type
Definition at line 14 of file triple.hpp.
template<typename T1, typename T2, typename T3> typedef T2 aitools::value::triple< T1, T2, T3 >::e2_type
Definition at line 15 of file triple.hpp.
template<typename T1, typename T2, typename T3> typedef T3 aitools::value::triple< T1, T2, T3 >::e3_type
Definition at line 16 of file triple.hpp.
Constructor & Destructor Documentation
template<typename T1, typename T2, typename T3> aitools::value::triple< T1, T2, T3 >::triple () [inline]
Definition at line 20 of file triple.hpp.
template<typename T1, typename T2, typename T3> aitools::value::triple< T1, T2, T3 >::triple (const e1_type & e1, const e2_type & e2, const e3_type & e3) [inline]
Definition at line 26 of file triple.hpp.
template<typename T1, typename T2, typename T3> aitools::value::triple< T1, T2, T3 >::triple (const triple< T1, T2, T3 > & rhs) [inline]
Definition at line 32 of file triple.hpp.
template<typename T1, typename T2, typename T3> aitools::value::triple< T1, T2, T3 >::~triple () [inline]
Definition at line 38 of file triple.hpp.
Member Function Documentation
template<typename T1, typename T2, typename T3> const e1_type& aitools::value::triple< T1, T2, T3 >::e1 () const [inline]
Definition at line 59 of file triple.hpp.
References aitools::value::triple< T1, T2, T3 >::e1_.
template<typename T1, typename T2, typename T3> e1_type& aitools::value::triple< T1, T2, T3 >::e1 () [inline]
Definition at line 41 of file triple.hpp.
References aitools::value::triple< T1, T2, T3 >::e1_.
Referenced by aitools::value::value_traits< triple< T1, T2, T3 > >::copy_from(), aitools::value::value_traits< triple< T1, T2, T3 > >::copy_to(), aitools::generator< value::triple< T1, T2, T3 > >::numbered(), aitools::value::operator==(), aitools::value::operator>(), aitools::value::value_traits< triple< T1, T2, T3 > >::parse_from(), aitools::value::value_traits< triple< T1, T2, T3 > >::print_to(), aitools::generator< value::triple< T1, T2, T3 > >::randomized(), aitools::value::value_traits< triple< T1, T2, T3 > >::read_from(), aitools::value::triple< T1, T2, T3 >::set(), aitools::value::value_traits< triple< T1, T2, T3 > >::size_of(), and aitools::value::value_traits< triple< T1, T2, T3 > >::write_to().
template<typename T1, typename T2, typename T3> const e2_type& aitools::value::triple< T1, T2, T3 >::e2 () const [inline]
Definition at line 65 of file triple.hpp.
References aitools::value::triple< T1, T2, T3 >::e2_.
template<typename T1, typename T2, typename T3> e2_type& aitools::value::triple< T1, T2, T3 >::e2 () [inline]
Definition at line 47 of file triple.hpp.
References aitools::value::triple< T1, T2, T3 >::e2_.
Referenced by aitools::value::value_traits< triple< T1, T2, T3 > >::copy_from(), aitools::value::value_traits< triple< T1, T2, T3 > >::copy_to(), aitools::generator< value::triple< T1, T2, T3 > >::numbered(), aitools::value::operator==(), aitools::value::value_traits< triple< T1, T2, T3 > >::parse_from(), aitools::value::value_traits< triple< T1, T2, T3 > >::print_to(), aitools::generator< value::triple< T1, T2, T3 > >::randomized(), aitools::value::value_traits< triple< T1, T2, T3 > >::read_from(), aitools::value::triple< T1, T2, T3 >::set(), aitools::value::value_traits< triple< T1, T2, T3 > >::size_of(), and aitools::value::value_traits< triple< T1, T2, T3 > >::write_to().
template<typename T1, typename T2, typename T3> const e3_type& aitools::value::triple< T1, T2, T3 >::e3 () const [inline]
Definition at line 71 of file triple.hpp.
References aitools::value::triple< T1, T2, T3 >::e3_.
template<typename T1, typename T2, typename T3> e3_type& aitools::value::triple< T1, T2, T3 >::e3 () [inline]
Definition at line 53 of file triple.hpp.
References aitools::value::triple< T1, T2, T3 >::e3_.
Referenced by aitools::value::value_traits< triple< T1, T2, T3 > >::copy_from(), aitools::value::value_traits< triple< T1, T2, T3 > >::copy_to(), aitools::generator< value::triple< T1, T2, T3 > >::numbered(), aitools::value::operator==(), aitools::value::value_traits< triple< T1, T2, T3 > >::parse_from(), aitools::value::value_traits< triple< T1, T2, T3 > >::print_to(), aitools::generator< value::triple< T1, T2, T3 > >::randomized(), aitools::value::value_traits< triple< T1, T2, T3 > >::read_from(), aitools::value::triple< T1, T2, T3 >::set(), aitools::value::value_traits< triple< T1, T2, T3 > >::size_of(), and aitools::value::value_traits< triple< T1, T2, T3 > >::write_to().
template<typename T1, typename T2, typename T3> void aitools::value::triple< T1, T2, T3 >::set (const e1_type & e1, const e2_type & e2, const e3_type & e3) [inline]
Definition at line 95 of file triple.hpp.
References aitools::value::triple< T1, T2, T3 >::e1(), aitools::value::triple< T1, T2, T3 >::e1_, aitools::value::triple< T1, T2, T3 >::e2(), aitools::value::triple< T1, T2, T3 >::e2_, aitools::value::triple< T1, T2, T3 >::e3(), and aitools::value::triple< T1, T2, T3 >::e3_.
template<typename T1, typename T2, typename T3> void aitools::value::triple< T1, T2, T3 >::set_e1 (const e1_type & e1) [inline]
Definition at line 77 of file triple.hpp.
References aitools::value::triple< T1, T2, T3 >::e1_.
template<typename T1, typename T2, typename T3> void aitools::value::triple< T1, T2, T3 >::set_e2 (const e2_type & e2) [inline]
Definition at line 83 of file triple.hpp.
References aitools::value::triple< T1, T2, T3 >::e2_.
template<typename T1, typename T2, typename T3> void aitools::value::triple< T1, T2, T3 >::set_e3 (const e3_type & e3) [inline]
Definition at line 89 of file triple.hpp.
References aitools::value::triple< T1, T2, T3 >::e3_.
Member Data Documentation
template<typename T1, typename T2, typename T3> e1_type aitools::value::triple< T1, T2, T3 >::e1_ [private]
Definition at line 104 of file triple.hpp.
Referenced by aitools::value::triple< T1, T2, T3 >::e1(), aitools::value::triple< T1, T2, T3 >::set(), and aitools::value::triple< T1, T2, T3 >::set_e1().
template<typename T1, typename T2, typename T3> e2_type aitools::value::triple< T1, T2, T3 >::e2_ [private]
Definition at line 105 of file triple.hpp.
Referenced by aitools::value::triple< T1, T2, T3 >::e2(), aitools::value::triple< T1, T2, T3 >::set(), and aitools::value::triple< T1, T2, T3 >::set_e2().
template<typename T1, typename T2, typename T3> e3_type aitools::value::triple< T1, T2, T3 >::e3_ [private]
Definition at line 106 of file triple.hpp.
Referenced by aitools::value::triple< T1, T2, T3 >::e3(), aitools::value::triple< T1, T2, T3 >::set(), and aitools::value::triple< T1, T2, T3 >::set_e3().
The documentation for this class was generated from the following file:
include/value/triple.hpp