aitools::value::pair< T1, T2 > Class Template Reference
aitools::value::pair< T1, T2 > Class Template Reference
#include <pair.hpp>
Public Types
typedef std::pair< T1, T2 > base_type
typedef base_type::first_type e1_type
typedef base_type::second_type e2_type
Public Member Functions
pair ()
pair (const e1_type &e1, const e2_type &e2)
pair (const pair &rhs)
~pair ()
e1_type & e1 ()
e2_type & e2 ()
const e1_type & e1 () const
const e2_type & e2 () const
void set_e1 (const e1_type &e1)
void set_e2 (const e2_type &e2)
void set (const e1_type &e1, const e2_type &e2)
Detailed Description
template<typename T1, typename T2>
class aitools::value::pair< T1, T2 >
Definition at line 12 of file pair.hpp.
Member Typedef Documentation
template<typename T1, typename T2> typedef std::pair<T1, T2> aitools::value::pair< T1, T2 >::base_type
Definition at line 16 of file pair.hpp.
template<typename T1, typename T2> typedef base_type::first_type aitools::value::pair< T1, T2 >::e1_type
Definition at line 17 of file pair.hpp.
template<typename T1, typename T2> typedef base_type::second_type aitools::value::pair< T1, T2 >::e2_type
Definition at line 18 of file pair.hpp.
Constructor & Destructor Documentation
template<typename T1, typename T2> aitools::value::pair< T1, T2 >::pair () [inline]
Definition at line 22 of file pair.hpp.
template<typename T1, typename T2> aitools::value::pair< T1, T2 >::pair (const e1_type & e1, const e2_type & e2) [inline]
Definition at line 26 of file pair.hpp.
template<typename T1, typename T2> aitools::value::pair< T1, T2 >::pair (const pair< T1, T2 > & rhs) [inline]
Definition at line 30 of file pair.hpp.
template<typename T1, typename T2> aitools::value::pair< T1, T2 >::~pair () [inline]
Definition at line 34 of file pair.hpp.
Member Function Documentation
template<typename T1, typename T2> const e1_type& aitools::value::pair< T1, T2 >::e1 () const [inline]
Definition at line 49 of file pair.hpp.
template<typename T1, typename T2> e1_type& aitools::value::pair< T1, T2 >::e1 () [inline]
Definition at line 37 of file pair.hpp.
Referenced by aitools::value::value_traits< pair< T1, T2 > >::copy_from(), aitools::value::value_traits< pair< T1, T2 > >::copy_to(), aitools::bighashmap::core::internal_map< T >::find(), aitools::bighashmap::core::external_map< T >::find(), aitools::generator< value::pair< T1, T2 > >::numbered(), aitools::value::operator==(), aitools::value::operator>(), aitools::value::value_traits< pair< T1, T2 > >::parse_from(), aitools::value::value_traits< pair< T1, T2 > >::print_to(), aitools::generator< value::pair< T1, T2 > >::randomized(), aitools::value::value_traits< pair< T1, T2 > >::read_from(), aitools::value::pair< T1, T2 >::set(), aitools::value::value_traits< pair< T1, T2 > >::size_of(), and aitools::value::value_traits< pair< T1, T2 > >::write_to().
template<typename T1, typename T2> const e2_type& aitools::value::pair< T1, T2 >::e2 () const [inline]
Definition at line 55 of file pair.hpp.
template<typename T1, typename T2> e2_type& aitools::value::pair< T1, T2 >::e2 () [inline]
Definition at line 43 of file pair.hpp.
Referenced by aitools::bighashmap::core::builder< T >::build_hashtable(), aitools::value::value_traits< pair< T1, T2 > >::copy_from(), aitools::value::value_traits< pair< T1, T2 > >::copy_to(), aitools::bighashmap::core::internal_map< T >::find(), aitools::bighashmap::core::external_map< T >::find(), aitools::generator< value::pair< T1, T2 > >::numbered(), aitools::value::operator==(), aitools::value::value_traits< pair< T1, T2 > >::parse_from(), aitools::value::value_traits< pair< T1, T2 > >::print_to(), aitools::generator< value::pair< T1, T2 > >::randomized(), aitools::value::value_traits< pair< T1, T2 > >::read_from(), aitools::value::pair< T1, T2 >::set(), aitools::value::value_traits< pair< T1, T2 > >::size_of(), and aitools::value::value_traits< pair< T1, T2 > >::write_to().
template<typename T1, typename T2> void aitools::value::pair< T1, T2 >::set (const e1_type & e1, const e2_type & e2) [inline]
Definition at line 73 of file pair.hpp.
References aitools::value::pair< T1, T2 >::e1(), and aitools::value::pair< T1, T2 >::e2().
template<typename T1, typename T2> void aitools::value::pair< T1, T2 >::set_e1 (const e1_type & e1) [inline]
Definition at line 61 of file pair.hpp.
Referenced by aitools::bighashmap::core::builder< T >::build_hashtable().
template<typename T1, typename T2> void aitools::value::pair< T1, T2 >::set_e2 (const e2_type & e2) [inline]
Definition at line 67 of file pair.hpp.
The documentation for this class was generated from the following file:
include/value/pair.hpp