aitools::bighashmap::core::cmph_map< T > Class Template Reference
aitools::bighashmap::core::cmph_map< T > Class Template Reference
#include <cmph_map.hpp>
Public Types
typedef std::string key_type
typedef T value_type
typedef uint32_t checksum_type
Public Member Functions
cmph_map (const bfs::path &mph_file)
virtual ~cmph_map ()
virtual bool find (const key_type &key, value_type &value)=0
uint32_t size () const
Protected Member Functions
uint32_t hash (const std::string &key)
Private Attributes
cmph_t * mphf_
Detailed Description
template<typename T>
class aitools::bighashmap::core::cmph_map< T >
Author:
martin.trenkmann@uni-weimar.de
Version:
Id
cmph_map.hpp,v 1.2 2011/09/21 01:00:50 trenkman Exp
Definition at line 25 of file cmph_map.hpp.
Member Typedef Documentation
template<typename T> typedef uint32_t aitools::bighashmap::core::cmph_map< T >::checksum_type
Reimplemented in aitools::bighashmap::core::external_map< T >, and aitools::bighashmap::core::internal_map< T >.
Definition at line 31 of file cmph_map.hpp.
template<typename T> typedef std::string aitools::bighashmap::core::cmph_map< T >::key_type
Reimplemented in aitools::bighashmap::core::external_map< T >, and aitools::bighashmap::core::internal_map< T >.
Definition at line 29 of file cmph_map.hpp.
template<typename T> typedef T aitools::bighashmap::core::cmph_map< T >::value_type
Reimplemented in aitools::bighashmap::core::external_map< T >, and aitools::bighashmap::core::internal_map< T >.
Definition at line 30 of file cmph_map.hpp.
Constructor & Destructor Documentation
template<typename T> aitools::bighashmap::core::cmph_map< T >::cmph_map (const bfs::path & mph_file) [inline]
Definition at line 35 of file cmph_map.hpp.
References aitools::util::fclose(), aitools::util::fopen(), aitools::bighashmap::core::cmph_map< T >::mphf_, and aitools::util::throw_runtime_error().
template<typename T> virtual aitools::bighashmap::core::cmph_map< T >::~cmph_map () [inline, virtual]
Definition at line 47 of file cmph_map.hpp.
References aitools::bighashmap::core::cmph_map< T >::mphf_.
Member Function Documentation
template<typename T> virtual bool aitools::bighashmap::core::cmph_map< T >::find (const key_type & key, value_type & value) [pure virtual]
Implemented in aitools::bighashmap::core::external_map< T >, and aitools::bighashmap::core::internal_map< T >.
template<typename T> uint32_t aitools::bighashmap::core::cmph_map< T >::hash (const std::string & key) [inline, protected]
Definition at line 66 of file cmph_map.hpp.
References aitools::bighashmap::core::cmph_map< T >::mphf_, and aitools::bighashmap::core::cmph_map< T >::size().
Referenced by aitools::bighashmap::core::internal_map< T >::find(), and aitools::bighashmap::core::external_map< T >::find().
template<typename T> uint32_t aitools::bighashmap::core::cmph_map< T >::size () const [inline]
Definition at line 58 of file cmph_map.hpp.
References aitools::bighashmap::core::cmph_map< T >::mphf_.
Referenced by aitools::bighashmap::core::cmph_map< T >::hash(), and aitools::bighashmap::core::internal_map< T >::internal_map().
Member Data Documentation
template<typename T> cmph_t* aitools::bighashmap::core::cmph_map< T >::mphf_ [private]
Definition at line 75 of file cmph_map.hpp.
Referenced by aitools::bighashmap::core::cmph_map< T >::cmph_map(), aitools::bighashmap::core::cmph_map< T >::hash(), aitools::bighashmap::core::cmph_map< T >::size(), and aitools::bighashmap::core::cmph_map< T >::~cmph_map().
The documentation for this class was generated from the following file:
include/core/cmph_map.hpp