src/jna/functions.cpp File Reference
src/jna/functions.cpp File Reference
#include "jna/functions.hpp"
#include "jna/constant_size_types.hpp"
Functions
const char * bhm_build (int type_id, const char *src_dir, const char *dst_dir)
raw_big_hash_map * bhm_open (int type_id, const char *idx_file, aitools::util::memory_type memory)
bool bhm_find (raw_big_hash_map *bhm, const char *key, char *value)
int64_t bhm_size (raw_big_hash_map *bhm)
void bhm_close (raw_big_hash_map *bhm)
Function Documentation
const char* bhm_build (int type_id, const char * src_dir, const char * dst_dir)
Definition at line 10 of file functions.cpp.
References aitools::util::log_error().
void bhm_close (raw_big_hash_map * bhm)
Definition at line 234 of file functions.cpp.
bool bhm_find (raw_big_hash_map * bhm, const char * key, char * value)
Definition at line 220 of file functions.cpp.
References aitools::bighashmap::core::raw_big_hash_map::find().
raw_big_hash_map* bhm_open (int type_id, const char * idx_file, aitools::util::memory_type memory)
Definition at line 115 of file functions.cpp.
References aitools::util::log_error().
int64_t bhm_size (raw_big_hash_map * bhm)
Definition at line 227 of file functions.cpp.
References aitools::bighashmap::core::raw_big_hash_map::size().