/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/jni/IndexSearcher.java.cpp File Reference
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/jni/IndexSearcher.java.cpp File Reference
#include "IndexSearcher.java.h"
#include <jni.h>
#include "JNIGateway.hpp"
Functions
JNIEXPORT jint JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natInstance (JNIEnv *env, jobject jsearcher, jstring jclazz)
JNIEXPORT jbyteArray JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natInit (JNIEnv *env, jobject jsearcher, jint oid, jbyteArray jconfig)
JNIEXPORT jintArray JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natGetQuantile (JNIEnv *env, jobject jsearcher, jint oid, jstring jkey)
JNIEXPORT jlong JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natGetFrequency (JNIEnv *env, jobject jsearcher, jint oid, jstring jkey)
JNIEXPORT jint JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natSearchL (JNIEnv *env, jobject jsearcher, jint oid, jstring jkey, jint length)
JNIEXPORT jint JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natSearchO (JNIEnv *env, jobject jsearcher, jint oid, jstring jkey, jint order)
JNIEXPORT void JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natDelete (JNIEnv *env, jobject jsearcher, jint oid)
Function Documentation
JNIEXPORT void JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natDelete (JNIEnv * env, jobject jsearcher, jint oid)
Definition at line 171 of file IndexSearcher.java.cpp.
JNIEXPORT jlong JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natGetFrequency (JNIEnv * env, jobject jsearcher, jint oid, jstring jkey)
Definition at line 103 of file IndexSearcher.java.cpp.
References aitools::invertedindex::Vocabulary::end(), and aitools::invertedindex::Vocabulary::find().
JNIEXPORT jintArray JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natGetQuantile (JNIEnv * env, jobject jsearcher, jint oid, jstring jkey)
Definition at line 78 of file IndexSearcher.java.cpp.
JNIEXPORT jbyteArray JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natInit (JNIEnv * env, jobject jsearcher, jint oid, jbyteArray jconfig)
Definition at line 44 of file IndexSearcher.java.cpp.
References JNINativeInterface_::GetByteArrayElements(), and aitools::util::throw_invalid_argument().
JNIEXPORT jint JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natInstance (JNIEnv * env, jobject jsearcher, jstring jclazz)
Definition at line 23 of file IndexSearcher.java.cpp.
JNIEXPORT jint JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natSearchL (JNIEnv * env, jobject jsearcher, jint oid, jstring jkey, jint length)
Definition at line 126 of file IndexSearcher.java.cpp.
JNIEXPORT jint JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natSearchO (JNIEnv * env, jobject jsearcher, jint oid, jstring jkey, jint order)
Definition at line 148 of file IndexSearcher.java.cpp.