/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/jni/IndexSearcher.java.h File Reference
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/src/jni/IndexSearcher.java.h File Reference
#include <jni.h>
Functions
JNIEXPORT jint JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natInstance (JNIEnv *, jobject, jstring)
JNIEXPORT jbyteArray JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natInit (JNIEnv *, jobject, jint, jbyteArray)
JNIEXPORT jintArray JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natGetQuantile (JNIEnv *, jobject, jint, jstring)
JNIEXPORT jlong JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natGetFrequency (JNIEnv *, jobject, jint, jstring)
JNIEXPORT jint JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natSearchL (JNIEnv *, jobject, jint, jstring, jint)
JNIEXPORT jint JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natSearchO (JNIEnv *, jobject, jint, jstring, jint)
JNIEXPORT void JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natDelete (JNIEnv *, jobject, jint)
Function Documentation
JNIEXPORT void JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natDelete (JNIEnv * , jobject , jint)
Definition at line 171 of file IndexSearcher.java.cpp.
JNIEXPORT jlong JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natGetFrequency (JNIEnv * , jobject , jint , jstring)
Definition at line 103 of file IndexSearcher.java.cpp.
References aitools::invertedindex::Vocabulary::end(), and aitools::invertedindex::Vocabulary::find().
JNIEXPORT jintArray JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natGetQuantile (JNIEnv * , jobject , jint , jstring)
Definition at line 78 of file IndexSearcher.java.cpp.
JNIEXPORT jbyteArray JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natInit (JNIEnv * , jobject , jint , jbyteArray)
Definition at line 44 of file IndexSearcher.java.cpp.
References JNINativeInterface_::GetByteArrayElements(), and aitools::util::throw_invalid_argument().
JNIEXPORT jint JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natInstance (JNIEnv * , jobject , jstring)
Definition at line 23 of file IndexSearcher.java.cpp.
JNIEXPORT jint JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natSearchL (JNIEnv * , jobject , jint , jstring , jint)
Definition at line 126 of file IndexSearcher.java.cpp.
JNIEXPORT jint JNICALL Java_de_aitools_aq_invertedindex_core_IndexSearcher_natSearchO (JNIEnv * , jobject , jint , jstring , jint)
Definition at line 148 of file IndexSearcher.java.cpp.