aitools::invertedindex Namespace Reference
aitools::invertedindex Namespace Reference
Classes
class Builder
class ByteBuffer
class Externalizable
class ExternalMergeSort
class GenericRecord
class IndexBuilder
class IndexSearcher
class InternalIntroSort
class Iterator
class MPHashFunction
class NonCopyable
class Postlist
class PostlistBuilder
class PostlistSorter
class Quantile
class Record
class Searcher
class StorageBuilder
class StorageSearcher
class System
struct StaticDescriptorInitializer_IndexMessages_2eproto
class Configuration
class Header
class JNIGateway
class InvertedFileReader
class NGramFileReader
class PostlistReader
class RecordReader
class Checksum
class Converter
class Exception
class Logging
class Timer
class Vocabulary
class Pair
class PairString
class Quadruple
class Single
class SingleString
class StringString
class Triple
class Value
class InvertedFileWriter
class PostlistWriter
Typedefs
typedef Triple< int64_t,
int32_t, int8_t > value_type
typedef Single< int8_t > SingleByte
typedef Single< int16_t > SingleShort
typedef Single< int32_t > SingleInt
typedef Single< int64_t > SingleLong
typedef Single< float > SingleFloat
typedef PairString< int8_t > ByteString
typedef PairString< int16_t > ShortString
typedef PairString< int32_t > IntString
typedef PairString< int64_t > LongString
typedef PairString< float > FloatString
typedef Pair< int16_t, int32_t > ShortInt
typedef Pair< int16_t, int64_t > ShortLong
typedef Pair< int16_t, float > ShortFloat
typedef Pair< int32_t, int32_t > IntInt
typedef Pair< int32_t, int64_t > IntLong
typedef Pair< int32_t, float > IntFloat
typedef Pair< int64_t, int32_t > LongInt
typedef Pair< int64_t, int64_t > LongLong
typedef Pair< int64_t, float > LongFloat
typedef Pair< float, int32_t > FloatInt
typedef Pair< float, int64_t > FloatLong
typedef Pair< float, float > FloatFloat
typedef Triple< int16_t,
int32_t, int32_t > ShortIntInt
typedef Triple< int16_t,
int32_t, float > ShortIntFloat
typedef Triple< int16_t, float,
float > ShortFloatFloat
typedef Triple< int32_t,
int32_t, int32_t > IntIntInt
typedef Triple< int32_t,
int32_t, float > IntIntFloat
typedef Triple< int32_t, float,
float > IntFloatFloat
typedef Triple< int64_t,
int32_t, int32_t > LongIntInt
typedef Triple< int64_t,
int32_t, float > LongIntFloat
typedef Triple< int64_t, float,
float > LongFloatFloat
typedef Triple< float, int32_t,
int32_t > FloatIntInt
typedef Triple< float, int32_t,
float > FloatIntFloat
typedef Triple< float, float,
float > FloatFloatFloat
typedef Quadruple< int32_t,
int32_t, int32_t, int32_t > IntIntIntInt
typedef Quadruple< int64_t,
int64_t, int64_t, int64_t > LongLongLongLong
typedef Quadruple< int64_t,
int64_t, int32_t, int32_t > LongLongIntInt
typedef Quadruple< int64_t,
int64_t, float, float > LongLongFloatFloat
typedef Quadruple< int64_t,
float, int64_t, int32_t > LongFloatLongInt
Enumerations
enum Configuration_InputFormat { Configuration_InputFormat_REAL_INVERTED = 0, Configuration_InputFormat_PSEUDO_INVERTED = 1 }
enum Configuration_Sorting { Configuration_Sorting_DISABLED = 0, Configuration_Sorting_ASCENDING = 1, Configuration_Sorting_DESCENDING = 2 }
Functions
void protobuf_AssignDesc_IndexMessages_2eproto ()
void protobuf_ShutdownFile_IndexMessages_2eproto ()
void protobuf_AddDesc_IndexMessages_2eproto ()
const
::google::protobuf::EnumDescriptor * Configuration_InputFormat_descriptor ()
bool Configuration_InputFormat_IsValid (int value)
const
::google::protobuf::EnumDescriptor * Configuration_Sorting_descriptor ()
bool Configuration_Sorting_IsValid (int value)
const ::std::string & Configuration_InputFormat_Name (Configuration_InputFormat value)
bool Configuration_InputFormat_Parse (const ::std::string &name, Configuration_InputFormat *value)
const ::std::string & Configuration_Sorting_Name (Configuration_Sorting value)
bool Configuration_Sorting_Parse (const ::std::string &name, Configuration_Sorting *value)
void build_index (const bfs::path &input_dir, const bfs::path &index_dir)
void search_index (const bfs::path &index_dir)
void write_inverted_file (const bfs::path &file)
void build_ngram_index (int argc, char *argv[])
Variables
struct
aitools::invertedindex::StaticDescriptorInitializer_IndexMessages_2eproto static_descriptor_initializer_IndexMessages_2eproto_
const Configuration_InputFormat Configuration_InputFormat_InputFormat_MIN = Configuration_InputFormat_REAL_INVERTED
const Configuration_InputFormat Configuration_InputFormat_InputFormat_MAX = Configuration_InputFormat_PSEUDO_INVERTED
const Configuration_Sorting Configuration_Sorting_Sorting_MIN = Configuration_Sorting_DISABLED
const Configuration_Sorting Configuration_Sorting_Sorting_MAX = Configuration_Sorting_DESCENDING
Typedef Documentation
typedef PairString<int8_t> aitools::invertedindex::ByteString
Definition at line 28 of file ValueTypes.hpp.
typedef Pair<float, float> aitools::invertedindex::FloatFloat
Definition at line 45 of file ValueTypes.hpp.
typedef Triple<float, float, float> aitools::invertedindex::FloatFloatFloat
Definition at line 58 of file ValueTypes.hpp.
typedef Pair<float, int32_t> aitools::invertedindex::FloatInt
Definition at line 43 of file ValueTypes.hpp.
typedef Triple<float, int32_t, float> aitools::invertedindex::FloatIntFloat
Definition at line 57 of file ValueTypes.hpp.
typedef Triple<float, int32_t, int32_t> aitools::invertedindex::FloatIntInt
Definition at line 56 of file ValueTypes.hpp.
typedef Pair<float, int64_t> aitools::invertedindex::FloatLong
Definition at line 44 of file ValueTypes.hpp.
typedef PairString<float> aitools::invertedindex::FloatString
Definition at line 32 of file ValueTypes.hpp.
typedef Pair<int32_t, float> aitools::invertedindex::IntFloat
Definition at line 39 of file ValueTypes.hpp.
typedef Triple<int32_t, float, float> aitools::invertedindex::IntFloatFloat
Definition at line 52 of file ValueTypes.hpp.
typedef Pair<int32_t, int32_t> aitools::invertedindex::IntInt
Definition at line 37 of file ValueTypes.hpp.
typedef Triple<int32_t, int32_t, float> aitools::invertedindex::IntIntFloat
Definition at line 51 of file ValueTypes.hpp.
typedef Triple<int32_t, int32_t, int32_t> aitools::invertedindex::IntIntInt
Definition at line 50 of file ValueTypes.hpp.
typedef Quadruple<int32_t, int32_t, int32_t, int32_t> aitools::invertedindex::IntIntIntInt
Definition at line 60 of file ValueTypes.hpp.
typedef Pair<int32_t, int64_t> aitools::invertedindex::IntLong
Definition at line 38 of file ValueTypes.hpp.
typedef PairString<int32_t> aitools::invertedindex::IntString
Definition at line 30 of file ValueTypes.hpp.
typedef Pair<int64_t, float> aitools::invertedindex::LongFloat
Definition at line 42 of file ValueTypes.hpp.
typedef Triple<int64_t, float, float> aitools::invertedindex::LongFloatFloat
Definition at line 55 of file ValueTypes.hpp.
typedef Quadruple<int64_t, float, int64_t, int32_t> aitools::invertedindex::LongFloatLongInt
Definition at line 64 of file ValueTypes.hpp.
typedef Pair<int64_t, int32_t> aitools::invertedindex::LongInt
Definition at line 40 of file ValueTypes.hpp.
typedef Triple<int64_t, int32_t, float> aitools::invertedindex::LongIntFloat
Definition at line 54 of file ValueTypes.hpp.
typedef Triple<int64_t, int32_t, int32_t> aitools::invertedindex::LongIntInt
Definition at line 53 of file ValueTypes.hpp.
typedef Pair<int64_t, int64_t> aitools::invertedindex::LongLong
Definition at line 41 of file ValueTypes.hpp.
typedef Quadruple<int64_t, int64_t, float, float> aitools::invertedindex::LongLongFloatFloat
Definition at line 63 of file ValueTypes.hpp.
typedef Quadruple<int64_t, int64_t, int32_t, int32_t> aitools::invertedindex::LongLongIntInt
Definition at line 62 of file ValueTypes.hpp.
typedef Quadruple<int64_t, int64_t, int64_t, int64_t> aitools::invertedindex::LongLongLongLong
Definition at line 61 of file ValueTypes.hpp.
typedef PairString<int64_t> aitools::invertedindex::LongString
Definition at line 31 of file ValueTypes.hpp.
typedef Pair<int16_t, float> aitools::invertedindex::ShortFloat
Definition at line 36 of file ValueTypes.hpp.
typedef Triple<int16_t, float, float> aitools::invertedindex::ShortFloatFloat
Definition at line 49 of file ValueTypes.hpp.
typedef Pair<int16_t, int32_t> aitools::invertedindex::ShortInt
Definition at line 34 of file ValueTypes.hpp.
typedef Triple<int16_t, int32_t, float> aitools::invertedindex::ShortIntFloat
Definition at line 48 of file ValueTypes.hpp.
typedef Triple<int16_t, int32_t, int32_t> aitools::invertedindex::ShortIntInt
Definition at line 47 of file ValueTypes.hpp.
typedef Pair<int16_t, int64_t> aitools::invertedindex::ShortLong
Definition at line 35 of file ValueTypes.hpp.
typedef PairString<int16_t> aitools::invertedindex::ShortString
Definition at line 29 of file ValueTypes.hpp.
typedef Single<int8_t> aitools::invertedindex::SingleByte
Typedefs of value types that are supported by JNI.
Author:
martin.trenkmann@uni-weimar.de
Version:
Id
ValueTypes.hpp,v 1.5 2011/01/26 22:20:09 trenkman Exp
Definition at line 22 of file ValueTypes.hpp.
typedef Single<float> aitools::invertedindex::SingleFloat
Definition at line 26 of file ValueTypes.hpp.
typedef Single<int32_t> aitools::invertedindex::SingleInt
Definition at line 24 of file ValueTypes.hpp.
typedef Single<int64_t> aitools::invertedindex::SingleLong
Definition at line 25 of file ValueTypes.hpp.
typedef Single<int16_t> aitools::invertedindex::SingleShort
Definition at line 23 of file ValueTypes.hpp.
typedef Triple< int64_t, int32_t, int8_t > aitools::invertedindex::value_type
Definition at line 16 of file NGramFileReader.hpp.
Enumeration Type Documentation
enum aitools::invertedindex::Configuration_InputFormat
Enumerator:
Configuration_InputFormat_REAL_INVERTED
Configuration_InputFormat_PSEUDO_INVERTED
Definition at line 37 of file IndexMessages.pb.h.
enum aitools::invertedindex::Configuration_Sorting
Enumerator:
Configuration_Sorting_DISABLED
Configuration_Sorting_ASCENDING
Configuration_Sorting_DESCENDING
Definition at line 55 of file IndexMessages.pb.h.
Function Documentation
void aitools::invertedindex::build_index (const bfs::path & input_dir, const bfs::path & index_dir)
void aitools::invertedindex::build_ngram_index (int argc, char * argv[])
Definition at line 21 of file ngram_indexing.hpp.
References aitools::invertedindex::IndexBuilder< Value >::build(), aitools::invertedindex::Configuration::DESCENDING, aitools::invertedindex::Configuration::DISABLED, aitools::invertedindex::Logging::error(), aitools::invertedindex::Configuration::PSEUDO_INVERTED, aitools::invertedindex::Configuration::REAL_INVERTED, aitools::invertedindex::Configuration::set_available_memory(), aitools::invertedindex::Configuration::set_index_directory(), aitools::invertedindex::Configuration::set_input_directory(), aitools::invertedindex::Configuration::set_input_format(), and aitools::invertedindex::Configuration::set_postlist_sorting().
Referenced by main().
const ::google::protobuf::EnumDescriptor * aitools::invertedindex::Configuration_InputFormat_descriptor ()
Referenced by Configuration_InputFormat_Name(), Configuration_InputFormat_Parse(), and aitools::invertedindex::Configuration::InputFormat_descriptor().
bool aitools::invertedindex::Configuration_InputFormat_IsValid (int value)
Referenced by aitools::invertedindex::Configuration::InputFormat_IsValid(), and aitools::invertedindex::Configuration::set_input_format().
const ::std::string& aitools::invertedindex::Configuration_InputFormat_Name (Configuration_InputFormat value) [inline]
Definition at line 46 of file IndexMessages.pb.h.
References Configuration_InputFormat_descriptor().
Referenced by aitools::invertedindex::Configuration::InputFormat_Name().
bool aitools::invertedindex::Configuration_InputFormat_Parse (const ::std::string & name, Configuration_InputFormat * value) [inline]
Definition at line 50 of file IndexMessages.pb.h.
References Configuration_InputFormat_descriptor().
Referenced by aitools::invertedindex::Configuration::InputFormat_Parse().
const ::google::protobuf::EnumDescriptor * aitools::invertedindex::Configuration_Sorting_descriptor ()
Referenced by Configuration_Sorting_Name(), Configuration_Sorting_Parse(), and aitools::invertedindex::Configuration::Sorting_descriptor().
bool aitools::invertedindex::Configuration_Sorting_IsValid (int value)
Referenced by aitools::invertedindex::Header::set_postlist_sorting(), aitools::invertedindex::Configuration::set_postlist_sorting(), and aitools::invertedindex::Configuration::Sorting_IsValid().
const ::std::string& aitools::invertedindex::Configuration_Sorting_Name (Configuration_Sorting value) [inline]
Definition at line 65 of file IndexMessages.pb.h.
References Configuration_Sorting_descriptor().
Referenced by aitools::invertedindex::Configuration::Sorting_Name().
bool aitools::invertedindex::Configuration_Sorting_Parse (const ::std::string & name, Configuration_Sorting * value) [inline]
Definition at line 69 of file IndexMessages.pb.h.
References Configuration_Sorting_descriptor().
Referenced by aitools::invertedindex::Configuration::Sorting_Parse().
void aitools::invertedindex::protobuf_AddDesc_IndexMessages_2eproto ()
void aitools::invertedindex::protobuf_AssignDesc_IndexMessages_2eproto ()
void aitools::invertedindex::protobuf_ShutdownFile_IndexMessages_2eproto ()
void aitools::invertedindex::search_index (const bfs::path & index_dir)
void aitools::invertedindex::write_inverted_file (const bfs::path & file)
Variable Documentation
const Configuration_InputFormat aitools::invertedindex::Configuration_InputFormat_InputFormat_MAX = Configuration_InputFormat_PSEUDO_INVERTED
Definition at line 43 of file IndexMessages.pb.h.
const Configuration_InputFormat aitools::invertedindex::Configuration_InputFormat_InputFormat_MIN = Configuration_InputFormat_REAL_INVERTED
Definition at line 42 of file IndexMessages.pb.h.
const Configuration_Sorting aitools::invertedindex::Configuration_Sorting_Sorting_MAX = Configuration_Sorting_DESCENDING
Definition at line 62 of file IndexMessages.pb.h.
const Configuration_Sorting aitools::invertedindex::Configuration_Sorting_Sorting_MIN = Configuration_Sorting_DISABLED
Definition at line 61 of file IndexMessages.pb.h.
struct aitools::invertedindex::StaticDescriptorInitializer_IndexMessages_2eproto aitools::invertedindex::static_descriptor_initializer_IndexMessages_2eproto_