aitools::value Namespace Reference
aitools::value Namespace Reference
Classes
struct mapper< 101 >
struct mapper< 102 >
struct mapper< 103 >
struct mapper< 201 >
struct mapper< 202 >
struct mapper< 203 >
struct mapper< 204 >
struct mapper< 205 >
struct mapper< 206 >
struct mapper< 207 >
struct mapper< 208 >
struct mapper< 209 >
struct mapper< 210 >
struct mapper< 301 >
struct mapper< 302 >
struct mapper< 303 >
struct mapper< 304 >
struct mapper< 305 >
struct mapper< 306 >
struct mapper< 307 >
struct mapper< 308 >
struct mapper< 309 >
struct mapper< 401 >
struct mapper< 402 >
struct mapper< 403 >
struct mapper< 404 >
struct mapper< 405 >
struct mapper< 406 >
struct mapper< 407 >
struct mapper< 408 >
class pair
struct value_traits< pair< T1, T2 > >
class quadruple
struct value_traits< quadruple< T1, T2, T3, T4 > >
class triple
struct value_traits< triple< T1, T2, T3 > >
struct value_traits
Typedefs
typedef double SingleDouble
typedef int32_t SingleInt
typedef int64_t SingleLong
typedef pair< double, double > DoubleDouble
typedef pair< double, int32_t > DoubleInt
typedef pair< double, int64_t > DoubleLong
typedef pair< int32_t, double > IntDouble
typedef pair< int32_t, int32_t > IntInt
typedef pair< int32_t, int64_t > IntLong
typedef pair< int64_t, double > LongDouble
typedef pair< int64_t, int32_t > LongInt
typedef pair< int64_t, int64_t > LongLong
typedef pair< int16_t, int32_t > ShortInt
typedef triple< double, double,
double > DoubleDoubleDouble
typedef triple< double,
int32_t, double > DoubleIntDouble
typedef triple< double,
int32_t, int32_t > DoubleIntInt
typedef triple< int32_t,
double, double > IntDoubleDouble
typedef triple< int32_t,
int32_t, double > IntIntDouble
typedef triple< int32_t,
int32_t, int32_t > IntIntInt
typedef triple< int64_t,
double, double > LongDoubleDouble
typedef triple< int64_t,
int32_t, double > LongIntDouble
typedef triple< int64_t,
int32_t, int32_t > LongIntInt
typedef quadruple< double,
double, int32_t, int32_t > DoubleDoubleIntInt
typedef quadruple< double,
double, int64_t, int64_t > DoubleDoubleLongLong
typedef quadruple< int32_t,
int32_t, double, double > IntIntDoubleDouble
typedef quadruple< int32_t,
int32_t, int64_t, int64_t > IntIntLongLong
typedef quadruple< int64_t,
double, int64_t, int32_t > LongDoubleLongInt
typedef quadruple< int64_t,
int64_t, double, double > LongLongDoubleDouble
typedef quadruple< int64_t,
int64_t, int32_t, int32_t > LongLongIntInt
typedef quadruple< double,
int64_t, int64_t, int32_t > DoubleLongLongInt
Functions
template<typename T1 , typename T2 >
bool operator== (const pair< T1, T2 > &lhs, const pair< T1, T2 > &rhs)
template<typename T1 , typename T2 >
bool operator!= (const pair< T1, T2 > &lhs, const pair< T1, T2 > &rhs)
template<typename T1 , typename T2 >
bool operator< (const pair< T1, T2 > &lhs, const pair< T1, T2 > &rhs)
template<typename T1 , typename T2 >
bool operator> (const pair< T1, T2 > &lhs, const pair< T1, T2 > &rhs)
template<typename T1 , typename T2 >
std::ostream & operator<< (std::ostream &os, const pair< T1, T2 > &value)
template<typename T1 , typename T2 , typename T3 , typename T4 >
bool operator== (const quadruple< T1, T2, T3, T4 > &lhs, const quadruple< T1, T2, T3, T4 > &rhs)
template<typename T1 , typename T2 , typename T3 , typename T4 >
bool operator!= (const quadruple< T1, T2, T3, T4 > &lhs, const quadruple< T1, T2, T3, T4 > &rhs)
template<typename T1 , typename T2 , typename T3 , typename T4 >
bool operator< (const quadruple< T1, T2, T3, T4 > &lhs, const quadruple< T1, T2, T3, T4 > &rhs)
template<typename T1 , typename T2 , typename T3 , typename T4 >
bool operator> (const quadruple< T1, T2, T3, T4 > &lhs, const quadruple< T1, T2, T3, T4 > &rhs)
template<typename T1 , typename T2 , typename T3 , typename T4 >
std::ostream & operator<< (std::ostream &os, const quadruple< T1, T2, T3, T4 > &value)
template<typename T1 , typename T2 , typename T3 >
bool operator== (const triple< T1, T2, T3 > &lhs, const triple< T1, T2, T3 > &rhs)
template<typename T1 , typename T2 , typename T3 >
bool operator!= (const triple< T1, T2, T3 > &lhs, const triple< T1, T2, T3 > &rhs)
template<typename T1 , typename T2 , typename T3 >
bool operator< (const triple< T1, T2, T3 > &lhs, const triple< T1, T2, T3 > &rhs)
template<typename T1 , typename T2 , typename T3 >
bool operator> (const triple< T1, T2, T3 > &lhs, const triple< T1, T2, T3 > &rhs)
template<typename T1 , typename T2 , typename T3 >
std::ostream & operator<< (std::ostream &os, const triple< T1, T2, T3 > &value)
template<typename T >
std::string name_of (T dummy=T())
template<>
std::string name_of (int8_t dummy)
template<>
std::string name_of (int16_t dummy)
template<>
std::string name_of (int32_t dummy)
template<>
std::string name_of (int64_t dummy)
template<>
std::string name_of (uint8_t dummy)
template<>
std::string name_of (uint16_t dummy)
template<>
std::string name_of (uint32_t dummy)
template<>
std::string name_of (uint64_t dummy)
template<>
std::string name_of (float dummy)
template<>
std::string name_of (double dummy)
template<typename T >
bool print_to_os (T value, std::ostream &os)
bool print_to_os (int8_t value, std::ostream &os)
bool print_to_os (uint8_t value, std::ostream &os)
Typedef Documentation
typedef pair<double, double> aitools::value::DoubleDouble
Definition at line 28 of file constant_size_types.hpp.
typedef triple<double, double, double> aitools::value::DoubleDoubleDouble
Definition at line 51 of file constant_size_types.hpp.
typedef quadruple<double, double, int32_t, int32_t> aitools::value::DoubleDoubleIntInt
Definition at line 72 of file constant_size_types.hpp.
typedef quadruple<double, double, int64_t, int64_t> aitools::value::DoubleDoubleLongLong
Definition at line 73 of file constant_size_types.hpp.
typedef pair<double, int32_t> aitools::value::DoubleInt
Definition at line 29 of file constant_size_types.hpp.
typedef triple<double, int32_t, double> aitools::value::DoubleIntDouble
Definition at line 52 of file constant_size_types.hpp.
typedef triple<double, int32_t, int32_t> aitools::value::DoubleIntInt
Definition at line 53 of file constant_size_types.hpp.
typedef pair<double, int64_t> aitools::value::DoubleLong
Definition at line 30 of file constant_size_types.hpp.
typedef quadruple<double, int64_t, int64_t, int32_t> aitools::value::DoubleLongLongInt
Definition at line 80 of file constant_size_types.hpp.
typedef pair<int32_t, double> aitools::value::IntDouble
Definition at line 31 of file constant_size_types.hpp.
typedef triple<int32_t, double, double> aitools::value::IntDoubleDouble
Definition at line 54 of file constant_size_types.hpp.
typedef pair<int32_t, int32_t> aitools::value::IntInt
Definition at line 32 of file constant_size_types.hpp.
typedef triple<int32_t, int32_t, double> aitools::value::IntIntDouble
Definition at line 55 of file constant_size_types.hpp.
typedef quadruple<int32_t, int32_t, double, double> aitools::value::IntIntDoubleDouble
Definition at line 74 of file constant_size_types.hpp.
typedef triple<int32_t, int32_t, int32_t> aitools::value::IntIntInt
Definition at line 56 of file constant_size_types.hpp.
typedef quadruple<int32_t, int32_t, int64_t, int64_t> aitools::value::IntIntLongLong
Definition at line 75 of file constant_size_types.hpp.
typedef pair<int32_t, int64_t> aitools::value::IntLong
Definition at line 33 of file constant_size_types.hpp.
typedef pair<int64_t, double> aitools::value::LongDouble
Definition at line 34 of file constant_size_types.hpp.
typedef triple<int64_t, double, double> aitools::value::LongDoubleDouble
Definition at line 57 of file constant_size_types.hpp.
typedef quadruple<int64_t, double, int64_t, int32_t> aitools::value::LongDoubleLongInt
Definition at line 76 of file constant_size_types.hpp.
typedef pair<int64_t, int32_t> aitools::value::LongInt
Definition at line 35 of file constant_size_types.hpp.
typedef triple<int64_t, int32_t, double> aitools::value::LongIntDouble
Definition at line 58 of file constant_size_types.hpp.
typedef triple<int64_t, int32_t, int32_t> aitools::value::LongIntInt
Definition at line 59 of file constant_size_types.hpp.
typedef pair<int64_t, int64_t> aitools::value::LongLong
Definition at line 36 of file constant_size_types.hpp.
typedef quadruple<int64_t, int64_t, double, double> aitools::value::LongLongDoubleDouble
Definition at line 77 of file constant_size_types.hpp.
typedef quadruple<int64_t, int64_t, int32_t, int32_t> aitools::value::LongLongIntInt
Definition at line 78 of file constant_size_types.hpp.
typedef pair<int16_t, int32_t> aitools::value::ShortInt
Definition at line 37 of file constant_size_types.hpp.
typedef double aitools::value::SingleDouble
Definition at line 16 of file constant_size_types.hpp.
typedef int32_t aitools::value::SingleInt
Definition at line 20 of file constant_size_types.hpp.
typedef int64_t aitools::value::SingleLong
Definition at line 21 of file constant_size_types.hpp.
Function Documentation
template<> std::string aitools::value::name_of (double dummy) [inline]
Definition at line 92 of file value_traits.hpp.
template<> std::string aitools::value::name_of (float dummy) [inline]
Definition at line 85 of file value_traits.hpp.
template<> std::string aitools::value::name_of (uint64_t dummy) [inline]
Definition at line 78 of file value_traits.hpp.
template<> std::string aitools::value::name_of (uint32_t dummy) [inline]
Definition at line 71 of file value_traits.hpp.
template<> std::string aitools::value::name_of (uint16_t dummy) [inline]
Definition at line 64 of file value_traits.hpp.
template<> std::string aitools::value::name_of (uint8_t dummy) [inline]
Definition at line 57 of file value_traits.hpp.
template<> std::string aitools::value::name_of (int64_t dummy) [inline]
Definition at line 50 of file value_traits.hpp.
template<> std::string aitools::value::name_of (int32_t dummy) [inline]
Definition at line 43 of file value_traits.hpp.
template<> std::string aitools::value::name_of (int16_t dummy) [inline]
Definition at line 36 of file value_traits.hpp.
template<> std::string aitools::value::name_of (int8_t dummy) [inline]
Definition at line 29 of file value_traits.hpp.
template<typename T > std::string aitools::value::name_of (T dummy = T()) [inline]
template<typename T1 , typename T2 , typename T3 > bool aitools::value::operator!= (const triple< T1, T2, T3 > & lhs, const triple< T1, T2, T3 > & rhs) [inline]
Definition at line 122 of file triple.hpp.
template<typename T1 , typename T2 , typename T3 , typename T4 > bool aitools::value::operator!= (const quadruple< T1, T2, T3, T4 > & lhs, const quadruple< T1, T2, T3, T4 > & rhs) [inline]
Definition at line 150 of file quadruple.hpp.
template<typename T1 , typename T2 > bool aitools::value::operator!= (const pair< T1, T2 > & lhs, const pair< T1, T2 > & rhs) [inline]
Definition at line 90 of file pair.hpp.
template<typename T1 , typename T2 , typename T3 > bool aitools::value::operator< (const triple< T1, T2, T3 > & lhs, const triple< T1, T2, T3 > & rhs) [inline]
Definition at line 129 of file triple.hpp.
template<typename T1 , typename T2 , typename T3 , typename T4 > bool aitools::value::operator< (const quadruple< T1, T2, T3, T4 > & lhs, const quadruple< T1, T2, T3, T4 > & rhs) [inline]
Definition at line 158 of file quadruple.hpp.
template<typename T1 , typename T2 > bool aitools::value::operator< (const pair< T1, T2 > & lhs, const pair< T1, T2 > & rhs) [inline]
Definition at line 97 of file pair.hpp.
template<typename T1 , typename T2 , typename T3 > std::ostream& aitools::value::operator<< (std::ostream & os, const triple< T1, T2, T3 > & value) [inline]
Definition at line 112 of file triple_traits.hpp.
template<typename T1 , typename T2 , typename T3 , typename T4 > std::ostream& aitools::value::operator<< (std::ostream & os, const quadruple< T1, T2, T3, T4 > & value) [inline]
Definition at line 122 of file quadruple_traits.hpp.
template<typename T1 , typename T2 > std::ostream& aitools::value::operator<< (std::ostream & os, const pair< T1, T2 > & value) [inline]
Definition at line 102 of file pair_traits.hpp.
template<typename T1 , typename T2 , typename T3 > bool aitools::value::operator== (const triple< T1, T2, T3 > & lhs, const triple< T1, T2, T3 > & rhs) [inline]
Definition at line 112 of file triple.hpp.
References aitools::value::triple< T1, T2, T3 >::e1(), aitools::value::triple< T1, T2, T3 >::e2(), and aitools::value::triple< T1, T2, T3 >::e3().
template<typename T1 , typename T2 , typename T3 , typename T4 > bool aitools::value::operator== (const quadruple< T1, T2, T3, T4 > & lhs, const quadruple< T1, T2, T3, T4 > & rhs) [inline]
Definition at line 138 of file quadruple.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e1(), aitools::value::quadruple< T1, T2, T3, T4 >::e2(), aitools::value::quadruple< T1, T2, T3, T4 >::e3(), and aitools::value::quadruple< T1, T2, T3, T4 >::e4().
template<typename T1 , typename T2 > bool aitools::value::operator== (const pair< T1, T2 > & lhs, const pair< T1, T2 > & rhs) [inline]
Definition at line 83 of file pair.hpp.
References aitools::value::pair< T1, T2 >::e1(), and aitools::value::pair< T1, T2 >::e2().
template<typename T1 , typename T2 , typename T3 > bool aitools::value::operator> (const triple< T1, T2, T3 > & lhs, const triple< T1, T2, T3 > & rhs) [inline]
Definition at line 136 of file triple.hpp.
References aitools::value::triple< T1, T2, T3 >::e1().
template<typename T1 , typename T2 , typename T3 , typename T4 > bool aitools::value::operator> (const quadruple< T1, T2, T3, T4 > & lhs, const quadruple< T1, T2, T3, T4 > & rhs) [inline]
Definition at line 166 of file quadruple.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e1().
template<typename T1 , typename T2 > bool aitools::value::operator> (const pair< T1, T2 > & lhs, const pair< T1, T2 > & rhs) [inline]
Definition at line 104 of file pair.hpp.
References aitools::value::pair< T1, T2 >::e1().
bool aitools::value::print_to_os (uint8_t value, std::ostream & os) [inline]
Definition at line 119 of file value_traits.hpp.
bool aitools::value::print_to_os (int8_t value, std::ostream & os) [inline]
Definition at line 111 of file value_traits.hpp.
template<typename T > bool aitools::value::print_to_os (T value, std::ostream & os) [inline]
Definition at line 103 of file value_traits.hpp.
Referenced by aitools::value::value_traits< T >::print_to().