aitools::value::value_traits< quadruple< T1, T2, T3, T4 > > Struct Template Reference
aitools::value::value_traits< quadruple< T1, T2, T3, T4 > > Struct Template Reference
#include <quadruple_traits.hpp>
Public Types
typedef quadruple< T1, T2, T3, T4 > value_type
typedef uint16_t io_size_type
Static Public Member Functions
static size_t size_of (const value_type &quadruple)
static char * copy_to (const value_type &quadruple, char *buffer)
static const char * copy_from (value_type &quadruple, const char *buffer)
static bool write_to (const value_type &quadruple, FILE *file)
static bool read_from (value_type &quadruple, FILE *file)
static bool print_to (const value_type &quadruple, std::ostream &os)
static bool println_to (const value_type &quadruple, std::ostream &os)
static bool parse_from (value_type &quadruple, std::istream &is)
static std::string type_name ()
Detailed Description
template<typename T1, typename T2, typename T3, typename T4>
struct aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >
Definition at line 17 of file quadruple_traits.hpp.
Member Typedef Documentation
template<typename T1 , typename T2 , typename T3 , typename T4 > typedef uint16_t aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::io_size_type
Definition at line 20 of file quadruple_traits.hpp.
template<typename T1 , typename T2 , typename T3 , typename T4 > typedef quadruple<T1, T2, T3, T4> aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::value_type
Definition at line 19 of file quadruple_traits.hpp.
Member Function Documentation
template<typename T1 , typename T2 , typename T3 , typename T4 > static const char* aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::copy_from (value_type & quadruple, const char * buffer) [inline, static]
Definition at line 42 of file quadruple_traits.hpp.
References aitools::value::value_traits< T >::copy_from(), aitools::value::quadruple< T1, T2, T3, T4 >::e1(), aitools::value::quadruple< T1, T2, T3, T4 >::e2(), aitools::value::quadruple< T1, T2, T3, T4 >::e3(), and aitools::value::quadruple< T1, T2, T3, T4 >::e4().
template<typename T1 , typename T2 , typename T3 , typename T4 > static char* aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::copy_to (const value_type & quadruple, char * buffer) [inline, static]
Definition at line 33 of file quadruple_traits.hpp.
References aitools::value::value_traits< T >::copy_to(), aitools::value::quadruple< T1, T2, T3, T4 >::e1(), aitools::value::quadruple< T1, T2, T3, T4 >::e2(), aitools::value::quadruple< T1, T2, T3, T4 >::e3(), and aitools::value::quadruple< T1, T2, T3, T4 >::e4().
template<typename T1 , typename T2 , typename T3 , typename T4 > static bool aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::parse_from (value_type & quadruple, std::istream & is) [inline, static]
Definition at line 91 of file quadruple_traits.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e1(), aitools::value::quadruple< T1, T2, T3, T4 >::e2(), aitools::value::quadruple< T1, T2, T3, T4 >::e3(), aitools::value::quadruple< T1, T2, T3, T4 >::e4(), and aitools::value::value_traits< T >::parse_from().
template<typename T1 , typename T2 , typename T3 , typename T4 > static bool aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::print_to (const value_type & quadruple, std::ostream & os) [inline, static]
Definition at line 71 of file quadruple_traits.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e1(), aitools::value::quadruple< T1, T2, T3, T4 >::e2(), aitools::value::quadruple< T1, T2, T3, T4 >::e3(), aitools::value::quadruple< T1, T2, T3, T4 >::e4(), and aitools::value::value_traits< T >::print_to().
template<typename T1 , typename T2 , typename T3 , typename T4 > static bool aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::println_to (const value_type & quadruple, std::ostream & os) [inline, static]
Definition at line 84 of file quadruple_traits.hpp.
References aitools::value::value_traits< T >::print_to().
template<typename T1 , typename T2 , typename T3 , typename T4 > static bool aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::read_from (value_type & quadruple, FILE * file) [inline, static]
Definition at line 61 of file quadruple_traits.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e1(), aitools::value::quadruple< T1, T2, T3, T4 >::e2(), aitools::value::quadruple< T1, T2, T3, T4 >::e3(), aitools::value::quadruple< T1, T2, T3, T4 >::e4(), and aitools::value::value_traits< T >::read_from().
template<typename T1 , typename T2 , typename T3 , typename T4 > static size_t aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::size_of (const value_type & quadruple) [inline, static]
Definition at line 23 of file quadruple_traits.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e1(), aitools::value::quadruple< T1, T2, T3, T4 >::e2(), aitools::value::quadruple< T1, T2, T3, T4 >::e3(), aitools::value::quadruple< T1, T2, T3, T4 >::e4(), and aitools::value::value_traits< T >::size_of().
template<typename T1 , typename T2 , typename T3 , typename T4 > static std::string aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::type_name () [inline, static]
Definition at line 101 of file quadruple_traits.hpp.
References aitools::value::value_traits< T >::type_name().
template<typename T1 , typename T2 , typename T3 , typename T4 > static bool aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::write_to (const value_type & quadruple, FILE * file) [inline, static]
Definition at line 51 of file quadruple_traits.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e1(), aitools::value::quadruple< T1, T2, T3, T4 >::e2(), aitools::value::quadruple< T1, T2, T3, T4 >::e3(), aitools::value::quadruple< T1, T2, T3, T4 >::e4(), and aitools::value::value_traits< T >::write_to().
The documentation for this struct was generated from the following file:
include/value/quadruple_traits.hpp