aitools::generator< value::quadruple< T1, T2, T3, T4 > > Struct Template Reference
aitools::generator< value::quadruple< T1, T2, T3, T4 > > Struct Template Reference
#include <generator.hpp>
Public Types
typedef value::quadruple< T1,
T2, T3, T4 > value_type
Static Public Member Functions
static void randomized (value_type &value)
static void numbered (value_type &value, size_t number)
Detailed Description
template<typename T1, typename T2, typename T3, typename T4>
struct aitools::generator< value::quadruple< T1, T2, T3, T4 > >
Definition at line 74 of file generator.hpp.
Member Typedef Documentation
template<typename T1 , typename T2 , typename T3 , typename T4 > typedef value::quadruple<T1, T2, T3, T4> aitools::generator< value::quadruple< T1, T2, T3, T4 > >::value_type
Definition at line 76 of file generator.hpp.
Member Function Documentation
template<typename T1 , typename T2 , typename T3 , typename T4 > static void aitools::generator< value::quadruple< T1, T2, T3, T4 > >::numbered (value_type & value, size_t number) [inline, static]
Definition at line 88 of file generator.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e1(), aitools::value::quadruple< T1, T2, T3, T4 >::e2(), aitools::value::quadruple< T1, T2, T3, T4 >::e3(), aitools::value::quadruple< T1, T2, T3, T4 >::e4(), and aitools::generator< T >::numbered().
template<typename T1 , typename T2 , typename T3 , typename T4 > static void aitools::generator< value::quadruple< T1, T2, T3, T4 > >::randomized (value_type & value) [inline, static]
Definition at line 79 of file generator.hpp.
References aitools::value::quadruple< T1, T2, T3, T4 >::e1(), aitools::value::quadruple< T1, T2, T3, T4 >::e2(), aitools::value::quadruple< T1, T2, T3, T4 >::e3(), aitools::value::quadruple< T1, T2, T3, T4 >::e4(), and aitools::generator< T >::randomized().
The documentation for this struct was generated from the following file:
test/generator.hpp