aitools::value::value_traits< T > Struct Template Reference
aitools::value::value_traits< T > Struct Template Reference
#include <value_traits.hpp>
Public Types
typedef boost::enable_if
< boost::is_arithmetic< T >, T >
::type value_type
typedef uint16_t io_size_type
Static Public Member Functions
static size_t size_of (const value_type &value)
static char * copy_to (const value_type &value, char *buffer)
static const char * copy_from (value_type &value, const char *buffer)
static bool write_to (const value_type &value, FILE *file)
static bool read_from (value_type &value, FILE *file)
static bool print_to (const value_type &value, std::ostream &os)
static bool println_to (const value_type &value, std::ostream &os)
static bool parse_from (value_type &value, std::istream &is)
static std::string type_name ()
Detailed Description
template<typename T>
struct aitools::value::value_traits< T >
Definition at line 125 of file value_traits.hpp.
Member Typedef Documentation
template<typename T> typedef uint16_t aitools::value::value_traits< T >::io_size_type
Definition at line 129 of file value_traits.hpp.
template<typename T> typedef boost::enable_if< boost::is_arithmetic<T>, T>::type aitools::value::value_traits< T >::value_type
Definition at line 128 of file value_traits.hpp.
Member Function Documentation
template<typename T> static const char* aitools::value::value_traits< T >::copy_from (value_type & value, const char * buffer) [inline, static]
Definition at line 145 of file value_traits.hpp.
Referenced by aitools::value::value_traits< triple< T1, T2, T3 > >::copy_from(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::copy_from(), aitools::value::value_traits< pair< T1, T2 > >::copy_from(), and aitools::bighashmap::core::internal_map< T >::find().
template<typename T> static char* aitools::value::value_traits< T >::copy_to (const value_type & value, char * buffer) [inline, static]
Definition at line 138 of file value_traits.hpp.
Referenced by aitools::bighashmap::core::builder< T >::build_hashtable(), aitools::value::value_traits< triple< T1, T2, T3 > >::copy_to(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::copy_to(), and aitools::value::value_traits< pair< T1, T2 > >::copy_to().
template<typename T> static bool aitools::value::value_traits< T >::parse_from (value_type & value, std::istream & is) [inline, static]
Definition at line 177 of file value_traits.hpp.
Referenced by aitools::value::value_traits< triple< T1, T2, T3 > >::parse_from(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::parse_from(), and aitools::value::value_traits< pair< T1, T2 > >::parse_from().
template<typename T> static bool aitools::value::value_traits< T >::print_to (const value_type & value, std::ostream & os) [inline, static]
Definition at line 164 of file value_traits.hpp.
References aitools::value::print_to_os().
Referenced by aitools::value::value_traits< triple< T1, T2, T3 > >::print_to(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::print_to(), aitools::value::value_traits< pair< T1, T2 > >::print_to(), aitools::value::value_traits< T >::println_to(), aitools::value::value_traits< triple< T1, T2, T3 > >::println_to(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::println_to(), and aitools::value::value_traits< pair< T1, T2 > >::println_to().
template<typename T> static bool aitools::value::value_traits< T >::println_to (const value_type & value, std::ostream & os) [inline, static]
Definition at line 170 of file value_traits.hpp.
References aitools::value::value_traits< T >::print_to().
template<typename T> static bool aitools::value::value_traits< T >::read_from (value_type & value, FILE * file) [inline, static]
Definition at line 158 of file value_traits.hpp.
References aitools::util::fread().
Referenced by aitools::bighashmap::core::external_map< T >::find(), aitools::value::value_traits< triple< T1, T2, T3 > >::read_from(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::read_from(), and aitools::value::value_traits< pair< T1, T2 > >::read_from().
template<typename T> static size_t aitools::value::value_traits< T >::size_of (const value_type & value) [inline, static]
Definition at line 132 of file value_traits.hpp.
Referenced by aitools::bighashmap::core::builder< T >::build_hashtable(), aitools::bighashmap::core::internal_map< T >::find(), aitools::bighashmap::core::external_map< T >::find(), aitools::bighashmap::core::internal_map< T >::internal_map(), aitools::value::value_traits< triple< T1, T2, T3 > >::size_of(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::size_of(), and aitools::value::value_traits< pair< T1, T2 > >::size_of().
template<typename T> static std::string aitools::value::value_traits< T >::type_name () [inline, static]
Definition at line 183 of file value_traits.hpp.
Referenced by aitools::value::value_traits< triple< T1, T2, T3 > >::type_name(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::type_name(), and aitools::value::value_traits< pair< T1, T2 > >::type_name().
template<typename T> static bool aitools::value::value_traits< T >::write_to (const value_type & value, FILE * file) [inline, static]
Definition at line 152 of file value_traits.hpp.
References aitools::util::fwrite().
Referenced by aitools::value::value_traits< triple< T1, T2, T3 > >::write_to(), aitools::value::value_traits< quadruple< T1, T2, T3, T4 > >::write_to(), and aitools::value::value_traits< pair< T1, T2 > >::write_to().
The documentation for this struct was generated from the following file:
include/value/value_traits.hpp