aitools::generator< value::pair< T1, T2 > > Struct Template Reference
aitools::generator< value::pair< T1, T2 > > Struct Template Reference
#include <generator.hpp>
Public Types
typedef value::pair< T1, T2 > value_type
Static Public Member Functions
static void randomized (value_type &value)
static void numbered (value_type &value, size_t number)
Detailed Description
template<typename T1, typename T2>
struct aitools::generator< value::pair< T1, T2 > >
Definition at line 32 of file generator.hpp.
Member Typedef Documentation
template<typename T1 , typename T2 > typedef value::pair<T1, T2> aitools::generator< value::pair< T1, T2 > >::value_type
Definition at line 34 of file generator.hpp.
Member Function Documentation
template<typename T1 , typename T2 > static void aitools::generator< value::pair< T1, T2 > >::numbered (value_type & value, size_t number) [inline, static]
Definition at line 44 of file generator.hpp.
References aitools::value::pair< T1, T2 >::e1(), aitools::value::pair< T1, T2 >::e2(), and aitools::generator< T >::numbered().
template<typename T1 , typename T2 > static void aitools::generator< value::pair< T1, T2 > >::randomized (value_type & value) [inline, static]
Definition at line 37 of file generator.hpp.
References aitools::value::pair< T1, T2 >::e1(), aitools::value::pair< T1, T2 >::e2(), and aitools::generator< T >::randomized().
The documentation for this struct was generated from the following file:
test/generator.hpp