aitools::value::value_traits< triple< T1, T2, T3 > > Struct Template Reference
aitools::value::value_traits< triple< T1, T2, T3 > > Struct Template Reference
#include <triple_traits.hpp>
Public Types
typedef triple< T1, T2, T3 > value_type
typedef uint16_t io_size_type
Static Public Member Functions
static size_t size_of (const value_type &triple)
static char * copy_to (const value_type &triple, char *buffer)
static const char * copy_from (value_type &triple, const char *buffer)
static bool write_to (const value_type &triple, FILE *file)
static bool read_from (value_type &triple, FILE *file)
static bool print_to (const value_type &triple, std::ostream &os)
static bool println_to (const value_type &triple, std::ostream &os)
static bool parse_from (value_type &triple, std::istream &is)
static std::string type_name ()
Detailed Description
template<typename T1, typename T2, typename T3>
struct aitools::value::value_traits< triple< T1, T2, T3 > >
Definition at line 17 of file triple_traits.hpp.
Member Typedef Documentation
template<typename T1 , typename T2 , typename T3 > typedef uint16_t aitools::value::value_traits< triple< T1, T2, T3 > >::io_size_type
Definition at line 20 of file triple_traits.hpp.
template<typename T1 , typename T2 , typename T3 > typedef triple<T1, T2, T3> aitools::value::value_traits< triple< T1, T2, T3 > >::value_type
Definition at line 19 of file triple_traits.hpp.
Member Function Documentation
template<typename T1 , typename T2 , typename T3 > static const char* aitools::value::value_traits< triple< T1, T2, T3 > >::copy_from (value_type & triple, const char * buffer) [inline, static]
Definition at line 40 of file triple_traits.hpp.
References aitools::value::value_traits< T >::copy_from(), aitools::value::triple< T1, T2, T3 >::e1(), aitools::value::triple< T1, T2, T3 >::e2(), and aitools::value::triple< T1, T2, T3 >::e3().
template<typename T1 , typename T2 , typename T3 > static char* aitools::value::value_traits< triple< T1, T2, T3 > >::copy_to (const value_type & triple, char * buffer) [inline, static]
Definition at line 32 of file triple_traits.hpp.
References aitools::value::value_traits< T >::copy_to(), aitools::value::triple< T1, T2, T3 >::e1(), aitools::value::triple< T1, T2, T3 >::e2(), and aitools::value::triple< T1, T2, T3 >::e3().
template<typename T1 , typename T2 , typename T3 > static bool aitools::value::value_traits< triple< T1, T2, T3 > >::parse_from (value_type & triple, std::istream & is) [inline, static]
Definition at line 84 of file triple_traits.hpp.
References aitools::value::triple< T1, T2, T3 >::e1(), aitools::value::triple< T1, T2, T3 >::e2(), aitools::value::triple< T1, T2, T3 >::e3(), and aitools::value::value_traits< T >::parse_from().
template<typename T1 , typename T2 , typename T3 > static bool aitools::value::value_traits< triple< T1, T2, T3 > >::print_to (const value_type & triple, std::ostream & os) [inline, static]
Definition at line 66 of file triple_traits.hpp.
References aitools::value::triple< T1, T2, T3 >::e1(), aitools::value::triple< T1, T2, T3 >::e2(), aitools::value::triple< T1, T2, T3 >::e3(), and aitools::value::value_traits< T >::print_to().
template<typename T1 , typename T2 , typename T3 > static bool aitools::value::value_traits< triple< T1, T2, T3 > >::println_to (const value_type & triple, std::ostream & os) [inline, static]
Definition at line 77 of file triple_traits.hpp.
References aitools::value::value_traits< T >::print_to().
template<typename T1 , typename T2 , typename T3 > static bool aitools::value::value_traits< triple< T1, T2, T3 > >::read_from (value_type & triple, FILE * file) [inline, static]
Definition at line 57 of file triple_traits.hpp.
References aitools::value::triple< T1, T2, T3 >::e1(), aitools::value::triple< T1, T2, T3 >::e2(), aitools::value::triple< T1, T2, T3 >::e3(), and aitools::value::value_traits< T >::read_from().
template<typename T1 , typename T2 , typename T3 > static size_t aitools::value::value_traits< triple< T1, T2, T3 > >::size_of (const value_type & triple) [inline, static]
Definition at line 23 of file triple_traits.hpp.
References aitools::value::triple< T1, T2, T3 >::e1(), aitools::value::triple< T1, T2, T3 >::e2(), aitools::value::triple< T1, T2, T3 >::e3(), and aitools::value::value_traits< T >::size_of().
template<typename T1 , typename T2 , typename T3 > static std::string aitools::value::value_traits< triple< T1, T2, T3 > >::type_name () [inline, static]
Definition at line 93 of file triple_traits.hpp.
References aitools::value::value_traits< T >::type_name().
template<typename T1 , typename T2 , typename T3 > static bool aitools::value::value_traits< triple< T1, T2, T3 > >::write_to (const value_type & triple, FILE * file) [inline, static]
Definition at line 48 of file triple_traits.hpp.
References aitools::value::triple< T1, T2, T3 >::e1(), aitools::value::triple< T1, T2, T3 >::e2(), aitools::value::triple< T1, T2, T3 >::e3(), and aitools::value::value_traits< T >::write_to().
The documentation for this struct was generated from the following file:
include/value/triple_traits.hpp