aitools::generator< value::triple< T1, T2, T3 > > Struct Template Reference
aitools::generator< value::triple< T1, T2, T3 > > Struct Template Reference
#include <generator.hpp>
Public Types
typedef value::triple< T1, T2, T3 > value_type
Static Public Member Functions
static void randomized (value_type &value)
static void numbered (value_type &value, size_t number)
Detailed Description
template<typename T1, typename T2, typename T3>
struct aitools::generator< value::triple< T1, T2, T3 > >
Definition at line 52 of file generator.hpp.
Member Typedef Documentation
template<typename T1 , typename T2 , typename T3 > typedef value::triple<T1, T2, T3> aitools::generator< value::triple< T1, T2, T3 > >::value_type
Definition at line 54 of file generator.hpp.
Member Function Documentation
template<typename T1 , typename T2 , typename T3 > static void aitools::generator< value::triple< T1, T2, T3 > >::numbered (value_type & value, size_t number) [inline, static]
Definition at line 65 of file generator.hpp.
References aitools::value::triple< T1, T2, T3 >::e1(), aitools::value::triple< T1, T2, T3 >::e2(), aitools::value::triple< T1, T2, T3 >::e3(), and aitools::generator< T >::numbered().
template<typename T1 , typename T2 , typename T3 > static void aitools::generator< value::triple< T1, T2, T3 > >::randomized (value_type & value) [inline, static]
Definition at line 57 of file generator.hpp.
References aitools::value::triple< T1, T2, T3 >::e1(), aitools::value::triple< T1, T2, T3 >::e2(), aitools::value::triple< T1, T2, T3 >::e3(), and aitools::generator< T >::randomized().
The documentation for this struct was generated from the following file:
test/generator.hpp