aitools::generator< T > Struct Template Reference
aitools::generator< T > Struct Template Reference
#include <generator.hpp>
Public Types
typedef T value_type
Static Public Member Functions
static void randomized (value_type &value)
static void numbered (value_type &value, size_t number)
Detailed Description
template<typename T>
struct aitools::generator< T >
Definition at line 14 of file generator.hpp.
Member Typedef Documentation
template<typename T > typedef T aitools::generator< T >::value_type
Definition at line 16 of file generator.hpp.
Member Function Documentation
template<typename T > static void aitools::generator< T >::numbered (value_type & value, size_t number) [inline, static]
Definition at line 25 of file generator.hpp.
Referenced by aitools::generator< value::quadruple< T1, T2, T3, T4 > >::numbered(), aitools::generator< value::triple< T1, T2, T3 > >::numbered(), and aitools::generator< value::pair< T1, T2 > >::numbered().
template<typename T > static void aitools::generator< T >::randomized (value_type & value) [inline, static]
Definition at line 19 of file generator.hpp.
Referenced by aitools::generator< value::quadruple< T1, T2, T3, T4 > >::randomized(), aitools::generator< value::triple< T1, T2, T3 > >::randomized(), and aitools::generator< value::pair< T1, T2 > >::randomized().
The documentation for this struct was generated from the following file:
test/generator.hpp