aitools::value::value_traits< pair< T1, T2 > > Struct Template Reference
aitools::value::value_traits< pair< T1, T2 > > Struct Template Reference
#include <pair_traits.hpp>
Public Types
typedef pair< T1, T2 > value_type
typedef uint16_t io_size_type
Static Public Member Functions
static size_t size_of (const value_type &pair)
static char * copy_to (const value_type &pair, char *buffer)
static const char * copy_from (value_type &pair, const char *buffer)
static bool write_to (const value_type &pair, FILE *file)
static bool read_from (value_type &pair, FILE *file)
static bool print_to (const value_type &pair, std::ostream &os)
static bool println_to (const value_type &pair, std::ostream &os)
static bool parse_from (value_type &pair, std::istream &is)
static std::string type_name ()
Detailed Description
template<typename T1, typename T2>
struct aitools::value::value_traits< pair< T1, T2 > >
Definition at line 17 of file pair_traits.hpp.
Member Typedef Documentation
template<typename T1 , typename T2 > typedef uint16_t aitools::value::value_traits< pair< T1, T2 > >::io_size_type
Definition at line 20 of file pair_traits.hpp.
template<typename T1 , typename T2 > typedef pair<T1, T2> aitools::value::value_traits< pair< T1, T2 > >::value_type
Definition at line 19 of file pair_traits.hpp.
Member Function Documentation
template<typename T1 , typename T2 > static const char* aitools::value::value_traits< pair< T1, T2 > >::copy_from (value_type & pair, const char * buffer) [inline, static]
Definition at line 38 of file pair_traits.hpp.
References aitools::value::value_traits< T >::copy_from(), aitools::value::pair< T1, T2 >::e1(), and aitools::value::pair< T1, T2 >::e2().
template<typename T1 , typename T2 > static char* aitools::value::value_traits< pair< T1, T2 > >::copy_to (const value_type & pair, char * buffer) [inline, static]
Definition at line 31 of file pair_traits.hpp.
References aitools::value::value_traits< T >::copy_to(), aitools::value::pair< T1, T2 >::e1(), and aitools::value::pair< T1, T2 >::e2().
template<typename T1 , typename T2 > static bool aitools::value::value_traits< pair< T1, T2 > >::parse_from (value_type & pair, std::istream & is) [inline, static]
Definition at line 77 of file pair_traits.hpp.
References aitools::value::pair< T1, T2 >::e1(), aitools::value::pair< T1, T2 >::e2(), and aitools::value::value_traits< T >::parse_from().
template<typename T1 , typename T2 > static bool aitools::value::value_traits< pair< T1, T2 > >::print_to (const value_type & pair, std::ostream & os) [inline, static]
Definition at line 61 of file pair_traits.hpp.
References aitools::value::pair< T1, T2 >::e1(), aitools::value::pair< T1, T2 >::e2(), and aitools::value::value_traits< T >::print_to().
template<typename T1 , typename T2 > static bool aitools::value::value_traits< pair< T1, T2 > >::println_to (const value_type & pair, std::ostream & os) [inline, static]
Definition at line 70 of file pair_traits.hpp.
References aitools::value::value_traits< T >::print_to().
template<typename T1 , typename T2 > static bool aitools::value::value_traits< pair< T1, T2 > >::read_from (value_type & pair, FILE * file) [inline, static]
Definition at line 53 of file pair_traits.hpp.
References aitools::value::pair< T1, T2 >::e1(), aitools::value::pair< T1, T2 >::e2(), and aitools::value::value_traits< T >::read_from().
template<typename T1 , typename T2 > static size_t aitools::value::value_traits< pair< T1, T2 > >::size_of (const value_type & pair) [inline, static]
Definition at line 23 of file pair_traits.hpp.
References aitools::value::pair< T1, T2 >::e1(), aitools::value::pair< T1, T2 >::e2(), and aitools::value::value_traits< T >::size_of().
template<typename T1 , typename T2 > static std::string aitools::value::value_traits< pair< T1, T2 > >::type_name () [inline, static]
Definition at line 85 of file pair_traits.hpp.
References aitools::value::value_traits< T >::type_name().
template<typename T1 , typename T2 > static bool aitools::value::value_traits< pair< T1, T2 > >::write_to (const value_type & pair, FILE * file) [inline, static]
Definition at line 45 of file pair_traits.hpp.
References aitools::value::pair< T1, T2 >::e1(), aitools::value::pair< T1, T2 >::e2(), and aitools::value::value_traits< T >::write_to().
The documentation for this struct was generated from the following file:
include/value/pair_traits.hpp