/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/reader/TestInvertedFileReader.cpp File Reference
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/reader/TestInvertedFileReader.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "InvertedFileReader.hpp"
#include "InvertedFileWriter.hpp"
#include "ValueTypes.hpp"
#include "Converter.hpp"
#include "Record.hpp"
#include <cstdlib>
Typedefs
typedef InvertedFileReader
< ShortIntFloat > Reader
typedef InvertedFileWriter
< ShortIntFloat > Writer
Functions
BOOST_AUTO_TEST_SUITE (inverted_file_reader)
BOOST_AUTO_TEST_CASE (explicit_ctor)
BOOST_AUTO_TEST_CASE (read)
BOOST_AUTO_TEST_SUITE_END ()
Typedef Documentation
typedef InvertedFileReader<ShortIntFloat> Reader
Definition at line 11 of file TestInvertedFileReader.cpp.
typedef InvertedFileWriter<ShortIntFloat> Writer
Definition at line 12 of file TestInvertedFileReader.cpp.
Function Documentation
BOOST_AUTO_TEST_CASE (read)
Definition at line 26 of file TestInvertedFileReader.cpp.
References aitools::invertedindex::InvertedFileReader< Value >::close(), aitools::invertedindex::InvertedFileWriter< Value >::close(), aitools::invertedindex::Record< Value >::key(), aitools::invertedindex::InvertedFileReader< Value >::next(), aitools::invertedindex::Record< Value >::value(), and aitools::invertedindex::InvertedFileWriter< Value >::write().
BOOST_AUTO_TEST_CASE (explicit_ctor)
Definition at line 16 of file TestInvertedFileReader.cpp.
References aitools::invertedindex::InvertedFileWriter< Value >::close().
BOOST_AUTO_TEST_SUITE (inverted_file_reader)
BOOST_AUTO_TEST_SUITE_END ()