/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/reader/TestPostlistReader.cpp File Reference
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/reader/TestPostlistReader.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "PostlistBuilder.hpp"
#include "PostlistWriter.hpp"
#include "PostlistReader.hpp"
Functions
BOOST_AUTO_TEST_SUITE (postlist_reader)
void write_postlist (PostlistWriter &writer, size_t num, size_t length, size_t esize)
void read_postlist (PostlistReader &reader, size_t num, size_t length, size_t esize)
BOOST_AUTO_TEST_CASE (read_empty_postlist)
BOOST_AUTO_TEST_CASE (read_non_paged_postlist_with_constant_value_size)
BOOST_AUTO_TEST_CASE (read_non_paged_postlist_with_variable_value_size)
BOOST_AUTO_TEST_CASE (read_paged_postlist_with_constant_value_size)
BOOST_AUTO_TEST_CASE (read_paged_postlist_with_variable_value_size)
BOOST_AUTO_TEST_SUITE_END ()
Function Documentation
BOOST_AUTO_TEST_CASE (read_paged_postlist_with_variable_value_size)
Definition at line 146 of file TestPostlistReader.cpp.
References aitools::invertedindex::PostlistReader::close(), aitools::invertedindex::PostlistWriter::close(), read_postlist(), aitools::invertedindex::PostlistReader::rewind(), and write_postlist().
BOOST_AUTO_TEST_CASE (read_paged_postlist_with_constant_value_size)
Definition at line 123 of file TestPostlistReader.cpp.
References aitools::invertedindex::PostlistReader::close(), aitools::invertedindex::PostlistWriter::close(), read_postlist(), aitools::invertedindex::PostlistReader::rewind(), and write_postlist().
BOOST_AUTO_TEST_CASE (read_non_paged_postlist_with_variable_value_size)
Definition at line 100 of file TestPostlistReader.cpp.
References aitools::invertedindex::PostlistReader::close(), aitools::invertedindex::PostlistWriter::close(), read_postlist(), aitools::invertedindex::PostlistReader::rewind(), and write_postlist().
BOOST_AUTO_TEST_CASE (read_non_paged_postlist_with_constant_value_size)
Definition at line 79 of file TestPostlistReader.cpp.
References aitools::invertedindex::PostlistReader::close(), aitools::invertedindex::PostlistWriter::close(), read_postlist(), aitools::invertedindex::PostlistReader::rewind(), and write_postlist().
BOOST_AUTO_TEST_CASE (read_empty_postlist)
Definition at line 61 of file TestPostlistReader.cpp.
References aitools::invertedindex::PostlistReader::close(), aitools::invertedindex::PostlistWriter::close(), read_postlist(), and write_postlist().
BOOST_AUTO_TEST_SUITE (postlist_reader)
BOOST_AUTO_TEST_SUITE_END ()
void read_postlist (PostlistReader & reader, size_t num, size_t length, size_t esize)
Definition at line 33 of file TestPostlistReader.cpp.
References aitools::invertedindex::PostlistReader::read(), and aitools::invertedindex::PostlistReader::tell().
Referenced by BOOST_AUTO_TEST_CASE().
void write_postlist (PostlistWriter & writer, size_t num, size_t length, size_t esize)
The internals of this function are tested by TestPostlistBuilder and TestPostlistWriter.
Definition at line 16 of file TestPostlistReader.cpp.
References aitools::invertedindex::PostlistBuilder::append(), aitools::invertedindex::PostlistBuilder::build(), aitools::invertedindex::ByteBuffer::resize(), and aitools::invertedindex::PostlistWriter::write().
Referenced by BOOST_AUTO_TEST_CASE().