/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/util/TestVocabulary.cpp File Reference
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/util/TestVocabulary.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Vocabulary.hpp"
#include "Converter.hpp"
#include <sstream>
Functions
BOOST_AUTO_TEST_SUITE (vocabulary)
BOOST_AUTO_TEST_CASE (default_ctor)
BOOST_AUTO_TEST_CASE (explicit_ctor)
BOOST_AUTO_TEST_CASE (copy_ctor)
BOOST_AUTO_TEST_CASE (accumulate)
BOOST_AUTO_TEST_CASE (clear)
BOOST_AUTO_TEST_CASE (contains)
BOOST_AUTO_TEST_CASE (find)
BOOST_AUTO_TEST_CASE (get_words)
BOOST_AUTO_TEST_CASE (save_load)
BOOST_AUTO_TEST_SUITE_END ()
Function Documentation
BOOST_AUTO_TEST_CASE (save_load)
Definition at line 96 of file TestVocabulary.cpp.
References aitools::invertedindex::Vocabulary::clear(), aitools::invertedindex::Vocabulary::find(), aitools::invertedindex::Vocabulary::insert(), aitools::invertedindex::Vocabulary::load(), and aitools::invertedindex::Vocabulary::save().
BOOST_AUTO_TEST_CASE (get_words)
Definition at line 81 of file TestVocabulary.cpp.
References aitools::invertedindex::Vocabulary::find(), aitools::invertedindex::Vocabulary::get_words(), aitools::invertedindex::Vocabulary::insert(), and aitools::invertedindex::Vocabulary::size().
BOOST_AUTO_TEST_CASE (find)
Definition at line 71 of file TestVocabulary.cpp.
References aitools::invertedindex::Vocabulary::end(), aitools::invertedindex::Vocabulary::find(), and aitools::invertedindex::Vocabulary::insert().
BOOST_AUTO_TEST_CASE (contains)
Definition at line 58 of file TestVocabulary.cpp.
References aitools::invertedindex::Vocabulary::accumulate(), aitools::invertedindex::Vocabulary::contains(), and aitools::invertedindex::Vocabulary::insert().
BOOST_AUTO_TEST_CASE (clear)
Definition at line 47 of file TestVocabulary.cpp.
References aitools::invertedindex::Vocabulary::clear(), aitools::invertedindex::Vocabulary::insert(), aitools::invertedindex::Vocabulary::is_empty(), and aitools::invertedindex::Vocabulary::size().
BOOST_AUTO_TEST_CASE (accumulate)
Definition at line 36 of file TestVocabulary.cpp.
References aitools::invertedindex::Vocabulary::accumulate(), aitools::invertedindex::Vocabulary::find(), and aitools::invertedindex::Vocabulary::insert().
BOOST_AUTO_TEST_CASE (copy_ctor)
Definition at line 23 of file TestVocabulary.cpp.
References aitools::invertedindex::Vocabulary::contains(), aitools::invertedindex::Vocabulary::insert(), and aitools::invertedindex::Vocabulary::size().
BOOST_AUTO_TEST_CASE (explicit_ctor)
Definition at line 17 of file TestVocabulary.cpp.
BOOST_AUTO_TEST_CASE (default_ctor)
Definition at line 10 of file TestVocabulary.cpp.
References aitools::invertedindex::Vocabulary::is_empty(), and aitools::invertedindex::Vocabulary::size().
BOOST_AUTO_TEST_SUITE (vocabulary)
BOOST_AUTO_TEST_SUITE_END ()