/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/writer/TestPostlistWriter.cpp File Reference
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/writer/TestPostlistWriter.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "PostlistBuilder.hpp"
#include "PostlistWriter.hpp"
Functions
BOOST_AUTO_TEST_SUITE (postlist_writer)
BOOST_AUTO_TEST_CASE (explicit_ctor)
BOOST_AUTO_TEST_CASE (write_empty_postlist)
BOOST_AUTO_TEST_CASE (write_non_paged_postlist_with_constant_value_size)
BOOST_AUTO_TEST_CASE (write_non_paged_postlist_with_variable_value_size)
BOOST_AUTO_TEST_CASE (write_paged_postlist_with_constant_value_size)
BOOST_AUTO_TEST_CASE (write_paged_postlist_with_variable_value_size)
BOOST_AUTO_TEST_SUITE_END ()
Function Documentation
BOOST_AUTO_TEST_CASE (write_paged_postlist_with_variable_value_size)
Definition at line 105 of file TestPostlistWriter.cpp.
References aitools::invertedindex::PostlistBuilder::append(), aitools::invertedindex::PostlistBuilder::build(), and aitools::invertedindex::ByteBuffer::resize().
BOOST_AUTO_TEST_CASE (write_paged_postlist_with_constant_value_size)
Definition at line 83 of file TestPostlistWriter.cpp.
References aitools::invertedindex::PostlistBuilder::append(), and aitools::invertedindex::PostlistBuilder::build().
BOOST_AUTO_TEST_CASE (write_non_paged_postlist_with_variable_value_size)
Definition at line 59 of file TestPostlistWriter.cpp.
References aitools::invertedindex::PostlistBuilder::append(), aitools::invertedindex::PostlistBuilder::build(), and aitools::invertedindex::ByteBuffer::resize().
BOOST_AUTO_TEST_CASE (write_non_paged_postlist_with_constant_value_size)
Definition at line 37 of file TestPostlistWriter.cpp.
References aitools::invertedindex::PostlistBuilder::append(), and aitools::invertedindex::PostlistBuilder::build().
BOOST_AUTO_TEST_CASE (write_empty_postlist)
Definition at line 22 of file TestPostlistWriter.cpp.
References aitools::invertedindex::PostlistBuilder::build(), aitools::invertedindex::PostlistWriter::tell(), and aitools::invertedindex::PostlistWriter::write().
BOOST_AUTO_TEST_CASE (explicit_ctor)
Definition at line 9 of file TestPostlistWriter.cpp.
References aitools::invertedindex::PostlistWriter::close(), aitools::invertedindex::PostlistWriter::ready(), and aitools::invertedindex::PostlistWriter::tell().
BOOST_AUTO_TEST_SUITE (postlist_writer)
BOOST_AUTO_TEST_SUITE_END ()