/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/core/TestGenericRecord.cpp File Reference
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/core/TestGenericRecord.cpp File Reference
#include <boost/test/unit_test.hpp>
#include <boost/algorithm/string.hpp>
#include "GenericRecord.hpp"
#include "Converter.hpp"
#include <cstdio>
Functions
BOOST_AUTO_TEST_SUITE (generic_record)
BOOST_AUTO_TEST_CASE (default_ctor)
BOOST_AUTO_TEST_CASE (explicit_ctor)
BOOST_AUTO_TEST_CASE (copy_ctor)
BOOST_AUTO_TEST_CASE (assignment_operator)
BOOST_AUTO_TEST_CASE (write)
BOOST_AUTO_TEST_CASE (read)
BOOST_AUTO_TEST_SUITE_END ()
Function Documentation
BOOST_AUTO_TEST_CASE (read)
Definition at line 72 of file TestGenericRecord.cpp.
References aitools::util::fclose(), aitools::util::ftell(), aitools::invertedindex::GenericRecord::key(), aitools::invertedindex::GenericRecord::read(), aitools::invertedindex::ByteBuffer::resize(), aitools::util::rewind(), aitools::invertedindex::ByteBuffer::size(), aitools::invertedindex::GenericRecord::size(), aitools::util::tmpfile(), aitools::invertedindex::GenericRecord::value(), and aitools::invertedindex::GenericRecord::write().
BOOST_AUTO_TEST_CASE (write)
Definition at line 54 of file TestGenericRecord.cpp.
References aitools::util::fclose(), aitools::util::ftell(), aitools::invertedindex::GenericRecord::key(), aitools::invertedindex::ByteBuffer::resize(), aitools::invertedindex::GenericRecord::size(), aitools::util::tmpfile(), aitools::invertedindex::GenericRecord::value(), and aitools::invertedindex::GenericRecord::write().
BOOST_AUTO_TEST_CASE (assignment_operator)
Definition at line 36 of file TestGenericRecord.cpp.
BOOST_AUTO_TEST_CASE (copy_ctor)
Definition at line 27 of file TestGenericRecord.cpp.
BOOST_AUTO_TEST_CASE (explicit_ctor)
Definition at line 18 of file TestGenericRecord.cpp.
References aitools::invertedindex::GenericRecord::key(), and aitools::invertedindex::GenericRecord::value().
BOOST_AUTO_TEST_CASE (default_ctor)
Definition at line 11 of file TestGenericRecord.cpp.
References aitools::invertedindex::ByteBuffer::empty(), aitools::invertedindex::GenericRecord::key(), and aitools::invertedindex::GenericRecord::value().
BOOST_AUTO_TEST_SUITE (generic_record)
BOOST_AUTO_TEST_SUITE_END ()