/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/core/TestPostlistBuilder.cpp File Reference
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/core/TestPostlistBuilder.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "PostlistBuilder.hpp"
Functions
BOOST_AUTO_TEST_SUITE (postlist_builder)
BOOST_AUTO_TEST_CASE (default_ctor)
BOOST_AUTO_TEST_CASE (append)
BOOST_AUTO_TEST_CASE (iterator)
BOOST_AUTO_TEST_SUITE_END ()
Function Documentation
BOOST_AUTO_TEST_CASE (iterator)
Definition at line 29 of file TestPostlistBuilder.cpp.
References aitools::invertedindex::PostlistBuilder::append(), aitools::invertedindex::PostlistBuilder::build(), aitools::invertedindex::PostlistBuilder::empty(), aitools::invertedindex::PostlistBuilder::length(), and aitools::invertedindex::PostlistBuilder::set_checksum().
BOOST_AUTO_TEST_CASE (append)
Definition at line 15 of file TestPostlistBuilder.cpp.
References aitools::invertedindex::PostlistBuilder::append(), aitools::invertedindex::PostlistBuilder::empty(), aitools::invertedindex::PostlistBuilder::length(), and aitools::invertedindex::ByteBuffer::resize().
BOOST_AUTO_TEST_CASE (default_ctor)
Definition at line 8 of file TestPostlistBuilder.cpp.
References aitools::invertedindex::PostlistBuilder::empty(), and aitools::invertedindex::PostlistBuilder::length().
BOOST_AUTO_TEST_SUITE (postlist_builder)
BOOST_AUTO_TEST_SUITE_END ()