/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/writer/TestInvertedFileWriter.cpp File Reference
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/writer/TestInvertedFileWriter.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "InvertedFileWriter.hpp"
#include "ValueTypes.hpp"
#include "Converter.hpp"
#include "Record.hpp"
#include <cstdlib>
Typedefs
typedef InvertedFileWriter
< ShortIntFloat > Writer
Functions
BOOST_AUTO_TEST_SUITE (inverted_file_writer)
BOOST_AUTO_TEST_CASE (explicit_ctor)
BOOST_AUTO_TEST_CASE (write)
BOOST_AUTO_TEST_SUITE_END ()
Typedef Documentation
typedef InvertedFileWriter<ShortIntFloat> Writer
Definition at line 10 of file TestInvertedFileWriter.cpp.
Function Documentation
BOOST_AUTO_TEST_CASE (write)
Definition at line 23 of file TestInvertedFileWriter.cpp.
References aitools::invertedindex::InvertedFileWriter< Value >::close(), aitools::invertedindex::Record< Value >::key(), aitools::invertedindex::Record< Value >::value(), and aitools::invertedindex::InvertedFileWriter< Value >::write().
BOOST_AUTO_TEST_CASE (explicit_ctor)
Definition at line 14 of file TestInvertedFileWriter.cpp.
References aitools::invertedindex::InvertedFileWriter< Value >::close().
BOOST_AUTO_TEST_SUITE (inverted_file_writer)
BOOST_AUTO_TEST_SUITE_END ()