/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/core/TestIterator.cpp File Reference
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/core/TestIterator.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "PostlistBuilder.hpp"
Functions
BOOST_AUTO_TEST_SUITE (iterator)
BOOST_AUTO_TEST_CASE (get_next_from_empty)
BOOST_AUTO_TEST_CASE (get_next_constant_entry_size)
BOOST_AUTO_TEST_CASE (get_next_variable_entry_size)
BOOST_AUTO_TEST_CASE (is_paged_constant_entry_size)
BOOST_AUTO_TEST_CASE (is_paged_variable_entry_size)
BOOST_AUTO_TEST_SUITE_END ()
Function Documentation
BOOST_AUTO_TEST_CASE (is_paged_variable_entry_size)
Definition at line 115 of file TestIterator.cpp.
References aitools::invertedindex::PostlistBuilder::append(), aitools::invertedindex::PostlistBuilder::build(), and aitools::invertedindex::ByteBuffer::resize().
BOOST_AUTO_TEST_CASE (is_paged_constant_entry_size)
Definition at line 84 of file TestIterator.cpp.
References aitools::invertedindex::PostlistBuilder::append(), and aitools::invertedindex::PostlistBuilder::build().
BOOST_AUTO_TEST_CASE (get_next_variable_entry_size)
Definition at line 52 of file TestIterator.cpp.
References aitools::invertedindex::PostlistBuilder::append(), aitools::invertedindex::PostlistBuilder::build(), and aitools::invertedindex::ByteBuffer::resize().
BOOST_AUTO_TEST_CASE (get_next_constant_entry_size)
Definition at line 21 of file TestIterator.cpp.
References aitools::invertedindex::PostlistBuilder::append(), and aitools::invertedindex::PostlistBuilder::build().
BOOST_AUTO_TEST_CASE (get_next_from_empty)
Definition at line 8 of file TestIterator.cpp.
References aitools::invertedindex::PostlistBuilder::build().
BOOST_AUTO_TEST_SUITE (iterator)
BOOST_AUTO_TEST_SUITE_END ()