/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/core/TestMPHashFunction.cpp File Reference
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/core/TestMPHashFunction.cpp File Reference
#include <boost/test/unit_test.hpp>
#include <boost/filesystem/fstream.hpp>
#include "MPHashFunction.hpp"
#include "Vocabulary.hpp"
#include "Converter.hpp"
#include <vector>
Functions
BOOST_AUTO_TEST_SUITE (mp_hash_function)
BOOST_AUTO_TEST_CASE (default_ctor)
BOOST_AUTO_TEST_CASE (create_a)
BOOST_AUTO_TEST_CASE (create_b)
BOOST_AUTO_TEST_CASE (save_load)
BOOST_AUTO_TEST_SUITE_END ()
Function Documentation
BOOST_AUTO_TEST_CASE (save_load)
Definition at line 66 of file TestMPHashFunction.cpp.
References aitools::invertedindex::MPHashFunction::create(), aitools::invertedindex::MPHashFunction::hash(), aitools::util::hash(), aitools::invertedindex::Vocabulary::insert(), aitools::invertedindex::MPHashFunction::load(), aitools::invertedindex::MPHashFunction::save(), and aitools::invertedindex::MPHashFunction::size().
BOOST_AUTO_TEST_CASE (create_b)
Definition at line 44 of file TestMPHashFunction.cpp.
References aitools::invertedindex::MPHashFunction::create(), aitools::invertedindex::MPHashFunction::hash(), aitools::util::hash(), aitools::invertedindex::Vocabulary::insert(), and aitools::invertedindex::MPHashFunction::size().
BOOST_AUTO_TEST_CASE (create_a)
Definition at line 19 of file TestMPHashFunction.cpp.
References aitools::invertedindex::MPHashFunction::create(), aitools::invertedindex::MPHashFunction::hash(), aitools::util::hash(), and aitools::invertedindex::MPHashFunction::size().
BOOST_AUTO_TEST_CASE (default_ctor)
Definition at line 12 of file TestMPHashFunction.cpp.
References aitools::invertedindex::MPHashFunction::hash(), and aitools::invertedindex::MPHashFunction::size().
BOOST_AUTO_TEST_SUITE (mp_hash_function)
BOOST_AUTO_TEST_SUITE_END ()