/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/core/TestRecord.cpp File Reference
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/core/TestRecord.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "ValueTypes.hpp"
#include "Converter.hpp"
#include "Record.hpp"
#include <sstream>
Functions
BOOST_AUTO_TEST_SUITE (record)
BOOST_AUTO_TEST_CASE (default_ctor)
BOOST_AUTO_TEST_CASE (explicit_ctor)
BOOST_AUTO_TEST_CASE (copy_ctor)
BOOST_AUTO_TEST_CASE (equalitiy_operator)
BOOST_AUTO_TEST_CASE (assignment_operator)
BOOST_AUTO_TEST_CASE (parse)
BOOST_AUTO_TEST_CASE (print)
BOOST_AUTO_TEST_CASE (to_generic)
BOOST_AUTO_TEST_SUITE_END ()
Function Documentation
BOOST_AUTO_TEST_CASE (to_generic)
Definition at line 81 of file TestRecord.cpp.
References aitools::invertedindex::Record< Value >::key(), aitools::invertedindex::GenericRecord::key(), aitools::invertedindex::ByteBuffer::size(), aitools::invertedindex::Record< Value >::to_generic(), and aitools::invertedindex::GenericRecord::value().
BOOST_AUTO_TEST_CASE (print)
Definition at line 67 of file TestRecord.cpp.
References aitools::invertedindex::Record< Value >::key().
BOOST_AUTO_TEST_CASE (parse)
Definition at line 56 of file TestRecord.cpp.
BOOST_AUTO_TEST_CASE (assignment_operator)
Definition at line 46 of file TestRecord.cpp.
BOOST_AUTO_TEST_CASE (equalitiy_operator)
Definition at line 37 of file TestRecord.cpp.
BOOST_AUTO_TEST_CASE (copy_ctor)
Definition at line 28 of file TestRecord.cpp.
BOOST_AUTO_TEST_CASE (explicit_ctor)
Definition at line 19 of file TestRecord.cpp.
References aitools::invertedindex::Record< Value >::key(), and aitools::invertedindex::Record< Value >::value().
BOOST_AUTO_TEST_CASE (default_ctor)
Definition at line 11 of file TestRecord.cpp.
References aitools::invertedindex::Record< Value >::key(), and aitools::invertedindex::Record< Value >::value().
BOOST_AUTO_TEST_SUITE (record)
BOOST_AUTO_TEST_SUITE_END ()