/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/core/TestPostlist.cpp File Reference
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/core/TestPostlist.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "PostlistBuilder.hpp"
#include "ValueTypes.hpp"
#include "Converter.hpp"
#include "Postlist.hpp"
Functions
BOOST_AUTO_TEST_SUITE (postlist)
BOOST_AUTO_TEST_CASE (get_next_from_empty)
BOOST_AUTO_TEST_CASE (get_next_constant_value_size)
BOOST_AUTO_TEST_CASE (get_next_variable_value_size)
BOOST_AUTO_TEST_CASE (is_paged_constant_value_size)
BOOST_AUTO_TEST_CASE (is_paged_variable_value_size)
BOOST_AUTO_TEST_SUITE_END ()
Function Documentation
BOOST_AUTO_TEST_CASE (is_paged_variable_value_size)
Definition at line 127 of file TestPostlist.cpp.
References aitools::invertedindex::PostlistBuilder::append(), aitools::invertedindex::PostlistBuilder::build(), aitools::invertedindex::PairString< T >::e1(), aitools::invertedindex::PairString< T >::e2(), and aitools::invertedindex::PairString< T >::to_bytes().
BOOST_AUTO_TEST_CASE (is_paged_constant_value_size)
Definition at line 95 of file TestPostlist.cpp.
References aitools::invertedindex::PostlistBuilder::append(), aitools::invertedindex::PostlistBuilder::build(), aitools::invertedindex::Triple< T1, T2, T3 >::e1(), and aitools::invertedindex::Triple< T1, T2, T3 >::to_bytes().
BOOST_AUTO_TEST_CASE (get_next_variable_value_size)
Definition at line 59 of file TestPostlist.cpp.
References aitools::invertedindex::PostlistBuilder::append(), aitools::invertedindex::PostlistBuilder::build(), aitools::invertedindex::PairString< T >::e1(), aitools::invertedindex::PairString< T >::e2(), and aitools::invertedindex::PairString< T >::to_bytes().
BOOST_AUTO_TEST_CASE (get_next_constant_value_size)
Definition at line 26 of file TestPostlist.cpp.
References aitools::invertedindex::PostlistBuilder::append(), aitools::invertedindex::PostlistBuilder::build(), aitools::invertedindex::Triple< T1, T2, T3 >::e1(), and aitools::invertedindex::Triple< T1, T2, T3 >::to_bytes().
BOOST_AUTO_TEST_CASE (get_next_from_empty)
Definition at line 11 of file TestPostlist.cpp.
References aitools::invertedindex::PostlistBuilder::build().
BOOST_AUTO_TEST_SUITE (postlist)
BOOST_AUTO_TEST_SUITE_END ()