/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/core/TestByteBuffer.cpp File Reference
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/core/TestByteBuffer.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "ByteBuffer.hpp"
#include <stdint.h>
#include <cstring>
Functions
BOOST_AUTO_TEST_SUITE (byte_buffer)
BOOST_AUTO_TEST_CASE (explicit_ctor)
BOOST_AUTO_TEST_CASE (copy_ctor)
BOOST_AUTO_TEST_CASE (clear)
BOOST_AUTO_TEST_CASE (free)
BOOST_AUTO_TEST_CASE (empty)
BOOST_AUTO_TEST_CASE (assignment_operator)
BOOST_AUTO_TEST_CASE (resize)
BOOST_AUTO_TEST_CASE (size)
BOOST_AUTO_TEST_CASE (capacity)
BOOST_AUTO_TEST_SUITE_END ()
Function Documentation
BOOST_AUTO_TEST_CASE (capacity)
Definition at line 88 of file TestByteBuffer.cpp.
References aitools::invertedindex::ByteBuffer::capacity(), aitools::invertedindex::ByteBuffer::resize(), and aitools::invertedindex::ByteBuffer::size().
BOOST_AUTO_TEST_CASE (size)
Definition at line 80 of file TestByteBuffer.cpp.
References aitools::invertedindex::ByteBuffer::size().
BOOST_AUTO_TEST_CASE (resize)
Definition at line 70 of file TestByteBuffer.cpp.
References aitools::invertedindex::ByteBuffer::resize(), and aitools::invertedindex::ByteBuffer::size().
BOOST_AUTO_TEST_CASE (assignment_operator)
Definition at line 59 of file TestByteBuffer.cpp.
References aitools::invertedindex::ByteBuffer::data(), aitools::invertedindex::ByteBuffer::resize(), and aitools::invertedindex::ByteBuffer::size().
BOOST_AUTO_TEST_CASE (empty)
Definition at line 49 of file TestByteBuffer.cpp.
References aitools::invertedindex::ByteBuffer::empty().
BOOST_AUTO_TEST_CASE (free)
Definition at line 38 of file TestByteBuffer.cpp.
References aitools::invertedindex::ByteBuffer::capacity(), aitools::invertedindex::ByteBuffer::data(), aitools::invertedindex::ByteBuffer::free(), and aitools::invertedindex::ByteBuffer::size().
BOOST_AUTO_TEST_CASE (clear)
Definition at line 29 of file TestByteBuffer.cpp.
References aitools::invertedindex::ByteBuffer::capacity(), aitools::invertedindex::ByteBuffer::clear(), aitools::invertedindex::ByteBuffer::empty(), and aitools::invertedindex::ByteBuffer::size().
BOOST_AUTO_TEST_CASE (copy_ctor)
Definition at line 21 of file TestByteBuffer.cpp.
References aitools::invertedindex::ByteBuffer::data(), and aitools::invertedindex::ByteBuffer::size().
BOOST_AUTO_TEST_CASE (explicit_ctor)
Definition at line 10 of file TestByteBuffer.cpp.
References aitools::invertedindex::ByteBuffer::data().
BOOST_AUTO_TEST_SUITE (byte_buffer)
BOOST_AUTO_TEST_SUITE_END ()