/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/core/TestQuantile.cpp File Reference
/home/palakars/workspace-inprogress/code-in-progress/aitools3/aitools3-aq-invertedindex-cpp/test/core/TestQuantile.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Converter.hpp"
#include "Quantile.hpp"
#include <sstream>
Functions
BOOST_AUTO_TEST_SUITE (quantile)
BOOST_AUTO_TEST_CASE (default_ctor)
BOOST_AUTO_TEST_CASE (copy_ctor)
BOOST_AUTO_TEST_CASE (clear)
BOOST_AUTO_TEST_CASE (assignment_operator)
BOOST_AUTO_TEST_CASE (add_up_operator)
BOOST_AUTO_TEST_CASE (parse)
BOOST_AUTO_TEST_CASE (print)
BOOST_AUTO_TEST_SUITE_END ()
Function Documentation
BOOST_AUTO_TEST_CASE (print)
Definition at line 87 of file TestQuantile.cpp.
References aitools::invertedindex::Quantile::print(), and aitools::invertedindex::Quantile::values().
BOOST_AUTO_TEST_CASE (parse)
Definition at line 76 of file TestQuantile.cpp.
References aitools::invertedindex::Quantile::parse(), and aitools::invertedindex::Quantile::values().
BOOST_AUTO_TEST_CASE (add_up_operator)
Definition at line 62 of file TestQuantile.cpp.
References aitools::invertedindex::Quantile::values().
BOOST_AUTO_TEST_CASE (assignment_operator)
Definition at line 47 of file TestQuantile.cpp.
References aitools::invertedindex::Quantile::values().
BOOST_AUTO_TEST_CASE (clear)
Definition at line 33 of file TestQuantile.cpp.
References aitools::invertedindex::Quantile::clear(), and aitools::invertedindex::Quantile::values().
BOOST_AUTO_TEST_CASE (copy_ctor)
Definition at line 19 of file TestQuantile.cpp.
References aitools::invertedindex::Quantile::values().
BOOST_AUTO_TEST_CASE (default_ctor)
Definition at line 10 of file TestQuantile.cpp.
References aitools::invertedindex::Quantile::values().
BOOST_AUTO_TEST_SUITE (quantile)
BOOST_AUTO_TEST_SUITE_END ()